-- 正規ソース: supabase/schemas/organization_scenarios.sql
-- 最終更新: 2026-04-10
CREATE TABLE public.organization_scenarios (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  organization_id UUID NOT NULL REFERENCES public.organizations(id),
  scenario_master_id UUID NOT NULL REFERENCES public.scenario_masters(id),
  slug TEXT,
  duration INTEGER,
  participation_fee INTEGER,
  extra_preparation_time INTEGER,
  org_status TEXT NOT NULL DEFAULT 'available'::text,
  custom_key_visual_url TEXT,
  custom_description TEXT,
  custom_synopsis TEXT,
  custom_caution TEXT,
  pricing_patterns JSONB DEFAULT '[]'::jsonb,
  gm_assignments JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  participation_costs JSONB DEFAULT '[]'::jsonb,
  gm_test_participation_fee INTEGER,
  flexible_pricing JSONB,
  use_flexible_pricing BOOLEAN DEFAULT FALSE,
  license_amount INTEGER,
  gm_test_license_amount INTEGER,
  franchise_license_amount INTEGER,
  franchise_gm_test_license_amount INTEGER,
  gm_costs JSONB DEFAULT '[]'::jsonb,
  gm_count INTEGER,
  available_gms TEXT[] DEFAULT '{}'::text[],
  experienced_staff TEXT[] DEFAULT '{}'::text[],
  available_stores TEXT[] DEFAULT '{}'::text[],
  production_cost INTEGER DEFAULT 0,
  production_costs JSONB DEFAULT '[]'::jsonb,
  depreciation_per_performance INTEGER,
  play_count INTEGER DEFAULT 0,
  notes TEXT,
  override_title TEXT,
  override_author TEXT,
  override_player_count_min INTEGER,
  override_player_count_max INTEGER,
  override_difficulty TEXT,
  override_genre TEXT[],
  override_has_pre_reading BOOLEAN,
  override_required_items TEXT[],
  weekend_duration INTEGER,
  external_license_amount INTEGER,
  external_gm_test_license_amount INTEGER,
  fc_receive_license_amount INTEGER,
  fc_receive_gm_test_license_amount INTEGER,
  fc_author_license_amount INTEGER,
  fc_author_gm_test_license_amount INTEGER,
  kit_count INTEGER DEFAULT 1,
  is_recommended BOOLEAN DEFAULT FALSE,
  survey_deadline_days INTEGER DEFAULT 1,
  survey_url TEXT,
  survey_enabled BOOLEAN DEFAULT FALSE,
  characters JSONB DEFAULT '[]'::jsonb,
  pre_reading_notice_message TEXT,
  male_count INTEGER,
  female_count INTEGER,
  other_count INTEGER,
  scenario_type TEXT DEFAULT 'normal'::text,
  report_display_name TEXT,
  private_booking_blocked_slots TEXT[],
  booking_start_date DATE,
  booking_end_date DATE,
  individual_notice_template TEXT,
  character_assignment_method TEXT NOT NULL DEFAULT 'survey'::text,
  private_booking_time_slots TEXT[],
  UNIQUE (organization_id, scenario_master_id)
);

-- Indexes
CREATE INDEX idx_org_scenarios_master_id ON public.organization_scenarios USING btree (scenario_master_id);
CREATE INDEX idx_org_scenarios_org_id ON public.organization_scenarios USING btree (organization_id);
CREATE INDEX idx_org_scenarios_slug ON public.organization_scenarios USING btree (organization_id, slug);
CREATE INDEX idx_org_scenarios_status ON public.organization_scenarios USING btree (org_status);
