import { test, expect } from '@playwright/test'
test('予約時に条件を確認し人数変更と公演切替で古い割引を使わない',async({page},testInfo)=>{
 await page.goto('/e2e/fixtures/booking-settings.html')
 await page.getByLabel('クーポン',{exact:true}).selectOption('valid')
 await expect(page.getByRole('button',{name:'予約確定',exact:true})).toBeDisabled()
 await expect(page.getByText('1,000円割引。予約確定時に利用します。')).toBeVisible()
 await page.getByLabel('人数',{exact:true}).fill('2')
 await expect(page.getByRole('button',{name:'予約確定',exact:true})).toBeDisabled()
 await expect(page.getByText('2,000円割引。予約確定時に利用します。')).toBeVisible()
 await page.getByLabel('クーポン',{exact:true}).selectOption('invalid')
 await expect(page.getByRole('alert')).toHaveText('対象シナリオではありません')
 await expect(page.getByRole('button',{name:'予約確定',exact:true})).toBeDisabled()
 await page.getByLabel('クーポン',{exact:true}).selectOption('')
 await expect(page.getByRole('button',{name:'予約確定',exact:true})).toBeEnabled()
 await page.getByLabel('クーポン',{exact:true}).selectOption('valid')
 await page.getByRole('button',{name:'公演を切替'}).click()
 await expect(page.getByLabel('クーポン',{exact:true})).toHaveValue('')
 await page.setViewportSize({width:390,height:844})
 expect(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth)).toBe(true)
 await page.screenshot({path:testInfo.outputPath('mobile.png'),fullPage:true})
})
test('店舗の旧公演時間から組織共通へ戻して保存できる',async({page})=>{
 await page.goto('/e2e/fixtures/booking-settings.html')
 await expect(page.getByLabel('作品未選択時の公演時間（分）',{exact:true})).toHaveValue('240')
 await page.getByText('項目ごとの設定元を確認・変更').click()
 await page.getByRole('combobox',{name:'作品未選択時の公演時間（分）の設定元'}).click()
 await page.getByRole('option',{name:'共通設定を使う（組織共通）'}).click()
 await expect(page.getByLabel('作品未選択時の公演時間（分）',{exact:true})).toHaveValue('210')
 await page.getByRole('button',{name:'保存',exact:true}).click()
 await expect(page.getByText('設定元：組織共通')).toBeVisible()
})
