import { test, expect } from '@playwright/test'
test('判断期限と予約締切を分けて表示し、公演指定と標準復帰を保存できる', async ({ page }, testInfo) => {
 await page.goto('/e2e/fixtures/booking-cutoff.html')
 await expect(page.getByRole('heading', { name: '開催判断の期限' })).toBeVisible()
 await expect(page.getByRole('heading', { name: '開催決定後の予約受付締切' })).toBeVisible()
 await page.getByLabel('公演開始の何分前まで予約を受け付けるか').fill('60')
 await page.getByRole('button', { name: 'シナリオの予約締切を保存' }).click()
 await expect(page.getByText('シナリオの予約締切を保存しました。', { exact: true })).toBeVisible()
 await page.getByRole('combobox').click()
 await page.getByRole('option', { name: 'この公演だけ指定する' }).click()
 await page.getByLabel('公演開始の何分前まで受け付けるか').fill('30')
 await page.getByRole('button', { name: '予約締切を保存', exact: true }).click()
 await expect(page.getByText('予約受付の締切を保存しました。', { exact: true })).toBeVisible()
 await expect(page.getByText('9/8 17:30（日本時間）', { exact: true })).toBeVisible()
 await page.screenshot({ path: testInfo.outputPath('desktop.png'), fullPage: true })
 await page.setViewportSize({ width: 390, height: 844 })
 await page.screenshot({ path: testInfo.outputPath('mobile.png'), fullPage: true })
 expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
 await page.getByRole('combobox').click()
 await page.getByRole('option', { name: 'シナリオ設定を使う（0分前）' }).click()
 await page.getByRole('button', { name: '予約締切を保存', exact: true }).click()
 await expect(page.getByText('9/8 18:00（日本時間）', { exact: true })).toBeVisible()
})
