import {test,expect} from '@playwright/test'
test.beforeEach(async({page})=>{page.on('pageerror',error=>{throw error});await page.route('**/*',route=>new URL(route.request().url()).hostname==='127.0.0.1'?route.continue():route.abort());await page.goto('/e2e/fixtures/functional-qa.html')})
async function counts(page:any){await page.getByText('試験結果を取得',{exact:true}).evaluate((button:HTMLButtonElement)=>button.click());return JSON.parse(await page.locator('#counts').innerText())}
test('確定画面で作品・日時・店舗を表示しサーバー金額とJSTを保持',async({page})=>{
 await expect(page.getByText('QA店舗',{exact:true}).first()).toBeVisible();await expect(page.getByText('QA作品',{exact:true}).first()).toBeVisible()
 await page.getByRole('button',{name:'予約を確定する',exact:true}).click();await expect(page.getByText('マイページで予約を確認')).toBeVisible()
 await page.screenshot({path:'/tmp/mmq-functional-booking-success.png',fullPage:true});const s=await counts(page);expect(s.payload).toMatchObject({store_id:'qa-store',schedule_event_id:'qa-event',requested_datetime:'2098-10-01T10:00+09:00',participant_count:2,total_price:9000});expect(s.writes).toBe(1);await expect(page.getByText('8,000',{exact:false}).first()).toBeVisible()
})
for(const mode of ['email-false','email-error','email-throw','email-skip']) test(mode+'でも予約確定を維持し再予約を誘わない',async({page})=>{await page.getByLabel('試験モード').selectOption(mode);await page.getByRole('button',{name:'予約を確定する',exact:true}).click();await expect(page.getByText(/予約は確定しましたが/)).toBeVisible();expect((await counts(page)).writes).toBe(1)})
for(const mode of ['sold-out','seat-race','read-error','server-race','offline']) test(mode+'を成功表示しない',async({page})=>{await page.getByLabel('試験モード').selectOption(mode);await page.getByRole('button',{name:'予約を確定する',exact:true}).click();await expect(page.getByText('マイページで予約を確認')).not.toBeVisible();await expect(page.getByText(/満席|残り1名|予約制限|残席が|通信に失敗/).first()).toBeVisible();expect((await counts(page)).sends).toBe(0)})
test('担当作品の登録と再読み込み保持、変更、解除を実画面で確認',async({page})=>{await page.getByText('担当作品画面',{exact:true}).click();const row=page.getByText('QA作品',{exact:true}).locator('../..');await row.getByRole('button').last().click();await page.getByRole('button',{name:'保存',exact:true}).click();await expect(page.getByText('保存しました',{exact:true})).toBeVisible();await page.reload();await page.getByText('担当作品画面',{exact:true}).click();await expect(page.getByText('GM可能作品').locator('../..')).toContainText('1');await page.getByText('QA作品',{exact:true}).locator('../..').getByRole('button').last().click();await page.getByRole('button',{name:'保存',exact:true}).click();await page.screenshot({path:'/tmp/mmq-functional-staff-success.png',fullPage:true});expect((await counts(page)).assignments[0]).toMatchObject({can_main_gm:false,is_experienced:true})})
test('担当保存通信失敗は成功表示せず選択を保持',async({page})=>{await page.getByLabel('試験モード').selectOption('offline');await page.getByText('担当作品画面',{exact:true}).click();await page.getByText('QA作品',{exact:true}).locator('../..').getByRole('button').last().click();await page.getByRole('button',{name:'保存',exact:true}).click();await expect(page.getByText(/保存を確認できませんでした/)).toBeVisible();await expect(page.getByText('GM可能作品').locator('../..')).toContainText('1');await expect(page.getByText('保存しました',{exact:true})).not.toBeVisible()})

test('連続クリックでも保存・メールinvokeは1回',async({page})=>{await page.getByRole('button',{name:'予約を確定する',exact:true}).evaluate((button:HTMLButtonElement)=>{button.click();button.click()});await expect(page.getByText('マイページで予約を確認')).toBeVisible();const s=await counts(page);expect(s.writes).toBe(1);expect(s.sends).toBe(1)})
test('認証中断では確定できずAPIへ書き込まない',async({page})=>{await page.getByLabel('試験モード').selectOption('signed-out');await page.getByPlaceholder('山田 太郎').fill('QA顧客');await page.getByPlaceholder('example@example.com').fill('qa@example.invalid');await page.getByPlaceholder('090-1234-5678').fill('09012345678');await page.getByRole('button',{name:'予約を確定する',exact:true}).click();await expect(page.getByText('ログインが必要です',{exact:true}).first()).toBeVisible();expect((await counts(page)).writes).toBe(0)})
test('担当作品の権限拒否は成功表示しない',async({page})=>{await page.getByLabel('試験モード').selectOption('forbidden');await page.getByText('担当作品画面',{exact:true}).click();await page.getByText('QA作品',{exact:true}).locator('../..').getByRole('button').last().click();await page.getByRole('button',{name:'保存',exact:true}).click();await expect(page.getByText(/保存する権限を確認できませんでした/)).toBeVisible();await expect(page.getByText('保存しました',{exact:true})).not.toBeVisible()})
test('担当作品読取失敗を空の担当表として保存しない',async({page})=>{await page.getByLabel('試験モード').selectOption('load-error');await page.getByText('担当作品画面',{exact:true}).click();await page.getByRole('button',{name:'保存',exact:true}).click();expect((await counts(page)).writes).toBe(0)})
test('担当の全件解除は確認するまで書き込まず、解除後の再読込を維持',async({page})=>{await page.getByText('担当作品画面',{exact:true}).click();const row=page.getByText('QA作品',{exact:true}).locator('../..');await row.getByRole('button').first().click();await page.getByRole('button',{name:'保存',exact:true}).click();await expect(page.getByText('保存しました',{exact:true})).toBeVisible();await row.getByRole('button').first().click();await page.getByRole('button',{name:'保存',exact:true}).click();await expect(page.getByRole('button',{name:'全件解除する',exact:true})).toBeVisible();expect((await counts(page)).writes).toBe(1);await page.getByRole('button',{name:'全件解除する',exact:true}).click();expect((await counts(page)).writes).toBe(2);expect((await counts(page)).assignments).toEqual([]);await page.reload();await page.getByText('担当作品画面',{exact:true}).click();await expect(page.getByText('体験済み作品').locator('../..')).toContainText('0')})

test('確定後の再読み込みで既存予約を検出し再予約を防ぐ（DB読戻しモック）',async({page})=>{await page.getByRole('button',{name:'予約を確定する',exact:true}).click();await expect(page.getByText('マイページで予約を確認')).toBeVisible();await page.reload();await expect(page.getByRole('button',{name:'重複のため予約不可',exact:true})).toBeDisabled();expect((await counts(page)).writes).toBe(0)})
test('不正な電話番号では確定せず入力エラーを表示',async({page})=>{await page.getByPlaceholder('090-1234-5678').fill('123');await page.getByRole('button',{name:'予約を確定する',exact:true}).click();await expect(page.getByText('電話番号は10〜11桁で入力してください',{exact:true}).first()).toBeVisible();expect((await counts(page)).writes).toBe(0)})
