import { test, expect } from '@playwright/test'
test('共通の割合を変更すると端数を切り捨てて例を即時更新し保存できる', async ({ page }, testInfo) => {
 await page.goto('/e2e/fixtures/recruitment-settings.html?common')
 const example = page.getByTestId('recruitment-example')
 await expect(example).toContainText('不足3人以内')
 await expect(example).toContainText('4人以上')
 await page.getByLabel('不足人数の割合').fill('30')
 await expect(example).toContainText('不足2人以内')
 await expect(example).toContainText('5人以上')
 await page.getByLabel('不足人数の割合').fill('1')
 await expect(example).toContainText('不足1人でも追加募集の対象にはなりません')
 await page.getByLabel('不足人数の割合').fill('')
 await expect(example).toContainText('有効な整数を入力')
 await page.getByRole('button', { name: '保存', exact: true }).click()
 await expect(page.getByRole('alert')).toContainText('整数')
 await page.getByLabel('不足人数の割合').fill('30')
 await page.getByRole('button', { name: '保存', exact: true }).click()
 await expect(page.getByRole('status')).toContainText('共通設定を保存しました')
 await expect(page.getByLabel('不足人数の割合')).toHaveValue('30')
 await page.screenshot({ path: testInfo.outputPath('common-desktop.png'), fullPage: true })
 await page.setViewportSize({ width: 390, height: 844 })
 await page.screenshot({ path: testInfo.outputPath('common-mobile.png'), fullPage: true })
 expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})
test('シナリオで共通から個別へ切替え、割合と人数を保存できる', async ({ page }, testInfo) => {
 await page.goto('/e2e/fixtures/recruitment-settings.html')
 await expect(page.getByTestId('recruitment-example')).toContainText('不足3人以内')
 await page.getByLabel('追加募集の対象', { exact: true }).click()
 await page.getByRole('option', { name: 'このシナリオだけ指定' }).click()
 await page.getByLabel('対象の指定方法').click()
 await page.getByRole('option', { name: '割合で指定' }).click()
 await page.getByLabel('不足人数の割合').fill('20')
 await expect(page.getByTestId('recruitment-example')).toContainText('不足1人以内')
 await page.getByLabel('追加募集の期限').fill('60')
 await page.getByRole('button', { name: '追加募集設定を保存' }).click()
 await expect(page.getByRole('status')).toContainText('保存しました')
 await expect(page.getByLabel('不足人数の割合')).toHaveValue('20')
 await expect(page.getByText(/14:00に判断し、不足1人以内なら17:00まで募集/)).toBeVisible()
 await page.getByLabel('対象の指定方法').click()
 await page.getByRole('option', { name: '人数で指定' }).click()
 await page.getByLabel('不足人数の上限').fill('3')
 await expect(page.getByTestId('recruitment-example')).toContainText('4人以上')
 await page.getByRole('button', { name: '追加募集設定を保存' }).click()
 await expect(page.getByRole('status')).toContainText('保存しました')
 await expect(page.getByLabel('不足人数の上限')).toHaveValue('3')
 await page.screenshot({ path: testInfo.outputPath('scenario-desktop.png'), fullPage: true })
 await page.setViewportSize({ width: 390, height: 844 })
 await page.screenshot({ path: testInfo.outputPath('scenario-mobile.png'), fullPage: true })
 expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})
