import { test, expect } from '@playwright/test'

test('設定一覧を4区分で表示し、管理者だけにMMQ全体を案内する', async ({ page }, info) => {
  await page.goto('/e2e/fixtures/settings-structure.html')
  for (const label of ['組織共通', '店舗別', '作品別', '公演別']) await expect(page.getByRole('heading', { name: label, exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'MMQ全体の管理' })).toHaveCount(0)
  await expect(page.getByText('その他の既存設定', { exact: true })).toHaveCount(0)
  await expect(page.getByRole('link', { name: '料金設定（既存）' })).toHaveCount(0)
  await expect(page.getByRole('link', { name: '売上レポート設定（既存）' })).toHaveCount(0)
  await expect(page.getByRole('link', { name: '支払い方法の案内', exact: true })).toHaveAttribute('href', '/test-org/settings?tab=reservation')
  await page.screenshot({ path: info.outputPath('settings-desktop.png'), fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: info.outputPath('settings-mobile.png'), fullPage: true })
  await page.goto('/e2e/fixtures/settings-structure.html?platform')
  await expect(page.getByRole('heading', { name: 'MMQ全体の管理' })).toBeVisible()
})

test('店舗Bから開くとBの値を読みBだけに保存し、店舗切替後はAの値になる', async ({ page }) => {
  await page.goto('/e2e/fixtures/settings-structure.html?mode=reservation')
  await expect(page.getByRole('textbox').first()).toHaveValue('店舗Bの案内')
  await expect(page.getByText('1回の予約の最大人数', { exact: true })).toHaveCount(0)
  await expect(page.getByText('顧客あたりの最大予約数', { exact: true })).toHaveCount(0)
  await expect(page.getByText('電話番号認証を要求', { exact: true })).toHaveCount(0)
  await expect(page.getByText('支払い方法の案内', { exact: true })).toBeVisible()
  await page.getByRole('textbox').first().fill('カード決済可')
  await page.getByRole('button', { name: '保存', exact: true }).click()
  const writes = await page.evaluate(() => JSON.parse(document.documentElement.dataset.writes || '[]'))
  expect(writes).toHaveLength(1)
  expect(writes[0].payload).not.toHaveProperty('max_participants_per_booking')
  expect(writes[0].payload).not.toHaveProperty('max_bookings_per_customer')
  expect(writes[0].payload).not.toHaveProperty('require_phone_verification')
  for (const field of ['advance_booking_days', 'same_day_booking_cutoff', 'private_booking_deadline_days']) expect(writes[0].payload).not.toHaveProperty(field)
  expect(writes[0]).toMatchObject({ table: 'reservation_settings', filters: { id: 'setting-b' }, payload: { payment_method_label: 'カード決済可' } })
  await page.getByRole('combobox').first().click()
  await page.getByRole('option', { name: '店舗A', exact: true }).click()
  await expect(page.getByRole('textbox').first()).toHaveValue('店舗Aの案内')
})

test('組織通知と店舗通知を別々に保存し、隠れた範囲を上書きしない', async ({ page }) => {
  await page.goto('/e2e/fixtures/settings-structure.html?mode=org-notifications')
  await expect(page.getByText('組織全体の通知設定', { exact: true })).toBeVisible()
  await expect(page.getByText('予約関連通知', { exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: '保存', exact: true }).click()
  let writes = await page.evaluate(() => JSON.parse(document.documentElement.dataset.writes || '[]'))
  expect(writes.map((w: { table: string }) => w.table)).toEqual(['global_settings'])
  await page.goto('/e2e/fixtures/settings-structure.html?mode=store-notifications')
  await expect(page.getByText('予約関連通知', { exact: true })).toBeVisible()
  await expect(page.getByText('組織全体の通知設定', { exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: '保存', exact: true }).click()
  writes = await page.evaluate(() => JSON.parse(document.documentElement.dataset.writes || '[]'))
  expect(writes).toHaveLength(1)
  expect(writes[0]).toMatchObject({ table: 'notification_settings', filters: { id: 'setting-b' } })
})

test('公演の組織共通時間帯は店舗の所要時間を保存しない', async ({ page }) => {
  await page.goto('/e2e/fixtures/settings-structure.html?mode=org-time')
  await expect(page.getByText('デフォルト公演時間', { exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: '保存', exact: true })).toHaveCount(1)
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect.poll(() => page.evaluate(() => !!document.documentElement.dataset.timeSaved)).toBe(true)
  expect(await page.evaluate(() => document.documentElement.dataset.writes)).toBeUndefined()
})

test('作品の設定元を示し、共通情報に戻す操作で上書きを解除する', async ({ page }, info) => {
  await page.goto('/e2e/fixtures/settings-structure.html?mode=scenario')
  await page.getByText('共通情報と自社設定', { exact: true }).click()
  const row = page.getByRole('row').filter({ has: page.getByRole('rowheader', { name: 'タイトル', exact: true }) })
  await expect(row).toContainText('自社設定')
  await row.getByRole('button', { name: '共通情報に戻す' }).click()
  await expect(row).toContainText('未保存')
  await page.getByRole('button', { name: '作品設定を保存' }).click()
  const saved = await page.evaluate(() => JSON.parse(document.documentElement.dataset.sourceSaved || '{}'))
  expect(saved.override_title).toBeNull()
  expect(saved.override_author).toBeNull()
  await page.screenshot({ path: info.outputPath('scenario-sources.png'), fullPage: true })
})


test('貸切締切は共通7日を継承し、0日で上書きして共通へ戻せる', async ({ page }, info) => {
  await page.goto('/e2e/fixtures/settings-structure.html?mode=private-deadline')
  await expect(page.getByText('適用する締切：公演日の7日前まで（組織共通）')).toBeVisible()
  await page.getByRole('combobox').click()
  await page.getByRole('option', { name: 'このシナリオで指定', exact: true }).click()
  await page.getByRole('spinbutton').fill('0')
  await page.getByRole('button', { name: '貸切の受付締切を保存', exact: true }).click()
  await expect(page.getByText('貸切予約の受付締切を保存しました。')).toBeVisible()
  await expect(page.getByText('適用する締切：公演日の0日前まで（このシナリオの個別指定）')).toBeVisible()
  expect(await page.evaluate(() => JSON.parse(document.documentElement.dataset.privateSaved || '{}').days)).toBe(0)
  await page.getByRole('combobox').click()
  await page.getByRole('option', { name: '共通設定を使う', exact: true }).click()
  await page.getByRole('button', { name: '貸切の受付締切を保存', exact: true }).click()
  await expect(page.getByText('貸切予約の受付締切を保存しました。')).toBeVisible()
  expect(await page.evaluate(() => JSON.parse(document.documentElement.dataset.privateSaved || '{}').days)).toBeNull()
  await expect(page.getByText('適用する締切：公演日の7日前まで（組織共通）')).toBeVisible()
  await page.screenshot({ path: info.outputPath('private-deadline-inherited.png'), fullPage: true })
})


test('通常予約締切を共通から0分に上書きし、継承へ戻せる', async ({ page }) => {
 await page.goto('/e2e/fixtures/settings-structure.html?mode=booking-cutoff')
 await expect(page.getByText('適用する締切：公演開始の30分前まで（組織共通）')).toBeVisible()
 await page.getByRole('combobox').click()
 await page.getByRole('option',{name:'このシナリオで指定',exact:true}).click()
 await page.getByRole('spinbutton').fill('0')
 await page.getByRole('button',{name:'通常予約の受付締切を保存',exact:true}).click()
 await expect(page.getByText('適用する締切：公演開始の0分前まで（このシナリオの個別指定）')).toBeVisible()
 await page.getByRole('combobox').click()
 await page.getByRole('option',{name:'共通設定を使う',exact:true}).click()
 await page.getByRole('button',{name:'通常予約の受付締切を保存',exact:true}).click()
 await expect(page.getByText('適用する締切：公演開始の30分前まで（組織共通）')).toBeVisible()
 expect(await page.evaluate(()=>JSON.parse(document.documentElement.dataset.cutoffSaved||'{}').minutes)).toBeNull()
})

test('追加募集の期限だけ上書きし、延長は共通設定を維持する',async ({page},info)=>{
 await page.goto('/e2e/fixtures/settings-structure.html?mode=recruitment')
 await expect(page.getByText('適用する期限：開始60分前まで（組織共通）')).toBeVisible()
 await page.locator('#recruitment-deadline-source').click()
 await page.getByRole('option',{name:'このシナリオだけ指定',exact:true}).click()
 await page.locator('#recruitment-minutes').fill('30')
 await page.getByRole('button',{name:'追加募集設定を保存',exact:true}).click()
 await expect(page.getByText('適用する期限：開始30分前まで（このシナリオの個別指定）')).toBeVisible()
 expect(await page.evaluate(()=>JSON.parse(document.documentElement.dataset.recruitmentSaved||'{}'))).toMatchObject({enabled_source:'common',deadline_source:'custom',deadline_minutes:30})
 await page.locator('#recruitment-deadline-source').click()
 await page.getByRole('option',{name:'共通設定を使う（開始60分前まで）',exact:true}).click()
 await page.getByRole('button',{name:'追加募集設定を保存',exact:true}).click()
 await expect(page.getByText('適用する期限：開始60分前まで（組織共通）')).toBeVisible()
 await page.screenshot({path:info.outputPath('recruitment-inheritance.png'),fullPage:true})
})

test('共通の追加募集設定で有効・期限・対象をまとめて保存する',async ({page},info)=>{
 await page.goto('/e2e/fixtures/settings-structure.html?mode=common-recruitment')
 await page.locator('#common-recruitment-deadline').fill('120')
 await page.locator('#common-recruitment-enabled').click()
 await page.getByRole('option',{name:'延長しない',exact:true}).click()
 await page.getByRole('button',{name:'保存',exact:true}).click()
 await expect(page.getByText('共通設定を保存しました。案内済みの追加募集期限は維持します。')).toBeVisible()
 expect(await page.evaluate(()=>JSON.parse(document.documentElement.dataset.commonSaved||'{}'))).toMatchObject({enabled:false,deadline_minutes:120,mode:'count',value:2})
 await page.screenshot({path:info.outputPath('common-recruitment.png'),fullPage:true})
})
