import { test, expect } from '@playwright/test'

test('設定一覧を4区分で表示し、管理者だけにMMQ全体を案内する', async ({ page }, info) => {
  await page.goto('/e2e/fixtures/settings-structure.html')
  for (const label of ['組織共通', '店舗別', '作品別', '公演別']) await expect(page.getByRole('heading', { name: label, exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'MMQ全体の管理' })).toHaveCount(0)
  await expect(page.getByRole('link', { name: '予約の受付', exact: true })).toHaveAttribute('href', '/test-org/settings?tab=reservation')
  await page.screenshot({ path: info.outputPath('settings-desktop.png'), fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: info.outputPath('settings-mobile.png'), fullPage: true })
  await page.goto('/e2e/fixtures/settings-structure.html?platform')
  await expect(page.getByRole('heading', { name: 'MMQ全体の管理' })).toBeVisible()
})

test('店舗Bから開くとBの値を読みBだけに保存し、店舗切替後はAの値になる', async ({ page }) => {
  await page.goto('/e2e/fixtures/settings-structure.html?mode=reservation')
  await expect(page.getByRole('spinbutton').first()).toHaveValue('77')
  await page.getByRole('spinbutton').first().fill('88')
  await page.getByRole('button', { name: '保存', exact: true }).click()
  const writes = await page.evaluate(() => JSON.parse(document.documentElement.dataset.writes || '[]'))
  expect(writes).toHaveLength(1)
  expect(writes[0]).toMatchObject({ table: 'reservation_settings', filters: { id: 'setting-b' }, payload: { advance_booking_days: 88 } })
  await page.getByRole('combobox').first().click()
  await page.getByRole('option', { name: '店舗A', exact: true }).click()
  await expect(page.getByRole('spinbutton').first()).toHaveValue('33')
})

test('組織通知と店舗通知を別々に保存し、隠れた範囲を上書きしない', async ({ page }) => {
  await page.goto('/e2e/fixtures/settings-structure.html?mode=org-notifications')
  await expect(page.getByText('組織全体の通知設定', { exact: true })).toBeVisible()
  await expect(page.getByText('予約関連通知', { exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: '保存', exact: true }).click()
  let writes = await page.evaluate(() => JSON.parse(document.documentElement.dataset.writes || '[]'))
  expect(writes.map((w: { table: string }) => w.table)).toEqual(['global_settings'])
  await page.goto('/e2e/fixtures/settings-structure.html?mode=store-notifications')
  await expect(page.getByText('予約関連通知', { exact: true })).toBeVisible()
  await expect(page.getByText('組織全体の通知設定', { exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: '保存', exact: true }).click()
  writes = await page.evaluate(() => JSON.parse(document.documentElement.dataset.writes || '[]'))
  expect(writes).toHaveLength(1)
  expect(writes[0]).toMatchObject({ table: 'notification_settings', filters: { id: 'setting-b' } })
})

test('公演の組織共通時間帯は店舗の所要時間を保存しない', async ({ page }) => {
  await page.goto('/e2e/fixtures/settings-structure.html?mode=org-time')
  await expect(page.getByText('デフォルト公演時間', { exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: '保存', exact: true })).toHaveCount(1)
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect.poll(() => page.evaluate(() => !!document.documentElement.dataset.timeSaved)).toBe(true)
  expect(await page.evaluate(() => document.documentElement.dataset.writes)).toBeUndefined()
})

test('作品の設定元を示し、共通情報に戻す操作で上書きを解除する', async ({ page }, info) => {
  await page.goto('/e2e/fixtures/settings-structure.html?mode=scenario')
  await page.getByText('共通情報と自社設定', { exact: true }).click()
  const row = page.getByRole('row').filter({ has: page.getByRole('rowheader', { name: 'タイトル', exact: true }) })
  await expect(row).toContainText('自社設定')
  await row.getByRole('button', { name: '共通情報に戻す' }).click()
  await expect(row).toContainText('未保存')
  await page.getByRole('button', { name: '作品設定を保存' }).click()
  const saved = await page.evaluate(() => JSON.parse(document.documentElement.dataset.sourceSaved || '{}'))
  expect(saved.override_title).toBeNull()
  expect(saved.override_author).toBeNull()
  await page.screenshot({ path: info.outputPath('scenario-sources.png'), fullPage: true })
})
