/**
 * 管理画面・公開ページの各画面（コード分割。読み込みに失敗したら再試行する）。AdminDashboard.tsx から移したもの。
 */
import { lazyWithRetry } from '@/utils/lazyWithRetry'

export const StoreManagement = lazyWithRetry(() => import('./StoreManagement').then(m => ({ default: m.StoreManagement })))
export const ScenarioManagement = lazyWithRetry(() => import('./ScenarioManagement').then(m => ({ default: m.ScenarioManagement })))
export const StaffManagement = lazyWithRetry(() => import('./StaffManagement').then(m => ({ default: m.StaffManagement })))
export const ScheduleManager = lazyWithRetry(() => import('./ScheduleManager/index').then(m => ({ default: m.ScheduleManager })))
export const SalesManagement = lazyWithRetry(() => import('./SalesManagement'))
export const ShiftSubmission = lazyWithRetry(() => import('./ShiftSubmission/index').then(m => ({ default: m.ShiftSubmission })))
export const ReservationManagement = lazyWithRetry(() => import('./ReservationManagement').then(m => ({ default: m.ReservationManagement })))
export const PublicBookingTop = lazyWithRetry(() => import('./PublicBookingTop').then(m => ({ default: m.PublicBookingTop })))
export const ScenarioDetailPage = lazyWithRetry(() => import('./ScenarioDetailPage').then(m => ({ default: m.ScenarioDetailPage })))
export const ScenarioDetailGlobal = lazyWithRetry(() => import('./ScenarioDetailGlobal').then(m => ({ default: m.ScenarioDetailGlobal })))
export const ScenarioCatalog = lazyWithRetry(() => import('./ScenarioCatalog').then(m => ({ default: m.ScenarioCatalog })))
export const GMAvailabilityCheck = lazyWithRetry(() => import('./GMAvailabilityCheck').then(m => ({ default: m.GMAvailabilityCheck })))
export const PrivateBookingScenarioSelect = lazyWithRetry(() => import('./PrivateBookingScenarioSelect').then(m => ({ default: m.PrivateBookingScenarioSelect })))
export const PrivateBookingRequestPage = lazyWithRetry(() => import('./PrivateBookingRequestPage').then(m => ({ default: m.PrivateBookingRequestPage })))
export const PrivateBookingManagement = lazyWithRetry(() => import('./PrivateBookingManagement').then(m => ({ default: m.PrivateBookingManagement })))
export const PrivateGroupListPage = lazyWithRetry(() => import('./PrivateBookingManagement/PrivateGroupListPage'))
export const AccountManagement = lazyWithRetry(() => import('./AccountManagement').then(m => ({ default: m.AccountManagement })))
export const CustomerManagement = lazyWithRetry(() => import('./CustomerManagement'))
export const UserManagement = lazyWithRetry(() => import('./UserManagement').then(m => ({ default: m.UserManagement })))
export const MyPage = lazyWithRetry(() => import('./MyPage'))
export const ReservationDetailPage = lazyWithRetry(() => import('./MyPage/pages/ReservationDetailPage').then(m => ({ default: m.ReservationDetailPage })))
export const SettingsPage = lazyWithRetry(() => import('./Settings'))
export const AddDemoParticipants = lazyWithRetry(() => import('./AddDemoParticipants').then(m => ({ default: m.AddDemoParticipants })))
export const ScenarioMatcher = lazyWithRetry(() => import('./ScenarioMatcher').then(m => ({ default: m.ScenarioMatcher })))
export const ManualPage = lazyWithRetry(() => import('./Manual/index').then(m => ({ default: m.ManualPage })))
export const DashboardHome = lazyWithRetry(() => import('./DashboardHome').then(m => ({ default: m.DashboardHome })))
export const StoreDashboard = lazyWithRetry(() => import('./StoreDashboard').then(m => ({ default: m.StoreDashboard })))
export const StaffProfile = lazyWithRetry(() => import('./StaffProfile').then(m => ({ default: m.StaffProfile })))
export const OrganizationManagement = lazyWithRetry(() => import('./OrganizationManagement'))
export const ExternalReports = lazyWithRetry(() => import('./ExternalReports'))
export const LicenseReportManagement = lazyWithRetry(() => import('./LicenseReportManagement'))
export const LicenseManagement = lazyWithRetry(() => import('./LicenseManagement'))
export const AcceptInvitation = lazyWithRetry(() => import('./AcceptInvitation'))
export const ScenarioMasterAdmin = lazyWithRetry(() => import('./ScenarioMasterAdmin').then(m => ({ default: m.ScenarioMasterAdmin })))
export const ScenarioMasterEdit = lazyWithRetry(() => import('./ScenarioMasterAdmin/ScenarioMasterEdit').then(m => ({ default: m.ScenarioMasterEdit })))
export const OrganizationSettings = lazyWithRetry(() => import('./OrganizationSettings'))
export const OrganizationRegister = lazyWithRetry(() => import('./OrganizationRegister'))
export const OrgSignup = lazyWithRetry(() => import('./OrgSignup'))
export const LandingPage = lazyWithRetry(() => import('./LandingPage'))
export const ForBusinessPage = lazyWithRetry(() => import('./ForBusiness').then(m => ({ default: m.ForBusinessPage })))
export const AuthorDashboard = lazyWithRetry(() => import('./AuthorDashboard'))
export const AuthorLogin = lazyWithRetry(() => import('./AuthorLogin'))
export const ExternalReportForm = lazyWithRetry(() => import('./ExternalReportForm'))
export const RentalReportForm = lazyWithRetry(() => import('./RentalReportForm').then(m => ({ default: m.RentalReportForm })))
export const LicensePartnerReportForm = lazyWithRetry(() => import('./LicensePartnerReportForm'))
export const PlatformScenarioSearch = lazyWithRetry(() => import('./PlatformScenarioSearch').then(m => ({ default: m.PlatformScenarioSearch })))
export const PlatformTop = lazyWithRetry(() => import('./PlatformTop').then(m => ({ default: m.PlatformTop })))
export const DesignPreview = lazyWithRetry(() => import('./dev/DesignPreview').then(m => ({ default: m.DesignPreview })))
export const ComponentGallery = lazyWithRetry(() => import('./dev/ComponentGallery').then(m => ({ default: m.ComponentGallery })))
export const ProjectGuide = lazyWithRetry(() => import('./dev/ProjectGuide').then(m => ({ default: m.ProjectGuide })))
export const LearnFromThisSystem = lazyWithRetry(() => import('./dev/LearnFromThisSystem').then(m => ({ default: m.LearnFromThisSystem })))
export const NotFoundPage = lazyWithRetry(() => import('./NotFoundPage').then(m => ({ default: m.NotFoundPage })))
export const PrivateGroupCreate = lazyWithRetry(() => import('./PrivateGroupCreate').then(m => ({ default: m.PrivateGroupCreate })))
export const PrivateGroupInvite = lazyWithRetry(() => import('./PrivateGroupInvite').then(m => ({ default: m.PrivateGroupInvite })))
export const PrivateGroupManage = lazyWithRetry(() => import('./PrivateGroupManage').then(m => ({ default: m.PrivateGroupManage })))
export const CouponManagement = lazyWithRetry(() => import('./CouponManagement').then(m => ({ default: m.CouponManagement })))
export const BlogDetailPage = lazyWithRetry(() => import('./BlogDetailPage').then(m => ({ default: m.BlogDetailPage })))
export const BlogManagement = lazyWithRetry(() => import('./BlogManagement').then(m => ({ default: m.BlogManagement })))
export const TermsPage = lazyWithRetry(() => import('./static').then(m => ({ default: m.TermsPage })))
export const PrivacyPage = lazyWithRetry(() => import('./static').then(m => ({ default: m.PrivacyPage })))
export const SecurityPage = lazyWithRetry(() => import('./static').then(m => ({ default: m.SecurityPage })))
export const LegalPage = lazyWithRetry(() => import('./static').then(m => ({ default: m.LegalPage })))
export const ContactPage = lazyWithRetry(() => import('./static').then(m => ({ default: m.ContactPage })))
export const OrganizationContactPage = lazyWithRetry(() => import('./org/ContactPage').then(m => ({ default: m.OrganizationContactPage })))
export const FAQPage = lazyWithRetry(() => import('./static').then(m => ({ default: m.FAQPage })))
export const GuidePage = lazyWithRetry(() => import('./static').then(m => ({ default: m.GuidePage })))
export const CancelPolicyPage = lazyWithRetry(() => import('./static').then(m => ({ default: m.CancelPolicyPage })))
export const StoreListPage = lazyWithRetry(() => import('./static').then(m => ({ default: m.StoreListPage })))
export const AboutPage = lazyWithRetry(() => import('./static').then(m => ({ default: m.AboutPage })))
export const PricingPage = lazyWithRetry(() => import('./static').then(m => ({ default: m.PricingPage })))
export const GettingStartedPage = lazyWithRetry(() => import('./static').then(m => ({ default: m.GettingStartedPage })))
