-- =====================================================
-- GMアサインメント + 体験済みスタッフ 完全復元スクリプト
-- =====================================================
-- インポートファイルから抽出: 総レコード 2179件
--   GM可能: 602件
--   体験済みのみ: 1577件
-- 
-- このスクリプトは以下を行います:
-- 1. staff_scenario_assignments にインポートファイルのデータを復元
--    ※ 既存レコードがあれば上書き（インポートデータが正しい元データ）
-- 2. organization_scenarios の available_gms, experienced_staff を再構築
-- =====================================================

-- ===========================================
-- STEP 0: 復元前の診断
-- ===========================================
SELECT 'Before: Total assignments: ' || COUNT(*) as total FROM staff_scenario_assignments;
SELECT 'Before: GM-capable: ' || COUNT(*) as gm_count FROM staff_scenario_assignments WHERE can_main_gm = true OR can_sub_gm = true;
SELECT 'Before: Experienced-only: ' || COUNT(*) as exp_count FROM staff_scenario_assignments WHERE is_experienced = true;
SELECT 'Before: org available_gms set: ' || COUNT(*) as org_gm FROM organization_scenarios WHERE available_gms IS NOT NULL AND available_gms != '{}' AND array_length(available_gms, 1) > 0;
SELECT 'Before: org experienced_staff set: ' || COUNT(*) as org_exp FROM organization_scenarios WHERE experienced_staff IS NOT NULL AND experienced_staff != '{}' AND array_length(experienced_staff, 1) > 0;

-- ===========================================
-- STEP 1-1: GM復元 (1~150/602)
-- ===========================================
INSERT INTO staff_scenario_assignments (staff_id, scenario_id, can_main_gm, can_sub_gm, is_experienced, can_gm_at)
SELECT s.id, sc.id, gp.main_gm, gp.sub_gm, false, NOW()
FROM (VALUES
    ('きゅう', '5DIVE', true, false),
    ('しらやま', '5DIVE', true, false),
    ('ぴよな', '5DIVE', true, false),
    ('八継じの', '5DIVE', true, false),
    ('つばめ', 'BBA', true, false),
    ('みずき', 'BBA', true, false),
    ('りえぞー', 'BBA', true, false),
    ('きゅう', 'BeatSpecter', true, false),
    ('Remia（れみあ）', 'BrightChoice', true, false),
    ('きゅう', 'BrightChoice', true, false),
    ('江波（えなみん）', 'BrightChoice', true, false),
    ('Remia（れみあ）', 'DearmyD', true, false),
    ('つばめ', 'DearmyD', true, false),
    ('れいにー', 'DearmyD', true, false),
    ('崎', 'DearmyD', true, false),
    ('江波（えなみん）', 'DearmyD', true, false),
    ('Remia（れみあ）', 'ENIGMACODE廃棄ミライの犠牲者たち', true, false),
    ('ほがらか', 'ENIGMACODE廃棄ミライの犠牲者たち', true, false),
    ('八継じの', 'ENIGMACODE廃棄ミライの犠牲者たち', true, false),
    ('りえぞー', 'GARDENリーガー殺人事件', true, false),
    ('あんころ', 'GM殺人事件', true, false),
    ('だいこん', 'GM殺人事件', true, false),
    ('りんな', 'GM殺人事件', true, false),
    ('ソウタン', 'GM殺人事件', true, false),
    ('八継じの', 'GM殺人事件', true, false),
    ('あんころ', 'Invisible-亡霊列車-', true, false),
    ('きゅう', 'Invisible-亡霊列車-', true, false),
    ('つばめ', 'Invisible-亡霊列車-', true, false),
    ('りえぞー', 'Invisible-亡霊列車-', true, false),
    ('ソラ', 'Invisible-亡霊列車-', true, false),
    ('ミカノハ', 'Invisible-亡霊列車-', true, false),
    ('八継じの', 'Invisible-亡霊列車-', true, false),
    ('古賀', 'Invisible-亡霊列車-', true, false),
    ('江波（えなみん）', 'Invisible-亡霊列車-', true, false),
    ('Remia（れみあ）', 'Iwillex-', true, false),
    ('ぽん', 'Iwillex-', true, false),
    ('れいにー', 'Iwillex-', true, false),
    ('崎', 'Iwillex-', true, false),
    ('江波（えなみん）', 'Iwillex-', true, false),
    ('ぽん', 'Jazzy', true, false),
    ('しらやま', 'MERCHANT', true, false),
    ('ミカノハ', 'MERCHANT', true, false),
    ('江波（えなみん）', 'MissingLink（ミッシングリンク）', true, false),
    ('ソラ', 'REDRUM01泉涌館の変転', true, false),
    ('ソラ', 'REDRUM02虚像のF', true, false),
    ('labo', 'REDRUM03致命的観測をもう一度', true, false),
    ('えりん', 'REDRUM03致命的観測をもう一度', true, false),
    ('しらやま', 'REDRUM03致命的観測をもう一度', true, false),
    ('ソラ', 'REDRUM03致命的観測をもう一度', true, false),
    ('ソラ', 'REDRUM4アルテミスの断罪', true, false),
    ('しらやま', 'Recollection', true, false),
    ('みずき', 'Recollection', true, false),
    ('ソラ', 'Recollection', true, false),
    ('きゅう', 'SORCIER～賢者達の物語～', true, false),
    ('つばめ', 'SORCIER～賢者達の物語～', true, false),
    ('みずき', 'SORCIER～賢者達の物語～', true, false),
    ('Remia（れみあ）', 'TOOLS〜ぎこちない椅子', true, false),
    ('きゅう', 'TOOLS〜ぎこちない椅子', true, false),
    ('れいにー', 'TOOLS〜ぎこちない椅子', true, false),
    ('ソラ', 'TOOLS〜ぎこちない椅子', true, false),
    ('りえぞー', 'TheRealFork30', true, false),
    ('ソラ', 'TheRealFork30', true, false),
    ('松井（まつい）', 'WANTEDz', true, false),
    ('江波（えなみん）', 'WANTEDz', true, false),
    ('あんころ', 'WORLDEND', true, false),
    ('つばめ', 'WORLDEND', true, false),
    ('ぽん', 'WORLDEND', true, false),
    ('りえぞー', 'WORLDEND', true, false),
    ('ミカノハ', 'WORLDEND', true, false),
    ('れいにー', 'inthebox〜長い熱病', true, false),
    ('八継じの', 'inthebox〜長い熱病', true, false),
    ('崎', 'inthebox〜長い熱病', true, false),
    ('ほがらか', 'readme.txt', true, false),
    ('ぽん', 'あくなき世界で嘘をうたう', true, false),
    ('みずき', 'あくなき世界で嘘をうたう', true, false),
    ('りんな', 'あくなき世界で嘘をうたう', true, false),
    ('江波（えなみん）', 'あくなき世界で嘘をうたう', true, false),
    ('ぽん', 'あの夏のアンタレス', true, false),
    ('れいにー', 'あの夏のアンタレス', true, false),
    ('Remia（れみあ）', 'あるマーダーミステリーについて', true, false),
    ('labo', 'あるマーダーミステリーについて', true, false),
    ('えりん', 'あるマーダーミステリーについて', true, false),
    ('しらやま', 'あるマーダーミステリーについて', true, false),
    ('りえぞー', 'あるマーダーミステリーについて', true, false),
    ('れいにー', 'あるマーダーミステリーについて', true, false),
    ('松井（まつい）', 'あるマーダーミステリーについて', true, false),
    ('江波（えなみん）', 'あるマーダーミステリーについて', true, false),
    ('藤崎ソルト', 'あるマーダーミステリーについて', true, false),
    ('Remia（れみあ）', 'ある悪魔の儀式について', true, false),
    ('江波（えなみん）', 'ある悪魔の儀式について', true, false),
    ('つばめ', 'くずの葉のもり', true, false),
    ('りえぞー', 'くずの葉のもり', true, false),
    ('ソラ', 'くずの葉のもり', true, false),
    ('八継じの', 'くずの葉のもり', true, false),
    ('Remia（れみあ）', 'この闇をあなたと', true, false),
    ('きゅう', 'この闇をあなたと', true, false),
    ('しらやま', 'この闇をあなたと', true, false),
    ('ソラ', 'この闇をあなたと', true, false),
    ('八継じの', 'この闇をあなたと', true, false),
    ('松井（まつい）', 'この闇をあなたと', true, false),
    ('江波（えなみん）', 'この闇をあなたと', true, false),
    ('きゅう', 'その白衣は誰が為に', true, false),
    ('きゅう', 'つわものどもが夢のあと', true, false),
    ('みずき', 'つわものどもが夢のあと', true, false),
    ('れいにー', 'つわものどもが夢のあと', true, false),
    ('りえぞー', 'ひぐらしのなく頃に　恨返し編', true, false),
    ('きゅう', 'へっどぎあ★ぱにっく', true, false),
    ('しらやま', 'へっどぎあ★ぱにっく', true, false),
    ('つばめ', 'へっどぎあ★ぱにっく', true, false),
    ('江波（えなみん）', 'へっどぎあ★ぱにっく', true, false),
    ('りえぞー', 'アオハルーツ', true, false),
    ('江波（えなみん）', 'アオハルーツ', true, false),
    ('しらやま', 'アオハループ', true, false),
    ('つばめ', 'アオハループ', true, false),
    ('ぽん', 'アオハループ', true, false),
    ('みくみん', 'アオハループ', true, false),
    ('みずき', 'アオハループ', true, false),
    ('りえぞー', 'アオハループ', true, false),
    ('きゅう', 'アンシンメトリー', true, false),
    ('しらやま', 'アンドロイドは愛を知らない', true, false),
    ('つばめ', 'アンドロイドは愛を知らない', true, false),
    ('八継じの', 'アンドロイドは愛を知らない', true, false),
    ('ぽん', 'アンフィスバエナと聖女の祈り', true, false),
    ('りえぞー', 'アンフィスバエナと聖女の祈り', true, false),
    ('松井（まつい）', 'アンフィスバエナと聖女の祈り', true, false),
    ('きゅう', 'ウロボロスの眠り', true, false),
    ('松井（まつい）', 'ウロボロスの眠り', true, false),
    ('江波（えなみん）', 'ウロボロスの眠り', true, false),
    ('あんころ', 'エイダ', true, false),
    ('しらやま', 'エイダ', true, false),
    ('みずき', 'エイダ', true, false),
    ('りえぞー', 'エイダ', true, false),
    ('藤崎ソルト', 'エイダ', true, false),
    ('きゅう', 'エデンの審判', true, false),
    ('崎', 'エデンの審判', true, false),
    ('あんころ', 'エンドロールは流れない', true, false),
    ('ぽん', 'エンドロールは流れない', true, false),
    ('みずき', 'エンドロールは流れない', true, false),
    ('ソラ', 'エンドロールは流れない', true, false),
    ('藤崎ソルト', 'エンドロールは流れない', true, false),
    ('ソラ', 'オペレーション：ゴーストウィング', true, false),
    ('江波（えなみん）', 'オペレーション：ゴーストウィング', true, false),
    ('ぽん', 'キヲクの方舟', true, false),
    ('きゅう', 'クリエイターズハイ', true, false),
    ('りえぞー', 'クリエイターズハイ', true, false),
    ('江波（えなみん）', 'クリエイターズハイ', true, false),
    ('ぽん', 'クリムゾンアート', true, false),
    ('りえぞー', 'クリムゾンアート', true, false),
    ('きゅう', 'クロノフォビア', true, false),
    ('つばめ', 'クロノフォビア', true, false)
) AS gp(staff_name, scenario_title, main_gm, sub_gm)
JOIN staff s ON s.name = gp.staff_name
JOIN scenarios sc ON sc.title = gp.scenario_title
ON CONFLICT (staff_id, scenario_id)
DO UPDATE SET
  can_main_gm = EXCLUDED.can_main_gm,
  can_sub_gm = EXCLUDED.can_sub_gm,
  is_experienced = false;

-- ===========================================
-- STEP 1-2: GM復元 (151~300/602)
-- ===========================================
INSERT INTO staff_scenario_assignments (staff_id, scenario_id, can_main_gm, can_sub_gm, is_experienced, can_gm_at)
SELECT s.id, sc.id, gp.main_gm, gp.sub_gm, false, NOW()
FROM (VALUES
    ('ほがらか', 'クロノフォビア', true, false),
    ('りえぞー', 'クロノフォビア', true, false),
    ('イワセモリシ', 'クロノフォビア', true, false),
    ('Remia（れみあ）', 'グロリアメモリーズ', true, false),
    ('きゅう', 'グロリアメモリーズ', true, false),
    ('しらやま', 'ゴージャスマンション', true, false),
    ('だいこん', 'ゴージャスマンション', true, false),
    ('しらやま', 'スターループ', true, false),
    ('ぴよな', 'スターループ', true, false),
    ('ぽん', 'スターループ', true, false),
    ('れいにー', 'スターループ', true, false),
    ('八継じの', 'スターループ', true, false),
    ('ソラ', 'ゼロの爆弾', true, false),
    ('八継じの', 'ゼロの爆弾', true, false),
    ('江波（えなみん）', 'ツイン号沈没事件に関する考察', true, false),
    ('えりん', 'ツグミドリ', true, false),
    ('きゅう', 'ツグミドリ', true, false),
    ('りえぞー', 'ツグミドリ', true, false),
    ('りんな', 'ツグミドリ', true, false),
    ('ソラ', 'ツグミドリ', true, false),
    ('松井（まつい）', 'ツグミドリ', true, false),
    ('江波（えなみん）', 'ツグミドリ', true, false),
    ('つばめ', 'テセウスの方舟', true, false),
    ('ほがらか', 'テセウスの方舟', true, false),
    ('八継じの', 'テセウスの方舟', true, false),
    ('藤崎ソルト', 'テセウスの方舟', true, false),
    ('つばめ', 'デモンズボックス', true, false),
    ('江波（えなみん）', 'デモンズボックス', true, false),
    ('きゅう', 'ドクター・テラスの秘密の実験', true, false),
    ('江波（えなみん）', 'ドクター・テラスの秘密の実験', true, false),
    ('Remia（れみあ）', 'ナナイロの迷宮 橙 オンラインゲーム殺人事件', true, false),
    ('えりん', 'ナナイロの迷宮 橙 オンラインゲーム殺人事件', true, false),
    ('きゅう', 'ナナイロの迷宮 橙 オンラインゲーム殺人事件', true, false),
    ('つばめ', 'ナナイロの迷宮 橙 オンラインゲーム殺人事件', true, false),
    ('ぽん', 'ナナイロの迷宮 橙 オンラインゲーム殺人事件', true, false),
    ('みずき', 'ナナイロの迷宮 橙 オンラインゲーム殺人事件', true, false),
    ('れいにー', 'ナナイロの迷宮 橙 オンラインゲーム殺人事件', true, false),
    ('Remia（れみあ）', 'ナナイロの迷宮 緑 アペイロン研究所殺人事件', true, false),
    ('きゅう', 'ナナイロの迷宮 緑 アペイロン研究所殺人事件', true, false),
    ('つばめ', 'ナナイロの迷宮 緑 アペイロン研究所殺人事件', true, false),
    ('りえぞー', 'ナナイロの迷宮 緑 アペイロン研究所殺人事件', true, false),
    ('Remia（れみあ）', 'ナナイロの迷宮 黄 エレクトリカル吹奏楽部殺人事件', true, false),
    ('きゅう', 'ナナイロの迷宮 黄 エレクトリカル吹奏楽部殺人事件', true, false),
    ('ぽん', 'ナナイロの迷宮 黄 エレクトリカル吹奏楽部殺人事件', true, false),
    ('みずき', 'ナナイロの迷宮 黄 エレクトリカル吹奏楽部殺人事件', true, false),
    ('れいにー', 'ナナイロの迷宮 黄 エレクトリカル吹奏楽部殺人事件', true, false),
    ('りえぞー', 'バベルの末裔', true, false),
    ('江波（えなみん）', 'バベルの末裔', true, false),
    ('江波（えなみん）', 'ヒーロースクランブル', true, false),
    ('Remia（れみあ）', 'ピタゴラスの篝火', true, false),
    ('きゅう', 'ピタゴラスの篝火', true, false),
    ('江波（えなみん）', 'ピタゴラスの篝火', true, false),
    ('えりん', 'フェイクドナー', true, false),
    ('しらやま', 'フェイクドナー', true, false),
    ('みずき', 'フェイクドナー', true, false),
    ('れいにー', 'フェイクドナー', true, false),
    ('江波（えなみん）', 'ブルーダイヤの不在証明', true, false),
    ('ソラ', 'マーダーオブエクスプローラー失われし大秘宝', true, false),
    ('江波（えなみん）', 'マーダー・オブ・パイレーツ', true, false),
    ('labo', 'モノクローム', true, false),
    ('えりん', 'モノクローム', true, false),
    ('きゅう', 'モノクローム', true, false),
    ('しらやま', 'モノクローム', true, false),
    ('みずき', 'モノクローム', true, false),
    ('りえぞー', 'モノクローム', true, false),
    ('イワセモリシ', 'モノクローム', true, false),
    ('八継じの', 'モノクローム', true, false),
    ('崎', 'モノクローム', true, false),
    ('りえぞー', 'ヤノハのフタリ', true, false),
    ('江波（えなみん）', 'ヤノハのフタリ', true, false),
    ('あんころ', 'ユートピアース', true, false),
    ('しらやま', 'ユートピアース', true, false),
    ('つばめ', 'ユートピアース', true, false),
    ('八継じの', 'ユートピアース', true, false),
    ('えりん', 'リアルマダミス-MurderWonderLand', true, false),
    ('つばめ', 'リアルマダミス-MurderWonderLand', true, false),
    ('みずき', 'リアルマダミス-MurderWonderLand', true, false),
    ('れいにー', 'リアルマダミス-MurderWonderLand', true, false),
    ('みずき', 'リアルマダミス-盤上の教皇', true, false),
    ('れいにー', 'リアルマダミス-盤上の教皇', true, false),
    ('つばめ', 'リトルワンダー', true, false),
    ('みずき', 'リトルワンダー', true, false),
    ('Remia（れみあ）', 'ロスト／リメンブランス', true, false),
    ('labo', 'ロスト／リメンブランス', true, false),
    ('きゅう', 'ロスト／リメンブランス', true, false),
    ('れいにー', 'ロスト／リメンブランス', true, false),
    ('みくみん', 'ロックドドア殺人', true, false),
    ('きゅう', '一条家の人々', true, false),
    ('江波（えなみん）', '一条家の人々', true, false),
    ('みくみん', '七股高校', true, false),
    ('えりん', '不思議の国の童話裁判', true, false),
    ('きゅう', '不思議の国の童話裁判', true, false),
    ('つばめ', '不思議の国の童話裁判', true, false),
    ('みずき', '不思議の国の童話裁判', true, false),
    ('りえぞー', '不思議の国の童話裁判', true, false),
    ('八継じの', '不思議の国の童話裁判', true, false),
    ('きゅう', '人狼を語る館', true, false),
    ('松井（まつい）', '人狼を語る館', true, false),
    ('あんころ', '人類最後の皆様へ／終末の眠り姫', true, false),
    ('ほがらか', '今日も涙の雨が降る', true, false),
    ('えりん', '傲慢な女王とアリスの不条理裁判', true, false),
    ('しらやま', '傲慢な女王とアリスの不条理裁判', true, false),
    ('ぽん', '傲慢な女王とアリスの不条理裁判', true, false),
    ('みずき', '傲慢な女王とアリスの不条理裁判', true, false),
    ('りえぞー', '傲慢な女王とアリスの不条理裁判', true, false),
    ('りんな', '傲慢な女王とアリスの不条理裁判', true, false),
    ('れいにー', '傲慢な女王とアリスの不条理裁判', true, false),
    ('松井（まつい）', '僕らの未来について', true, false),
    ('ほがらか', '全能のパラドックス', true, false),
    ('ぽったー', '全能のパラドックス', true, false),
    ('イワセモリシ', '全能のパラドックス', true, false),
    ('江波（えなみん）', '全能のパラドックス', true, false),
    ('あんころ', '凍てつくあなたに６つの灯火', true, false),
    ('えりん', '凍てつくあなたに６つの灯火', true, false),
    ('りえぞー', '凍てつくあなたに６つの灯火', true, false),
    ('松井（まつい）', '凍てつくあなたに６つの灯火', true, false),
    ('Remia（れみあ）', '午前2時7分', true, false),
    ('きゅう', '午前2時7分', true, false),
    ('江波（えなみん）', '午前2時7分', true, false),
    ('れいにー', '南極地点X', true, false),
    ('松井（まつい）', '南極地点X', true, false),
    ('きゅう', '古鐘のなる頃に', true, false),
    ('松井（まつい）', '古鐘のなる頃に', true, false),
    ('江波（えなみん）', '古鐘のなる頃に', true, false),
    ('松井（まつい）', '名探偵と四嶺館', true, false),
    ('しらやま', '告別詩（取引中止）', true, false),
    ('ぴよな', '告別詩（取引中止）', true, false),
    ('りえぞー', '告別詩（取引中止）', true, false),
    ('きゅう', '土牢に悲鳴は谺して', true, false),
    ('松井（まつい）', '土牢に悲鳴は谺して', true, false),
    ('しらやま', '境界線のカーサスベリ', true, false),
    ('つばめ', '境界線のカーサスベリ', true, false),
    ('ソラ', '境界線のカーサスベリ', true, false),
    ('崎', '境界線のカーサスベリ', true, false),
    ('藤崎ソルト', '境界線のカーサスベリ', true, false),
    ('あんころ', '天使は花明かりの下で', true, false),
    ('しらやま', '天使は花明かりの下で', true, false),
    ('ぴよな', '天使は花明かりの下で', true, false),
    ('ぽん', '天使は花明かりの下で', true, false),
    ('みずき', '天使は花明かりの下で', true, false),
    ('りえぞー', '天使は花明かりの下で', true, false),
    ('しらやま', '天邪河（あまのじゃく）', true, false),
    ('みずき', '天邪河（あまのじゃく）', true, false),
    ('松井（まつい）', '天邪河（あまのじゃく）', true, false),
    ('きゅう', '奪うもの、奪われるもの', true, false),
    ('れいにー', '奪うもの、奪われるもの', true, false),
    ('えりん', '女皇の書架', true, false),
    ('きゅう', '女皇の書架', true, false),
    ('りえぞー', '女皇の書架', true, false),
    ('八継じの', '女皇の書架', true, false)
) AS gp(staff_name, scenario_title, main_gm, sub_gm)
JOIN staff s ON s.name = gp.staff_name
JOIN scenarios sc ON sc.title = gp.scenario_title
ON CONFLICT (staff_id, scenario_id)
DO UPDATE SET
  can_main_gm = EXCLUDED.can_main_gm,
  can_sub_gm = EXCLUDED.can_sub_gm,
  is_experienced = false;

-- ===========================================
-- STEP 1-3: GM復元 (301~450/602)
-- ===========================================
INSERT INTO staff_scenario_assignments (staff_id, scenario_id, can_main_gm, can_sub_gm, is_experienced, can_gm_at)
SELECT s.id, sc.id, gp.main_gm, gp.sub_gm, false, NOW()
FROM (VALUES
    ('八継じの', '妖怪たちと月夜の刀', true, false),
    ('崎', '妖怪たちと月夜の刀', true, false),
    ('Remia（れみあ）', '季節マーダー／アニクシィ', true, false),
    ('えりん', '季節マーダー／アニクシィ', true, false),
    ('きゅう', '季節マーダー／アニクシィ', true, false),
    ('つばめ', '季節マーダー／アニクシィ', true, false),
    ('ぽん', '季節マーダー／アニクシィ', true, false),
    ('みずき', '季節マーダー／アニクシィ', true, false),
    ('りえぞー', '季節マーダー／アニクシィ', true, false),
    ('りんな', '季節マーダー／アニクシィ', true, false),
    ('れいにー', '季節マーダー／アニクシィ', true, false),
    ('崎', '季節マーダー／アニクシィ', true, false),
    ('江波（えなみん）', '季節マーダー／アニクシィ', true, false),
    ('Remia（れみあ）', '季節マーダー／カノケリ', true, false),
    ('えりん', '季節マーダー／カノケリ', true, false),
    ('きゅう', '季節マーダー／カノケリ', true, false),
    ('つばめ', '季節マーダー／カノケリ', true, false),
    ('ぴよな', '季節マーダー／カノケリ', true, false),
    ('ぽん', '季節マーダー／カノケリ', true, false),
    ('みずき', '季節マーダー／カノケリ', true, false),
    ('りえぞー', '季節マーダー／カノケリ', true, false),
    ('りんな', '季節マーダー／カノケリ', true, false),
    ('れいにー', '季節マーダー／カノケリ', true, false),
    ('崎', '季節マーダー／カノケリ', true, false),
    ('江波（えなみん）', '季節マーダー／カノケリ', true, false),
    ('Remia（れみあ）', '季節マーダー／キモナス', true, false),
    ('えりん', '季節マーダー／キモナス', true, false),
    ('きゅう', '季節マーダー／キモナス', true, false),
    ('ぽん', '季節マーダー／キモナス', true, false),
    ('みずき', '季節マーダー／キモナス', true, false),
    ('りえぞー', '季節マーダー／キモナス', true, false),
    ('りんな', '季節マーダー／キモナス', true, false),
    ('れいにー', '季節マーダー／キモナス', true, false),
    ('崎', '季節マーダー／キモナス', true, false),
    ('江波（えなみん）', '季節マーダー／キモナス', true, false),
    ('Remia（れみあ）', '季節マーダー／シノポロ', true, false),
    ('えりん', '季節マーダー／シノポロ', true, false),
    ('きゅう', '季節マーダー／シノポロ', true, false),
    ('しらやま', '季節マーダー／シノポロ', true, false),
    ('ぴよな', '季節マーダー／シノポロ', true, false),
    ('ぽん', '季節マーダー／シノポロ', true, false),
    ('みずき', '季節マーダー／シノポロ', true, false),
    ('りえぞー', '季節マーダー／シノポロ', true, false),
    ('りんな', '季節マーダー／シノポロ', true, false),
    ('れいにー', '季節マーダー／シノポロ', true, false),
    ('崎', '季節マーダー／シノポロ', true, false),
    ('江波（えなみん）', '季節マーダー／シノポロ', true, false),
    ('えりん', '学校の解談', true, false),
    ('みずき', '学校の解談', true, false),
    ('りえぞー', '学校の解談', true, false),
    ('江波（えなみん）', '学校の解談', true, false),
    ('Remia（れみあ）', '小暮事件に関する考察', true, false),
    ('labo', '小暮事件に関する考察', true, false),
    ('ソラ', '小暮事件に関する考察', true, false),
    ('松井（まつい）', '小暮事件に関する考察', true, false),
    ('江波（えなみん）', '小暮事件に関する考察', true, false),
    ('りえぞー', '少年少女Aの独白', true, false),
    ('江波（えなみん）', '少年少女Aの独白', true, false),
    ('Remia（れみあ）', '岐路に降り立つ', true, false),
    ('きゅう', '岐路に降り立つ', true, false),
    ('松井（まつい）', '岐路に降り立つ', true, false),
    ('江波（えなみん）', '岐路に降り立つ', true, false),
    ('きゅう', '幻想のマリス', true, false),
    ('みずき', '幻想のマリス', true, false),
    ('れいにー', '幻想のマリス', true, false),
    ('江波（えなみん）', '幻想のマリス', true, false),
    ('ソラ', '廻る弾丸輪舞（ダンガンロンド）', true, false),
    ('松井（まつい）', '廻る弾丸輪舞（ダンガンロンド）', true, false),
    ('あんころ', '彗星蘭の万朶', true, false),
    ('しらやま', '彗星蘭の万朶', true, false),
    ('りんな', '彗星蘭の万朶', true, false),
    ('八継じの', '彗星蘭の万朶', true, false),
    ('つばめ', '彼とかじつとマシュマロウ', true, false),
    ('ぽん', '彼とかじつとマシュマロウ', true, false),
    ('りえぞー', '彼とかじつとマシュマロウ', true, false),
    ('藤崎ソルト', '彼とかじつとマシュマロウ', true, false),
    ('えりん', '彼女といるかとチョコレート', true, false),
    ('ぽん', '彼女といるかとチョコレート', true, false),
    ('りえぞー', '彼女といるかとチョコレート', true, false),
    ('藤崎ソルト', '彼女といるかとチョコレート', true, false),
    ('松井（まつい）', '悪意の岐路に立つ', true, false),
    ('江波（えなみん）', '悪意の岐路に立つ', true, false),
    ('みずき', '愛する故に', true, false),
    ('れいにー', '愛する故に', true, false),
    ('イワセモリシ', '愛する故に', true, false),
    ('ソラ', '愛する故に', true, false),
    ('あんころ', '或ル胡蝶ノ夢', true, false),
    ('えりん', '或ル胡蝶ノ夢', true, false),
    ('きゅう', '或ル胡蝶ノ夢', true, false),
    ('しらやま', '或ル胡蝶ノ夢', true, false),
    ('ぽん', '或ル胡蝶ノ夢', true, false),
    ('みずき', '或ル胡蝶ノ夢', true, false),
    ('りえぞー', '或ル胡蝶ノ夢', true, false),
    ('りんな', '或ル胡蝶ノ夢', true, false),
    ('崎', '或ル胡蝶ノ夢', true, false),
    ('松井（まつい）', '或ル胡蝶ノ夢', true, false),
    ('八継じの', '探ぱんマーダーミステリー・ノーショーツトルダム学園殺人事件', true, false),
    ('みずき', '探偵撲滅', true, false),
    ('八継じの', '探偵撲滅', true, false),
    ('しらやま', '新世界のユキサキ', true, false),
    ('ぴよな', '新世界のユキサキ', true, false),
    ('りえぞー', '新世界のユキサキ', true, false),
    ('りんな', '新世界のユキサキ', true, false),
    ('八継じの', '新世界のユキサキ', true, false),
    ('崎', '新世界のユキサキ', true, false),
    ('松井（まつい）', '新世界のユキサキ', true, false),
    ('江波（えなみん）', '新世界のユキサキ', true, false),
    ('藤崎ソルト', '新世界のユキサキ', true, false),
    ('りえぞー', '星', true, false),
    ('えりん', '星空のマリス', true, false),
    ('きゅう', '星空のマリス', true, false),
    ('ぽん', '星空のマリス', true, false),
    ('みずき', '星空のマリス', true, false),
    ('りえぞー', '星空のマリス', true, false),
    ('松井（まつい）', '星空のマリス', true, false),
    ('江波（えなみん）', '星空のマリス', true, false),
    ('えりん', '曙光のエテルナ', true, false),
    ('しらやま', '曙光のエテルナ', true, false),
    ('つばめ', '曙光のエテルナ', true, false),
    ('八継じの', '曙光のエテルナ', true, false),
    ('しらやま', '月光の偽桜', true, false),
    ('つばめ', '月光の偽桜', true, false),
    ('ぴよな', '月光の偽桜', true, false),
    ('ソラ', '月光の偽桜', true, false),
    ('崎', '月光の偽桜', true, false),
    ('藤崎ソルト', '月光の偽桜', true, false),
    ('きゅう', '朱き亡国に捧げる祈り', true, false),
    ('だいこん', '朱き亡国に捧げる祈り', true, false),
    ('れいにー', '朱き亡国に捧げる祈り', true, false),
    ('松井（まつい）', '朱き亡国に捧げる祈り', true, false),
    ('江波（えなみん）', '朱き亡国に捧げる祈り', true, false),
    ('ほがらか', '椅子戦争', true, false),
    ('りえぞー', '椅子戦争', true, false),
    ('きゅう', '機巧人形の心臓', true, false),
    ('しらやま', '機巧人形の心臓', true, false),
    ('つばめ', '機巧人形の心臓', true, false),
    ('ぴよな', '機巧人形の心臓', true, false),
    ('りえぞー', '機巧人形の心臓', true, false),
    ('八継じの', '機巧人形の心臓', true, false),
    ('藤崎ソルト', '機巧人形の心臓', true, false),
    ('つばめ', '檻見る5人-（空色時箱セット公演）', true, false),
    ('ソラ', '檻見る5人-（空色時箱セット公演）', true, false),
    ('松井（まつい）', '正義はまた蘇る', true, false),
    ('江波（えなみん）', '正義はまた蘇る', true, false),
    ('きゅう', '歯に噛むあなたに', true, false),
    ('Remia（れみあ）', '殺人鬼Xの独白', true, false),
    ('れいにー', '殺人鬼Xの独白', true, false),
    ('松井（まつい）', '殺人鬼Xの独白', true, false),
    ('きゅう', '殺人鬼イバラノミチの回想録', true, false),
    ('ぽん', '殺人鬼イバラノミチの回想録', true, false)
) AS gp(staff_name, scenario_title, main_gm, sub_gm)
JOIN staff s ON s.name = gp.staff_name
JOIN scenarios sc ON sc.title = gp.scenario_title
ON CONFLICT (staff_id, scenario_id)
DO UPDATE SET
  can_main_gm = EXCLUDED.can_main_gm,
  can_sub_gm = EXCLUDED.can_sub_gm,
  is_experienced = false;

-- ===========================================
-- STEP 1-4: GM復元 (451~600/602)
-- ===========================================
INSERT INTO staff_scenario_assignments (staff_id, scenario_id, can_main_gm, can_sub_gm, is_experienced, can_gm_at)
SELECT s.id, sc.id, gp.main_gm, gp.sub_gm, false, NOW()
FROM (VALUES
    ('りえぞー', '殺人鬼イバラノミチの回想録', true, false),
    ('れいにー', '殺人鬼イバラノミチの回想録', true, false),
    ('しらやま', '殺神罪', true, false),
    ('つばめ', '殺神罪', true, false),
    ('みずき', '殺神罪', true, false),
    ('松井（まつい）', '殺神罪', true, false),
    ('あんころ', '流年', true, false),
    ('えりん', '流年', true, false),
    ('れいにー', '流年', true, false),
    ('イワセモリシ', '流年', true, false),
    ('八継じの', '深海に沈む子供たち（水底に生きる）', true, false),
    ('松井（まつい）', '清流館の秘宝', true, false),
    ('つばめ', '漣の向こう側', true, false),
    ('ぴよな', '漣の向こう側', true, false),
    ('八継じの', '漣の向こう側', true, false),
    ('きゅう', '火ノ神様のいうとおり', true, false),
    ('江波（えなみん）', '火ノ神様のいうとおり', true, false),
    ('えりん', '燔祭のジェミニ', true, false),
    ('しらやま', '燔祭のジェミニ', true, false),
    ('つばめ', '燔祭のジェミニ', true, false),
    ('りえぞー', '燔祭のジェミニ', true, false),
    ('りんな', '燔祭のジェミニ', true, false),
    ('八継じの', '燔祭のジェミニ', true, false),
    ('江波（えなみん）', '燔祭のジェミニ', true, false),
    ('Remia（れみあ）', '狂気山脈　2.5　頂上戦争', true, false),
    ('れいにー', '狂気山脈　2.5　頂上戦争', true, false),
    ('Remia（れみあ）', '狂気山脈　星降る天辺（２）', true, false),
    ('れいにー', '狂気山脈　星降る天辺（２）', true, false),
    ('Remia（れみあ）', '狂気山脈　薄明三角点（３）', true, false),
    ('れいにー', '狂気山脈　薄明三角点（３）', true, false),
    ('Remia（れみあ）', '狂気山脈　陰謀の分水嶺（１）', true, false),
    ('れいにー', '狂気山脈　陰謀の分水嶺（１）', true, false),
    ('あんころ', '異能特区シンギュラリティ', true, false),
    ('えりん', '白殺しType-K', true, false),
    ('きゅう', '白殺しType-K', true, false),
    ('しらやま', '白殺しType-K', true, false),
    ('しらやま', '百鬼の夜、月光の影', true, false),
    ('みずき', '百鬼の夜、月光の影', true, false),
    ('りんな', '百鬼の夜、月光の影', true, false),
    ('ソラ', '真・渋谷陰陽奇譚', true, false),
    ('崎', '真・渋谷陰陽奇譚', true, false),
    ('つばめ', '空色時箱（ソライロタイムカプセル）-檻見る５人セット公演', true, false),
    ('ソラ', '空色時箱（ソライロタイムカプセル）-檻見る５人セット公演', true, false),
    ('labo', '立方館', true, false),
    ('ぽったー', '立方館', true, false),
    ('松井（まつい）', '立方館', true, false),
    ('きゅう', '紅く舞う', true, false),
    ('松井（まつい）', '紅く舞う', true, false),
    ('えりん', '紫に染まる前に', true, false),
    ('松井（まつい）', '紫に染まる前に', true, false),
    ('ぽん', '絆の永逝', true, false),
    ('みずき', '花咲の箱庭', true, false),
    ('えりん', '花街リグレット', true, false),
    ('きゅう', '花街リグレット', true, false),
    ('しらやま', '花街リグレット', true, false),
    ('みずき', '花街リグレット', true, false),
    ('りえぞー', '花街リグレット', true, false),
    ('八継じの', '花街リグレット', true, false),
    ('えりん', '荒廃のマリス', true, false),
    ('きゅう', '荒廃のマリス', true, false),
    ('ぽん', '荒廃のマリス', true, false),
    ('みずき', '荒廃のマリス', true, false),
    ('りえぞー', '荒廃のマリス', true, false),
    ('松井（まつい）', '荒廃のマリス', true, false),
    ('江波（えなみん）', '荒廃のマリス', true, false),
    ('つばめ', '藍雨廻逢', true, false),
    ('ぴよな', '藍雨廻逢', true, false),
    ('りんな', '藍雨廻逢', true, false),
    ('ソラ', '藍雨廻逢', true, false),
    ('八継じの', '藍雨廻逢', true, false),
    ('きゅう', '蝉散', true, false),
    ('ぴよな', '蝉散', true, false),
    ('崎', '蝉散', true, false),
    ('きゅう', '蟻集', true, false),
    ('ぴよな', '蟻集', true, false),
    ('崎', '蟻集', true, false),
    ('きゅう', '裁くもの、裁かれるもの', true, false),
    ('れいにー', '裁くもの、裁かれるもの', true, false),
    ('江波（えなみん）', '裁くもの、裁かれるもの', true, false),
    ('松井（まつい）', '裁判員の仮面', true, false),
    ('江波（えなみん）', '裁判員の仮面', true, false),
    ('きゅう', '裂き子さん', true, false),
    ('つばめ', '裂き子さん', true, false),
    ('ぴよな', '裂き子さん', true, false),
    ('ぽん', '裂き子さん', true, false),
    ('みずき', '裂き子さん', true, false),
    ('りえぞー', '裂き子さん', true, false),
    ('つばめ', '誠実な十字架', true, false),
    ('ぴよな', '誠実な十字架', true, false),
    ('八継じの', '誠実な十字架', true, false),
    ('江波（えなみん）', '誠実な十字架', true, false),
    ('えりん', '赤の導線', true, false),
    ('しらやま', '赤の導線', true, false),
    ('ぴよな', '赤の導線', true, false),
    ('りえぞー', '赤の導線', true, false),
    ('れいにー', '赤の導線', true, false),
    ('江波（えなみん）', '赤の導線', true, false),
    ('つばめ', '赤鬼が泣いた夜', true, false),
    ('あんころ', '超特急の呪いの館で撮れ高足りてますか？', true, false),
    ('きゅう', '超特急の呪いの館で撮れ高足りてますか？', true, false),
    ('ぴよな', '超特急の呪いの館で撮れ高足りてますか？', true, false),
    ('ソラ', '超特急の呪いの館で撮れ高足りてますか？', true, false),
    ('labo', '違人', true, false),
    ('きゅう', '違人', true, false),
    ('きゅう', '野槌', true, false),
    ('きゅう', '鉄紺の証言', true, false),
    ('江波（えなみん）', '鉄紺の証言', true, false),
    ('きゅう', '銀世界のアシアト(５月まで）', true, false),
    ('しらやま', '銀世界のアシアト(５月まで）', true, false),
    ('ぴよな', '銀世界のアシアト(５月まで）', true, false),
    ('りえぞー', '銀世界のアシアト(５月まで）', true, false),
    ('りんな', '銀世界のアシアト(５月まで）', true, false),
    ('ソラ', '銀世界のアシアト(５月まで）', true, false),
    ('崎', '銀世界のアシアト(５月まで）', true, false),
    ('松井（まつい）', '銀世界のアシアト(５月まで）', true, false),
    ('江波（えなみん）', '銀世界のアシアト(５月まで）', true, false),
    ('藤崎ソルト', '銀世界のアシアト(５月まで）', true, false),
    ('えりん', '電脳の檻のアリス', true, false),
    ('ぴよな', '電脳の檻のアリス', true, false),
    ('りえぞー', '電脳の檻のアリス', true, false),
    ('八継じの', '電脳の檻のアリス', true, false),
    ('きゅう', '霧に眠るは幾つの罪', true, false),
    ('ぽったー', '霧に眠るは幾つの罪', true, false),
    ('れいにー', '霧に眠るは幾つの罪', true, false),
    ('崎', '霧に眠るは幾つの罪', true, false),
    ('松井（まつい）', '霧に眠るは幾つの罪', true, false),
    ('江波（えなみん）', '霧に眠るは幾つの罪', true, false),
    ('みずき', '鬼哭館の殺人事件', true, false),
    ('れいにー', '鬼哭館の殺人事件', true, false),
    ('ソラ', '鬼哭館の殺人事件', true, false),
    ('松井（まつい）', '鬼哭館の殺人事件', true, false),
    ('つばめ', '魂を運ぶ飛行船', true, false),
    ('りんな', '魂を運ぶ飛行船', true, false),
    ('藤崎ソルト', '魂を運ぶ飛行船', true, false),
    ('江波（えなみん）', '魔女の聖餐式', true, false),
    ('きゅう', '鳴神様のいうとおり', true, false),
    ('ぽん', '鳴神様のいうとおり', true, false),
    ('りえぞー', '鳴神様のいうとおり', true, false),
    ('江波（えなみん）', '鳴神様のいうとおり', true, false),
    ('松井（まつい）', '鹿神館の罪人', true, false),
    ('江波（えなみん）', '鹿神館の罪人', true, false),
    ('れいにー', '黒い森の獣part1', true, false),
    ('松井（まつい）', '黒い森の獣part1', true, false),
    ('れいにー', '黒い森の獣part2人と狼', true, false),
    ('松井（まつい）', '黒い森の獣part2人と狼', true, false),
    ('Remia（れみあ）', '黒と白の狭間に', true, false),
    ('えりん', '黒と白の狭間に', true, false),
    ('しらやま', '黒と白の狭間に', true, false),
    ('つばめ', '黒と白の狭間に', true, false),
    ('江波（えなみん）', '黒と白の狭間に', true, false)
) AS gp(staff_name, scenario_title, main_gm, sub_gm)
JOIN staff s ON s.name = gp.staff_name
JOIN scenarios sc ON sc.title = gp.scenario_title
ON CONFLICT (staff_id, scenario_id)
DO UPDATE SET
  can_main_gm = EXCLUDED.can_main_gm,
  can_sub_gm = EXCLUDED.can_sub_gm,
  is_experienced = false;

-- ===========================================
-- STEP 1-5: GM復元 (601~602/602)
-- ===========================================
INSERT INTO staff_scenario_assignments (staff_id, scenario_id, can_main_gm, can_sub_gm, is_experienced, can_gm_at)
SELECT s.id, sc.id, gp.main_gm, gp.sub_gm, false, NOW()
FROM (VALUES
    ('だいこん', '黒の眺望', true, false),
    ('松井（まつい）', '黒の眺望', true, false)
) AS gp(staff_name, scenario_title, main_gm, sub_gm)
JOIN staff s ON s.name = gp.staff_name
JOIN scenarios sc ON sc.title = gp.scenario_title
ON CONFLICT (staff_id, scenario_id)
DO UPDATE SET
  can_main_gm = EXCLUDED.can_main_gm,
  can_sub_gm = EXCLUDED.can_sub_gm,
  is_experienced = false;

-- ===========================================
-- STEP 2-1: 体験済み復元 (1~150/1577)
-- ===========================================
INSERT INTO staff_scenario_assignments (staff_id, scenario_id, can_main_gm, can_sub_gm, is_experienced, can_gm_at)
SELECT s.id, sc.id, false, false, true, NOW()
FROM (VALUES
    ('Remia（れみあ）', '5DIVE'),
    ('labo', '5DIVE'),
    ('あんころ', '5DIVE'),
    ('えりん(12/20予定）ソラ', '5DIVE'),
    ('だいこん', '5DIVE'),
    ('つばめ', '5DIVE'),
    ('ぽったー', '5DIVE'),
    ('ぽん', '5DIVE'),
    ('みずき', '5DIVE'),
    ('りえぞー', '5DIVE'),
    ('りんな', '5DIVE'),
    ('れいにー', '5DIVE'),
    ('ソウタン', '5DIVE'),
    ('崎', '5DIVE'),
    ('松井（まつい）', '5DIVE'),
    ('江波（えなみん）', '5DIVE'),
    ('藤崎ソルト', '5DIVE'),
    ('Remia（れみあ）', 'BBA'),
    ('labo', 'BBA'),
    ('あんころ', 'BBA'),
    ('えりん', 'BBA'),
    ('きゅう', 'BBA'),
    ('しらやま', 'BBA'),
    ('ぴよな', 'BBA'),
    ('ぽったー', 'BBA'),
    ('れいにー', 'BBA'),
    ('イワセモリシ', 'BBA'),
    ('ソラ', 'BBA'),
    ('八継じの', 'BBA'),
    ('松井（まつい）', 'BBA'),
    ('江波（えなみん）', 'BBA'),
    ('Remia（れみあ）', 'BeatSpecter'),
    ('labo', 'BeatSpecter'),
    ('あんころ', 'BeatSpecter'),
    ('ぽったー', 'BeatSpecter'),
    ('れいにー', 'BeatSpecter'),
    ('ソラ', 'BeatSpecter'),
    ('ミカノハ', 'BeatSpecter'),
    ('labo', 'BrightChoice'),
    ('えりん', 'BrightChoice'),
    ('つばめ', 'BrightChoice'),
    ('ほがらか', 'BrightChoice'),
    ('ぽったー', 'BrightChoice'),
    ('ぽん', 'BrightChoice'),
    ('みずき', 'BrightChoice'),
    ('りえぞー', 'BrightChoice'),
    ('れいにー', 'BrightChoice'),
    ('イワセモリシ', 'BrightChoice'),
    ('八継じの', 'BrightChoice'),
    ('松井（まつい）', 'BrightChoice'),
    ('藤崎ソルト', 'BrightChoice'),
    ('labo', 'DearmyD'),
    ('えりん', 'DearmyD'),
    ('きゅう', 'DearmyD'),
    ('しらやま', 'DearmyD'),
    ('ぽん', 'DearmyD'),
    ('みくみん', 'DearmyD'),
    ('みずき', 'DearmyD'),
    ('ソラ', 'DearmyD'),
    ('渚咲', 'DearmyD'),
    ('labo', 'ENIGMACODE廃棄ミライの犠牲者たち'),
    ('あんころ', 'ENIGMACODE廃棄ミライの犠牲者たち'),
    ('えりん', 'ENIGMACODE廃棄ミライの犠牲者たち'),
    ('だいこん', 'ENIGMACODE廃棄ミライの犠牲者たち'),
    ('つばめ', 'ENIGMACODE廃棄ミライの犠牲者たち'),
    ('ぽったー', 'ENIGMACODE廃棄ミライの犠牲者たち'),
    ('りんな', 'ENIGMACODE廃棄ミライの犠牲者たち'),
    ('ソラ', 'ENIGMACODE廃棄ミライの犠牲者たち'),
    ('奏兎', 'ENIGMACODE廃棄ミライの犠牲者たち'),
    ('温風リン', 'ENIGMACODE廃棄ミライの犠牲者たち'),
    ('藤崎ソルト', 'ENIGMACODE廃棄ミライの犠牲者たち'),
    ('えりん', 'Factor'),
    ('きゅう', 'Factor'),
    ('つばめ', 'Factor'),
    ('みずき', 'GARDENリーガー殺人事件'),
    ('れいにー', 'GARDENリーガー殺人事件'),
    ('江波（えなみん）', 'GARDENリーガー殺人事件'),
    ('labo', 'GM殺人事件'),
    ('しらやま', 'GM殺人事件'),
    ('つばめ', 'GM殺人事件'),
    ('ぴよな', 'GM殺人事件'),
    ('ぽったー', 'GM殺人事件'),
    ('イワセモリシ', 'GM殺人事件'),
    ('ソラ', 'GM殺人事件'),
    ('ミカノハ', 'GM殺人事件'),
    ('藤崎ソルト', 'GM殺人事件'),
    ('えりん', 'Grape'),
    ('きゅう', 'Grape'),
    ('八継じの', 'Grape'),
    ('kanade', 'Invisible-亡霊列車-'),
    ('labo', 'Invisible-亡霊列車-'),
    ('えりん', 'Invisible-亡霊列車-'),
    ('しらやま', 'Invisible-亡霊列車-'),
    ('ぽったー', 'Invisible-亡霊列車-'),
    ('りんな', 'Invisible-亡霊列車-'),
    ('松井（まつい）', 'Invisible-亡霊列車-'),
    ('藤崎ソルト', 'Invisible-亡霊列車-'),
    ('labo', 'Iwillex-'),
    ('えりん', 'Iwillex-'),
    ('きゅう', 'Iwillex-'),
    ('ぽったー', 'Iwillex-'),
    ('みずき', 'Iwillex-'),
    ('八継じの', 'Iwillex-'),
    ('松井（まつい）', 'Iwillex-'),
    ('渚咲', 'Iwillex-'),
    ('きゅう', 'Jazzy'),
    ('つばめ', 'Jazzy'),
    ('イワセモリシ', 'Jazzy'),
    ('崎', 'Jazzy'),
    ('江波（えなみん）', 'Jazzy'),
    ('あんころ', 'MERCHANT'),
    ('えりん', 'MERCHANT'),
    ('きゅう', 'MERCHANT'),
    ('だいこん', 'MERCHANT'),
    ('つばめ', 'MERCHANT'),
    ('ぴよな', 'MERCHANT'),
    ('ぽん', 'MERCHANT'),
    ('みずき', 'MERCHANT'),
    ('古賀', 'MERCHANT'),
    ('崎', 'MERCHANT'),
    ('江波（えなみん）', 'MERCHANT'),
    ('あんころ', 'MissingLink（ミッシングリンク）'),
    ('しらやま', 'MissingLink（ミッシングリンク）'),
    ('つばめ', 'MissingLink（ミッシングリンク）'),
    ('ぽったー', 'MissingLink（ミッシングリンク）'),
    ('ソラ', 'MissingLink（ミッシングリンク）'),
    ('ミカノハ', 'MissingLink（ミッシングリンク）'),
    ('八継じの', 'MissingLink（ミッシングリンク）'),
    ('崎', 'MissingLink（ミッシングリンク）'),
    ('labo', 'REDRUM01泉涌館の変転'),
    ('えりん', 'REDRUM01泉涌館の変転'),
    ('ぽったー', 'REDRUM01泉涌館の変転'),
    ('ミカノハ', 'REDRUM01泉涌館の変転'),
    ('松井（まつい）', 'REDRUM01泉涌館の変転'),
    ('あんころ', 'REDRUM02虚像のF'),
    ('えりん', 'REDRUM02虚像のF'),
    ('きゅう', 'REDRUM02虚像のF'),
    ('だいこん', 'REDRUM02虚像のF'),
    ('ぽったー', 'REDRUM02虚像のF'),
    ('ミカノハ', 'REDRUM02虚像のF'),
    ('松井（まつい）', 'REDRUM02虚像のF'),
    ('藤崎ソルト', 'REDRUM02虚像のF'),
    ('だいこん', 'REDRUM03致命的観測をもう一度'),
    ('ぽったー', 'REDRUM03致命的観測をもう一度'),
    ('れいにー', 'REDRUM03致命的観測をもう一度'),
    ('ミカノハ', 'REDRUM03致命的観測をもう一度'),
    ('八継じの', 'REDRUM03致命的観測をもう一度'),
    ('松井（まつい）', 'REDRUM03致命的観測をもう一度'),
    ('藤崎ソルト', 'REDRUM03致命的観測をもう一度'),
    ('ぽったー', 'REDRUM4アルテミスの断罪')
) AS ep(staff_name, scenario_title)
JOIN staff s ON s.name = ep.staff_name
JOIN scenarios sc ON sc.title = ep.scenario_title
ON CONFLICT (staff_id, scenario_id)
DO UPDATE SET
  can_main_gm = false,
  can_sub_gm = false,
  is_experienced = true;

-- ===========================================
-- STEP 2-2: 体験済み復元 (151~300/1577)
-- ===========================================
INSERT INTO staff_scenario_assignments (staff_id, scenario_id, can_main_gm, can_sub_gm, is_experienced, can_gm_at)
SELECT s.id, sc.id, false, false, true, NOW()
FROM (VALUES
    ('渚咲', 'REDRUM4アルテミスの断罪'),
    ('Remia（れみあ）', 'Recollection'),
    ('あんころ', 'Recollection'),
    ('えりん', 'Recollection'),
    ('きゅう', 'Recollection'),
    ('だいこん', 'Recollection'),
    ('ほがらか', 'Recollection'),
    ('ぽん', 'Recollection'),
    ('みくみん', 'Recollection'),
    ('りえぞー', 'Recollection'),
    ('りんな', 'Recollection'),
    ('れいにー', 'Recollection'),
    ('ソウタン', 'Recollection'),
    ('ミカノハ', 'Recollection'),
    ('八継じの', 'Recollection'),
    ('松井（まつい）', 'Recollection'),
    ('江波（えなみん）', 'Recollection'),
    ('しらやま', 'SORCIER～賢者達の物語～'),
    ('だいこん', 'SORCIER～賢者達の物語～'),
    ('ほがらか', 'SORCIER～賢者達の物語～'),
    ('みくみん', 'SORCIER～賢者達の物語～'),
    ('りんな', 'SORCIER～賢者達の物語～'),
    ('ミカノハ', 'SORCIER～賢者達の物語～'),
    ('八継じの', 'SORCIER～賢者達の物語～'),
    ('江波（えなみん）', 'SORCIER～賢者達の物語～'),
    ('えりん', 'TOOLS〜ぎこちない椅子'),
    ('だいこん', 'TOOLS〜ぎこちない椅子'),
    ('ぽったー', 'TOOLS〜ぎこちない椅子'),
    ('みずき', 'TOOLS〜ぎこちない椅子'),
    ('松井（まつい）', 'TOOLS〜ぎこちない椅子'),
    ('江波（えなみん）', 'TOOLS〜ぎこちない椅子'),
    ('あんころ', 'TheRealFork30'),
    ('きゅう', 'TheRealFork30'),
    ('ぴよな', 'TheRealFork30'),
    ('りんな', 'TheRealFork30'),
    ('イワセモリシ', 'TheRealFork30'),
    ('八継じの', 'TheRealFork30'),
    ('きゅう', 'WANTEDz'),
    ('ほがらか', 'WANTEDz'),
    ('ぽん', 'WANTEDz'),
    ('みずき', 'WANTEDz'),
    ('れいにー', 'WANTEDz'),
    ('Remia（れみあ）', 'WORLDEND'),
    ('きゅう', 'WORLDEND'),
    ('しらやま', 'WORLDEND'),
    ('だいこん', 'WORLDEND'),
    ('ぽったー', 'WORLDEND'),
    ('みずき', 'WORLDEND'),
    ('れいにー', 'WORLDEND'),
    ('松井（まつい）', 'WORLDEND'),
    ('江波（えなみん）', 'WORLDEND'),
    ('きゅう', 'inthebox〜長い熱病'),
    ('しらやま', 'inthebox〜長い熱病'),
    ('だいこん', 'inthebox〜長い熱病'),
    ('つばめ', 'inthebox〜長い熱病'),
    ('ぽったー', 'inthebox〜長い熱病'),
    ('りんな', 'inthebox〜長い熱病'),
    ('イワセモリシ', 'inthebox〜長い熱病'),
    ('ソラ', 'inthebox〜長い熱病'),
    ('松井（まつい）', 'inthebox〜長い熱病'),
    ('えりん', 'readme.txt'),
    ('きゅう', 'readme.txt'),
    ('ぽん', 'readme.txt'),
    ('れいにー', 'readme.txt'),
    ('崎', 'readme.txt'),
    ('松井（まつい）', 'readme.txt'),
    ('江波（えなみん）', 'readme.txt'),
    ('藤崎ソルト', 'readme.txt'),
    ('Remia（れみあ）', 'あくなき世界で嘘をうたう'),
    ('えりん', 'あくなき世界で嘘をうたう'),
    ('きゅう', 'あくなき世界で嘘をうたう'),
    ('つばめ', 'あくなき世界で嘘をうたう'),
    ('ぴよな', 'あくなき世界で嘘をうたう'),
    ('みくみん', 'あくなき世界で嘘をうたう'),
    ('れいにー', 'あくなき世界で嘘をうたう'),
    ('松井（まつい）', 'あくなき世界で嘘をうたう'),
    ('Remia（れみあ）', 'あの夏のアンタレス'),
    ('しらやま', 'あの夏のアンタレス'),
    ('古賀', 'あの夏のアンタレス'),
    ('江波（えなみん）', 'あの夏のアンタレス'),
    ('きゅう', 'あるマーダーミステリーについて'),
    ('だいこん', 'あるマーダーミステリーについて'),
    ('ぴよな', 'あるマーダーミステリーについて'),
    ('ほがらか', 'あるマーダーミステリーについて'),
    ('ぽったー', 'あるマーダーミステリーについて'),
    ('ぽん', 'あるマーダーミステリーについて'),
    ('みずき', 'あるマーダーミステリーについて'),
    ('イワセモリシ', 'あるマーダーミステリーについて'),
    ('ソラ', 'あるマーダーミステリーについて'),
    ('ミカノハ', 'あるマーダーミステリーについて'),
    ('崎', 'あるマーダーミステリーについて'),
    ('しらやま', 'ある悪魔の儀式について'),
    ('ソラ', 'ある悪魔の儀式について'),
    ('八継じの', 'ある悪魔の儀式について'),
    ('温風リン', 'ある悪魔の儀式について'),
    ('Remia（れみあ）', 'くずの葉のもり'),
    ('えりん', 'くずの葉のもり'),
    ('ぴよな', 'くずの葉のもり'),
    ('ぽったー', 'くずの葉のもり'),
    ('りんな', 'くずの葉のもり'),
    ('イワセモリシ', 'くずの葉のもり'),
    ('崎', 'くずの葉のもり'),
    ('松井（まつい）', 'くずの葉のもり'),
    ('藤崎ソルト', 'くずの葉のもり'),
    ('kanade', 'この闇をあなたと'),
    ('labo', 'この闇をあなたと'),
    ('あんころ', 'この闇をあなたと'),
    ('えりん', 'この闇をあなたと'),
    ('だいこん', 'この闇をあなたと'),
    ('つばめ', 'この闇をあなたと'),
    ('ぴよな', 'この闇をあなたと'),
    ('ほがらか', 'この闇をあなたと'),
    ('ぽったー', 'この闇をあなたと'),
    ('みずき', 'この闇をあなたと'),
    ('りんな', 'この闇をあなたと'),
    ('れいにー', 'この闇をあなたと'),
    ('イワセモリシ', 'この闇をあなたと'),
    ('ソウタン', 'この闇をあなたと'),
    ('ミカノハ', 'この闇をあなたと'),
    ('崎', 'この闇をあなたと'),
    ('藤崎ソルト', 'この闇をあなたと'),
    ('Remia（れみあ）', 'つわものどもが夢のあと'),
    ('えりん', 'つわものどもが夢のあと'),
    ('ぽん', 'つわものどもが夢のあと'),
    ('りえぞー', 'つわものどもが夢のあと'),
    ('ソラ', 'つわものどもが夢のあと'),
    ('江波（えなみん）', 'つわものどもが夢のあと'),
    ('ほがらか', 'ひぐらしのなく頃に　恨返し編'),
    ('ぽん', 'ひぐらしのなく頃に　恨返し編'),
    ('古賀', 'ひぐらしのなく頃に　恨返し編'),
    ('江波（えなみん）', 'ひぐらしのなく頃に　恨返し編'),
    ('ほがらか', 'へっどぎあ★ぱにっく'),
    ('ぽん', 'へっどぎあ★ぱにっく'),
    ('みずき', 'へっどぎあ★ぱにっく'),
    ('りえぞー', 'へっどぎあ★ぱにっく'),
    ('れいにー', 'へっどぎあ★ぱにっく'),
    ('崎', 'へっどぎあ★ぱにっく'),
    ('松井（まつい）', 'へっどぎあ★ぱにっく'),
    ('Remia（れみあ）', 'アオハルーツ'),
    ('えりん', 'アオハルーツ'),
    ('つばめ', 'アオハルーツ'),
    ('ほがらか', 'アオハルーツ'),
    ('ぽん', 'アオハルーツ'),
    ('みずき', 'アオハルーツ'),
    ('れいにー', 'アオハルーツ'),
    ('ソラ', 'アオハルーツ'),
    ('松井（まつい）', 'アオハルーツ'),
    ('Remia（れみあ）', 'アオハループ'),
    ('あんころ', 'アオハループ'),
    ('えりん', 'アオハループ')
) AS ep(staff_name, scenario_title)
JOIN staff s ON s.name = ep.staff_name
JOIN scenarios sc ON sc.title = ep.scenario_title
ON CONFLICT (staff_id, scenario_id)
DO UPDATE SET
  can_main_gm = false,
  can_sub_gm = false,
  is_experienced = true;

-- ===========================================
-- STEP 2-3: 体験済み復元 (301~450/1577)
-- ===========================================
INSERT INTO staff_scenario_assignments (staff_id, scenario_id, can_main_gm, can_sub_gm, is_experienced, can_gm_at)
SELECT s.id, sc.id, false, false, true, NOW()
FROM (VALUES
    ('きゅう', 'アオハループ'),
    ('ぴよな', 'アオハループ'),
    ('ほがらか', 'アオハループ'),
    ('りんな', 'アオハループ'),
    ('れいにー', 'アオハループ'),
    ('イワセモリシ', 'アオハループ'),
    ('ソラ', 'アオハループ'),
    ('八継じの', 'アオハループ'),
    ('古賀', 'アオハループ'),
    ('松井（まつい）', 'アオハループ'),
    ('江波（えなみん）', 'アオハループ'),
    ('温風リン', 'アオハループ'),
    ('藤崎ソルト', 'アオハループ'),
    ('Remia（れみあ）', 'アンシンメトリー'),
    ('つばめ', 'アンシンメトリー'),
    ('ぽったー', 'アンシンメトリー'),
    ('ソラ', 'アンシンメトリー'),
    ('藤崎ソルト', 'アンシンメトリー'),
    ('kanade', 'アンドロイドは愛を知らない'),
    ('ぴよな', 'アンドロイドは愛を知らない'),
    ('ぽったー', 'アンドロイドは愛を知らない'),
    ('イワセモリシ', 'アンドロイドは愛を知らない'),
    ('ミカノハ', 'アンドロイドは愛を知らない'),
    ('温風リン', 'アンドロイドは愛を知らない'),
    ('藤崎ソルト', 'アンドロイドは愛を知らない'),
    ('Remia（れみあ）', 'アンフィスバエナと聖女の祈り'),
    ('labo', 'アンフィスバエナと聖女の祈り'),
    ('えりん', 'アンフィスバエナと聖女の祈り'),
    ('きゅう', 'アンフィスバエナと聖女の祈り'),
    ('だいこん', 'アンフィスバエナと聖女の祈り'),
    ('つばめ', 'アンフィスバエナと聖女の祈り'),
    ('ぴよな', 'アンフィスバエナと聖女の祈り'),
    ('ほがらか', 'アンフィスバエナと聖女の祈り'),
    ('みずき', 'アンフィスバエナと聖女の祈り'),
    ('れいにー', 'アンフィスバエナと聖女の祈り'),
    ('イワセモリシ', 'アンフィスバエナと聖女の祈り'),
    ('ソウタン', 'アンフィスバエナと聖女の祈り'),
    ('ソラ', 'アンフィスバエナと聖女の祈り'),
    ('八継じの', 'アンフィスバエナと聖女の祈り'),
    ('崎', 'アンフィスバエナと聖女の祈り'),
    ('江波（えなみん）', 'アンフィスバエナと聖女の祈り'),
    ('藤崎ソルト', 'アンフィスバエナと聖女の祈り'),
    ('Remia（れみあ）', 'ウロボロスの眠り'),
    ('ぴよな', 'ウロボロスの眠り'),
    ('ほがらか', 'ウロボロスの眠り'),
    ('ぽん', 'ウロボロスの眠り'),
    ('りえぞー', 'ウロボロスの眠り'),
    ('れいにー', 'ウロボロスの眠り'),
    ('Remia（れみあ）', 'エイダ'),
    ('kanade', 'エイダ'),
    ('labo', 'エイダ'),
    ('えりん', 'エイダ'),
    ('きゅう', 'エイダ'),
    ('だいこん', 'エイダ'),
    ('つばめ', 'エイダ'),
    ('ぴよな', 'エイダ'),
    ('ほがらか', 'エイダ'),
    ('ぽったー', 'エイダ'),
    ('ぽん', 'エイダ'),
    ('みくみん', 'エイダ'),
    ('れいにー', 'エイダ'),
    ('ソラ', 'エイダ'),
    ('ミカノハ', 'エイダ'),
    ('八継じの', 'エイダ'),
    ('古賀', 'エイダ'),
    ('奏兎', 'エイダ'),
    ('崎', 'エイダ'),
    ('松井（まつい）', 'エイダ'),
    ('江波（えなみん）', 'エイダ'),
    ('渚咲', 'エイダ'),
    ('温風リン', 'エイダ'),
    ('Remia（れみあ）', 'エデンの審判'),
    ('えりん', 'エデンの審判'),
    ('ほがらか', 'エデンの審判'),
    ('ぽったー', 'エデンの審判'),
    ('ぽん', 'エデンの審判'),
    ('みずき', 'エデンの審判'),
    ('れいにー', 'エデンの審判'),
    ('八継じの', 'エデンの審判'),
    ('松井（まつい）', 'エデンの審判'),
    ('江波（えなみん）', 'エデンの審判'),
    ('Remia（れみあ）', 'エンドロールは流れない'),
    ('kanade', 'エンドロールは流れない'),
    ('labo', 'エンドロールは流れない'),
    ('えりん', 'エンドロールは流れない'),
    ('きゅう', 'エンドロールは流れない'),
    ('しらやま', 'エンドロールは流れない'),
    ('だいこん', 'エンドロールは流れない'),
    ('つばめ', 'エンドロールは流れない'),
    ('ぴよな', 'エンドロールは流れない'),
    ('ほがらか', 'エンドロールは流れない'),
    ('りんな', 'エンドロールは流れない'),
    ('れいにー', 'エンドロールは流れない'),
    ('イワセモリシ', 'エンドロールは流れない'),
    ('ミカノハ', 'エンドロールは流れない'),
    ('古賀', 'エンドロールは流れない'),
    ('奏兎', 'エンドロールは流れない'),
    ('崎', 'エンドロールは流れない'),
    ('松井（まつい）', 'エンドロールは流れない'),
    ('江波（えなみん）', 'エンドロールは流れない'),
    ('温風リン', 'エンドロールは流れない'),
    ('Remia（れみあ）', 'オペレーション：ゴーストウィング'),
    ('きゅう', 'オペレーション：ゴーストウィング'),
    ('つばめ', 'オペレーション：ゴーストウィング'),
    ('ぽったー', 'オペレーション：ゴーストウィング'),
    ('らの', 'オペレーション：ゴーストウィング'),
    ('りんな', 'オペレーション：ゴーストウィング'),
    ('ミカノハ', 'オペレーション：ゴーストウィング'),
    ('きゅう', 'キヲクの方舟'),
    ('ぽったー', 'キヲクの方舟'),
    ('みずき', 'キヲクの方舟'),
    ('りえぞー', 'キヲクの方舟'),
    ('松井（まつい）', 'キヲクの方舟'),
    ('江波（えなみん）', 'キヲクの方舟'),
    ('Remia（れみあ）', 'キングを殺すには'),
    ('あんころ', 'キングを殺すには'),
    ('きゅう', 'キングを殺すには'),
    ('だいこん', 'キングを殺すには'),
    ('ほがらか', 'キングを殺すには'),
    ('みずき', 'キングを殺すには'),
    ('りえぞー', 'キングを殺すには'),
    ('れいにー', 'キングを殺すには'),
    ('崎', 'キングを殺すには'),
    ('江波（えなみん）', 'キングを殺すには'),
    ('labo', 'クリエイターズハイ'),
    ('えりん', 'クリエイターズハイ'),
    ('ほがらか', 'クリエイターズハイ'),
    ('ぽったー', 'クリエイターズハイ'),
    ('ぽん', 'クリエイターズハイ'),
    ('れいにー', 'クリエイターズハイ'),
    ('八継じの', 'クリエイターズハイ'),
    ('松井（まつい）', 'クリエイターズハイ'),
    ('Remia（れみあ）', 'クリムゾンアート'),
    ('kanade', 'クリムゾンアート'),
    ('きゅう', 'クリムゾンアート'),
    ('つばめ', 'クリムゾンアート'),
    ('ほがらか', 'クリムゾンアート'),
    ('みずき', 'クリムゾンアート'),
    ('れいにー', 'クリムゾンアート'),
    ('江波（えなみん）', 'クリムゾンアート'),
    ('Remia（れみあ）', 'クロノフォビア'),
    ('labo', 'クロノフォビア'),
    ('えりん', 'クロノフォビア'),
    ('だいこん', 'クロノフォビア'),
    ('ぽったー', 'クロノフォビア'),
    ('ぽん', 'クロノフォビア'),
    ('みずき', 'クロノフォビア'),
    ('れいにー', 'クロノフォビア'),
    ('崎', 'クロノフォビア'),
    ('松井（まつい）', 'クロノフォビア')
) AS ep(staff_name, scenario_title)
JOIN staff s ON s.name = ep.staff_name
JOIN scenarios sc ON sc.title = ep.scenario_title
ON CONFLICT (staff_id, scenario_id)
DO UPDATE SET
  can_main_gm = false,
  can_sub_gm = false,
  is_experienced = true;

-- ===========================================
-- STEP 2-4: 体験済み復元 (451~600/1577)
-- ===========================================
INSERT INTO staff_scenario_assignments (staff_id, scenario_id, can_main_gm, can_sub_gm, is_experienced, can_gm_at)
SELECT s.id, sc.id, false, false, true, NOW()
FROM (VALUES
    ('江波（えなみん）', 'クロノフォビア'),
    ('labo', 'グロリアメモリーズ'),
    ('えりん', 'グロリアメモリーズ'),
    ('しらやま', 'グロリアメモリーズ'),
    ('つばめ', 'グロリアメモリーズ'),
    ('ぽったー', 'グロリアメモリーズ'),
    ('ぽん', 'グロリアメモリーズ'),
    ('りんな', 'グロリアメモリーズ'),
    ('れいにー', 'グロリアメモリーズ'),
    ('ソウタン', 'グロリアメモリーズ'),
    ('八継じの', 'グロリアメモリーズ'),
    ('崎', 'グロリアメモリーズ'),
    ('江波（えなみん）', 'グロリアメモリーズ'),
    ('藤崎ソルト', 'グロリアメモリーズ'),
    ('Remia（れみあ）', 'ゴージャスマンション'),
    ('あんころ', 'ゴージャスマンション'),
    ('えりん', 'ゴージャスマンション'),
    ('ぴよな', 'ゴージャスマンション'),
    ('りんな', 'ゴージャスマンション'),
    ('イワセモリシ', 'ゴージャスマンション'),
    ('八継じの', 'ゴージャスマンション'),
    ('あんころ', 'スターループ'),
    ('江波（えなみん）', 'スターループ'),
    ('温風リン', 'スターループ'),
    ('Remia（れみあ）', 'ゼロの爆弾'),
    ('あんころ', 'ゼロの爆弾'),
    ('きゅう', 'ゼロの爆弾'),
    ('しらやま', 'ゼロの爆弾'),
    ('つばめ', 'ゼロの爆弾'),
    ('ぽったー', 'ゼロの爆弾'),
    ('りんな', 'ゼロの爆弾'),
    ('江波（えなみん）', 'ゼロの爆弾'),
    ('えりん', 'ツイン号沈没事件に関する考察'),
    ('あんころ', 'ツグミドリ'),
    ('しらやま', 'ツグミドリ'),
    ('ぴよな', 'ツグミドリ'),
    ('れいにー', 'ツグミドリ'),
    ('ミカノハ', 'ツグミドリ'),
    ('八継じの', 'ツグミドリ'),
    ('藤崎ソルト', 'ツグミドリ'),
    ('Remia（れみあ）', 'テセウスの方舟'),
    ('labo', 'テセウスの方舟'),
    ('きゅう', 'テセウスの方舟'),
    ('ぽったー', 'テセウスの方舟'),
    ('りんな', 'テセウスの方舟'),
    ('イワセモリシ', 'テセウスの方舟'),
    ('ソラ', 'テセウスの方舟'),
    ('ミカノハ', 'テセウスの方舟'),
    ('Remia（れみあ）', 'デモンズボックス'),
    ('きゅう', 'デモンズボックス'),
    ('ほがらか', 'デモンズボックス'),
    ('ぽん', 'デモンズボックス'),
    ('れいにー', 'デモンズボックス'),
    ('崎', 'デモンズボックス'),
    ('松井（まつい）', 'デモンズボックス'),
    ('Remia（れみあ）', 'ドクター・テラスの秘密の実験'),
    ('えりん', 'ドクター・テラスの秘密の実験'),
    ('ほがらか', 'ドクター・テラスの秘密の実験'),
    ('ぽったー', 'ドクター・テラスの秘密の実験'),
    ('ぽん', 'ドクター・テラスの秘密の実験'),
    ('みくみん', 'ドクター・テラスの秘密の実験'),
    ('れいにー', 'ドクター・テラスの秘密の実験'),
    ('古賀', 'ドクター・テラスの秘密の実験'),
    ('松井（まつい）', 'ドクター・テラスの秘密の実験'),
    ('だいこん', 'ナナイロの迷宮 橙 オンラインゲーム殺人事件'),
    ('ほがらか', 'ナナイロの迷宮 橙 オンラインゲーム殺人事件'),
    ('ミカノハ', 'ナナイロの迷宮 橙 オンラインゲーム殺人事件'),
    ('古賀', 'ナナイロの迷宮 橙 オンラインゲーム殺人事件'),
    ('松井（まつい）', 'ナナイロの迷宮 橙 オンラインゲーム殺人事件'),
    ('江波（えなみん）', 'ナナイロの迷宮 橙 オンラインゲーム殺人事件'),
    ('藤崎ソルト', 'ナナイロの迷宮 橙 オンラインゲーム殺人事件'),
    ('えりん', 'ナナイロの迷宮 黄 エレクトリカル吹奏楽部殺人事件'),
    ('つばめ', 'ナナイロの迷宮 黄 エレクトリカル吹奏楽部殺人事件'),
    ('ほがらか', 'ナナイロの迷宮 黄 エレクトリカル吹奏楽部殺人事件'),
    ('古賀', 'ナナイロの迷宮 黄 エレクトリカル吹奏楽部殺人事件'),
    ('江波（えなみん）', 'ナナイロの迷宮 黄 エレクトリカル吹奏楽部殺人事件'),
    ('藤崎ソルト', 'ナナイロの迷宮 黄 エレクトリカル吹奏楽部殺人事件'),
    ('きゅう', 'バベルの末裔'),
    ('ぽったー', 'バベルの末裔'),
    ('きゅう', 'ヒーロースクランブル'),
    ('ぽん', 'ヒーロースクランブル'),
    ('みずき', 'ヒーロースクランブル'),
    ('れいにー', 'ヒーロースクランブル'),
    ('labo', 'ピタゴラスの篝火'),
    ('えりん', 'ピタゴラスの篝火'),
    ('ぽん', 'ピタゴラスの篝火'),
    ('みずき', 'ピタゴラスの篝火'),
    ('れいにー', 'ピタゴラスの篝火'),
    ('藤崎ソルト', 'ピタゴラスの篝火'),
    ('江波（えなみん）', 'フェイクアブダクション'),
    ('Remia（れみあ）', 'フェイクドナー'),
    ('labo', 'フェイクドナー'),
    ('あんころ', 'フェイクドナー'),
    ('きゅう', 'フェイクドナー'),
    ('だいこん', 'フェイクドナー'),
    ('ほがらか', 'フェイクドナー'),
    ('ぽったー', 'フェイクドナー'),
    ('ぽん', 'フェイクドナー'),
    ('みくみん', 'フェイクドナー'),
    ('りんな', 'フェイクドナー'),
    ('ソラ', 'フェイクドナー'),
    ('崎', 'フェイクドナー'),
    ('松井（まつい）', 'フェイクドナー'),
    ('江波（えなみん）', 'フェイクドナー'),
    ('Remia（れみあ）', 'ブラックナイトスレイヴ'),
    ('えりん', 'ブラックナイトスレイヴ'),
    ('江波（えなみん）', 'ブラックナイトスレイヴ'),
    ('きゅう', 'ブルーダイヤの不在証明'),
    ('ソラ', 'ブルーダイヤの不在証明'),
    ('八継じの', 'ブルーダイヤの不在証明'),
    ('崎', 'ブルーダイヤの不在証明'),
    ('Remia（れみあ）', 'マーダーオブエクスプローラー失われし大秘宝'),
    ('あんころ', 'マーダーオブエクスプローラー失われし大秘宝'),
    ('えりん', 'マーダーオブエクスプローラー失われし大秘宝'),
    ('きゅう', 'マーダーオブエクスプローラー失われし大秘宝'),
    ('だいこん', 'マーダーオブエクスプローラー失われし大秘宝'),
    ('つばめ', 'マーダーオブエクスプローラー失われし大秘宝'),
    ('ぽったー', 'マーダーオブエクスプローラー失われし大秘宝'),
    ('りんな', 'マーダーオブエクスプローラー失われし大秘宝'),
    ('八継じの', 'マーダーオブエクスプローラー失われし大秘宝'),
    ('古賀', 'マーダーオブエクスプローラー失われし大秘宝'),
    ('えりん', 'マーダー・オブ・パイレーツ'),
    ('ほがらか', 'マーダー・オブ・パイレーツ'),
    ('みずき', 'マーダー・オブ・パイレーツ'),
    ('れいにー', 'マーダー・オブ・パイレーツ'),
    ('Remia（れみあ）', 'モノクローム'),
    ('あんころ', 'モノクローム'),
    ('だいこん', 'モノクローム'),
    ('つばめ', 'モノクローム'),
    ('ぴよな', 'モノクローム'),
    ('ほがらか', 'モノクローム'),
    ('ぽん', 'モノクローム'),
    ('りんな', 'モノクローム'),
    ('れいにー', 'モノクローム'),
    ('ソウタン', 'モノクローム'),
    ('ソラ', 'モノクローム'),
    ('松井（まつい）', 'モノクローム'),
    ('江波（えなみん）', 'モノクローム'),
    ('温風リン', 'モノクローム'),
    ('藤崎ソルト', 'モノクローム'),
    ('kanade', 'ヤノハのフタリ'),
    ('labo', 'ヤノハのフタリ'),
    ('きゅう', 'ヤノハのフタリ'),
    ('しらやま', 'ヤノハのフタリ'),
    ('だいこん', 'ヤノハのフタリ'),
    ('つばめ', 'ヤノハのフタリ'),
    ('ぽったー', 'ヤノハのフタリ'),
    ('ぽん', 'ヤノハのフタリ'),
    ('みずき', 'ヤノハのフタリ'),
    ('りんな', 'ヤノハのフタリ')
) AS ep(staff_name, scenario_title)
JOIN staff s ON s.name = ep.staff_name
JOIN scenarios sc ON sc.title = ep.scenario_title
ON CONFLICT (staff_id, scenario_id)
DO UPDATE SET
  can_main_gm = false,
  can_sub_gm = false,
  is_experienced = true;

-- ===========================================
-- STEP 2-5: 体験済み復元 (601~750/1577)
-- ===========================================
INSERT INTO staff_scenario_assignments (staff_id, scenario_id, can_main_gm, can_sub_gm, is_experienced, can_gm_at)
SELECT s.id, sc.id, false, false, true, NOW()
FROM (VALUES
    ('れいにー', 'ヤノハのフタリ'),
    ('藤崎ソルト', 'ヤノハのフタリ'),
    ('きゅう', 'ユートピアース'),
    ('ぽったー', 'ユートピアース'),
    ('みずき', 'ユートピアース'),
    ('りんな', 'ユートピアース'),
    ('れいにー', 'ユートピアース'),
    ('ミカノハ', 'ユートピアース'),
    ('Remia（れみあ）', 'リアルマダミス-MurderWonderLand'),
    ('ぽったー', 'リアルマダミス-MurderWonderLand'),
    ('ぽん', 'リアルマダミス-MurderWonderLand'),
    ('りえぞー', 'リアルマダミス-MurderWonderLand'),
    ('古賀', 'リアルマダミス-MurderWonderLand'),
    ('崎', 'リアルマダミス-MurderWonderLand'),
    ('松井（まつい）', 'リアルマダミス-MurderWonderLand'),
    ('江波（えなみん）', 'リアルマダミス-MurderWonderLand'),
    ('渚咲', 'リアルマダミス-MurderWonderLand'),
    ('Remia（れみあ）', 'リアルマダミス-盤上の教皇'),
    ('えりん', 'リアルマダミス-盤上の教皇'),
    ('きゅう', 'リアルマダミス-盤上の教皇'),
    ('ぽったー', 'リアルマダミス-盤上の教皇'),
    ('ぽん', 'リアルマダミス-盤上の教皇'),
    ('りんな', 'リアルマダミス-盤上の教皇'),
    ('松井（まつい）', 'リアルマダミス-盤上の教皇'),
    ('江波（えなみん）', 'リアルマダミス-盤上の教皇'),
    ('labo', 'リトルワンダー'),
    ('あんころ', 'リトルワンダー'),
    ('きゅう', 'リトルワンダー'),
    ('しらやま', 'リトルワンダー'),
    ('だいこん', 'リトルワンダー'),
    ('ぴよな', 'リトルワンダー'),
    ('ほがらか', 'リトルワンダー'),
    ('ぽったー', 'リトルワンダー'),
    ('りんな', 'リトルワンダー'),
    ('れいにー', 'リトルワンダー'),
    ('イワセモリシ', 'リトルワンダー'),
    ('ソラ', 'リトルワンダー'),
    ('ミカノハ', 'リトルワンダー'),
    ('八継じの', 'リトルワンダー'),
    ('江波（えなみん）', 'リトルワンダー'),
    ('温風リン', 'リトルワンダー'),
    ('あんころ', 'ロスト／リメンブランス'),
    ('えりん', 'ロスト／リメンブランス'),
    ('しらやま', 'ロスト／リメンブランス'),
    ('ほがらか', 'ロスト／リメンブランス'),
    ('ぽったー', 'ロスト／リメンブランス'),
    ('ぽん', 'ロスト／リメンブランス'),
    ('みずき', 'ロスト／リメンブランス'),
    ('崎', 'ロスト／リメンブランス'),
    ('江波（えなみん）', 'ロスト／リメンブランス'),
    ('渚咲', 'ロスト／リメンブランス'),
    ('藤崎ソルト', 'ロスト／リメンブランス'),
    ('りえぞー', 'ロックドドア殺人'),
    ('江波（えなみん）', 'ロックドドア殺人'),
    ('ぽん', '一条家の人々'),
    ('松井（まつい）', '一条家の人々'),
    ('江波（えなみん）', '七股高校'),
    ('Remia（れみあ）', '不思議の国の童話裁判'),
    ('あんころ', '不思議の国の童話裁判'),
    ('しらやま', '不思議の国の童話裁判'),
    ('ぴよな', '不思議の国の童話裁判'),
    ('ほがらか', '不思議の国の童話裁判'),
    ('ぽん', '不思議の国の童話裁判'),
    ('りんな', '不思議の国の童話裁判'),
    ('れいにー', '不思議の国の童話裁判'),
    ('ソラ', '不思議の国の童話裁判'),
    ('古賀', '不思議の国の童話裁判'),
    ('江波（えなみん）', '不思議の国の童話裁判'),
    ('温風リン', '不思議の国の童話裁判'),
    ('ぽん', '人狼を語る館'),
    ('みずき', '人狼を語る館'),
    ('れいにー', '人狼を語る館'),
    ('ソラ', '人狼を語る館'),
    ('江波（えなみん）', '人狼を語る館'),
    ('温風リン', '人狼デスゲームへの挑戦'),
    ('Remia（れみあ）', '人類最後の皆様へ／終末の眠り姫'),
    ('labo', '人類最後の皆様へ／終末の眠り姫'),
    ('えりん', '人類最後の皆様へ／終末の眠り姫'),
    ('だいこん', '人類最後の皆様へ／終末の眠り姫'),
    ('つばめ', '人類最後の皆様へ／終末の眠り姫'),
    ('ぴよな', '人類最後の皆様へ／終末の眠り姫'),
    ('ぽったー', '人類最後の皆様へ／終末の眠り姫'),
    ('ぽん', '人類最後の皆様へ／終末の眠り姫'),
    ('みずき', '人類最後の皆様へ／終末の眠り姫'),
    ('イワセモリシ', '人類最後の皆様へ／終末の眠り姫'),
    ('古賀', '人類最後の皆様へ／終末の眠り姫'),
    ('崎', '人類最後の皆様へ／終末の眠り姫'),
    ('江波（えなみん）', '人類最後の皆様へ／終末の眠り姫'),
    ('Remia（れみあ）', '今日も涙の雨が降る'),
    ('えりん', '今日も涙の雨が降る'),
    ('ぽん', '今日も涙の雨が降る'),
    ('松井（まつい）', '今日も涙の雨が降る'),
    ('江波（えなみん）', '今日も涙の雨が降る'),
    ('labo', '傲慢な女王とアリスの不条理裁判'),
    ('きゅう', '傲慢な女王とアリスの不条理裁判'),
    ('つばめ', '傲慢な女王とアリスの不条理裁判'),
    ('ほがらか', '傲慢な女王とアリスの不条理裁判'),
    ('ぽったー', '傲慢な女王とアリスの不条理裁判'),
    ('みくみん', '傲慢な女王とアリスの不条理裁判'),
    ('八継じの', '傲慢な女王とアリスの不条理裁判'),
    ('古賀', '傲慢な女王とアリスの不条理裁判'),
    ('松井（まつい）', '傲慢な女王とアリスの不条理裁判'),
    ('江波（えなみん）', '傲慢な女王とアリスの不条理裁判'),
    ('Remia（れみあ）', '僕らの未来について'),
    ('きゅう', '僕らの未来について'),
    ('ほがらか', '僕らの未来について'),
    ('ぽん', '僕らの未来について'),
    ('江波（えなみん）', '僕らの未来について'),
    ('Remia（れみあ）', '全能のパラドックス'),
    ('labo', '全能のパラドックス'),
    ('あんころ', '全能のパラドックス'),
    ('えりん', '全能のパラドックス'),
    ('きゅう', '全能のパラドックス'),
    ('しらやま', '全能のパラドックス'),
    ('ぽん', '全能のパラドックス'),
    ('みずき', '全能のパラドックス'),
    ('れいにー', '全能のパラドックス'),
    ('松井（まつい）', '全能のパラドックス'),
    ('きゅう', '凍てつくあなたに６つの灯火'),
    ('つばめ', '凍てつくあなたに６つの灯火'),
    ('ほがらか', '凍てつくあなたに６つの灯火'),
    ('みくみん', '凍てつくあなたに６つの灯火'),
    ('みずき', '凍てつくあなたに６つの灯火'),
    ('れいにー', '凍てつくあなたに６つの灯火'),
    ('イワセモリシ', '凍てつくあなたに６つの灯火'),
    ('江波（えなみん）', '凍てつくあなたに６つの灯火'),
    ('えりん', '午前2時7分'),
    ('ぽん', '午前2時7分'),
    ('みずき', '午前2時7分'),
    ('れいにー', '午前2時7分'),
    ('ソラ', '午前2時7分'),
    ('Remia（れみあ）', '南極地点X'),
    ('kanade', '南極地点X'),
    ('あんころ', '南極地点X'),
    ('だいこん', '南極地点X'),
    ('ほがらか', '南極地点X'),
    ('ぽん', '南極地点X'),
    ('りんな', '南極地点X'),
    ('ミカノハ', '南極地点X'),
    ('江波（えなみん）', '南極地点X'),
    ('藤崎ソルト', '南極地点X'),
    ('きゅう', '口裂け女の微笑み・Mの悪意'),
    ('Remia（れみあ）', '古鐘のなる頃に'),
    ('labo', '古鐘のなる頃に'),
    ('しらやま', '古鐘のなる頃に'),
    ('ぽん', '古鐘のなる頃に'),
    ('みずき', '古鐘のなる頃に'),
    ('りえぞー', '古鐘のなる頃に'),
    ('れいにー', '古鐘のなる頃に'),
    ('Remia（れみあ）', '名探偵と四嶺館')
) AS ep(staff_name, scenario_title)
JOIN staff s ON s.name = ep.staff_name
JOIN scenarios sc ON sc.title = ep.scenario_title
ON CONFLICT (staff_id, scenario_id)
DO UPDATE SET
  can_main_gm = false,
  can_sub_gm = false,
  is_experienced = true;

-- ===========================================
-- STEP 2-6: 体験済み復元 (751~900/1577)
-- ===========================================
INSERT INTO staff_scenario_assignments (staff_id, scenario_id, can_main_gm, can_sub_gm, is_experienced, can_gm_at)
SELECT s.id, sc.id, false, false, true, NOW()
FROM (VALUES
    ('きゅう', '名探偵と四嶺館'),
    ('ぽん', '名探偵と四嶺館'),
    ('れいにー', '名探偵と四嶺館'),
    ('江波（えなみん）', '名探偵と四嶺館'),
    ('labo', '告別詩（取引中止）'),
    ('あんころ', '告別詩（取引中止）'),
    ('つばめ', '告別詩（取引中止）'),
    ('ほがらか', '告別詩（取引中止）'),
    ('ぽったー', '告別詩（取引中止）'),
    ('みずき', '告別詩（取引中止）'),
    ('りんな', '告別詩（取引中止）'),
    ('イワセモリシ', '告別詩（取引中止）'),
    ('ソラ', '告別詩（取引中止）'),
    ('八継じの', '告別詩（取引中止）'),
    ('松井（まつい）', '告別詩（取引中止）'),
    ('江波（えなみん）', '告別詩（取引中止）'),
    ('藤崎ソルト', '告別詩（取引中止）'),
    ('えりん', '土牢に悲鳴は谺して'),
    ('ぽったー', '土牢に悲鳴は谺して'),
    ('りんな', '土牢に悲鳴は谺して'),
    ('ソラ', '土牢に悲鳴は谺して'),
    ('Remia（れみあ）', '境界線のカーサスベリ'),
    ('きゅう', '境界線のカーサスベリ'),
    ('だいこん', '境界線のカーサスベリ'),
    ('ぴよな', '境界線のカーサスベリ'),
    ('りんな', '境界線のカーサスベリ'),
    ('イワセモリシ', '境界線のカーサスベリ'),
    ('八継じの', '境界線のカーサスベリ'),
    ('labo', '天使は花明かりの下で'),
    ('えりん', '天使は花明かりの下で'),
    ('だいこん', '天使は花明かりの下で'),
    ('つばめ', '天使は花明かりの下で'),
    ('れいにー', '天使は花明かりの下で'),
    ('ソラ', '天使は花明かりの下で'),
    ('ミカノハ', '天使は花明かりの下で'),
    ('八継じの', '天使は花明かりの下で'),
    ('古賀', '天使は花明かりの下で'),
    ('奏兎', '天使は花明かりの下で'),
    ('江波（えなみん）', '天使は花明かりの下で'),
    ('藤崎ソルト', '天使は花明かりの下で'),
    ('Remia（れみあ）', '天邪河（あまのじゃく）'),
    ('labo', '天邪河（あまのじゃく）'),
    ('あんころ', '天邪河（あまのじゃく）'),
    ('だいこん', '天邪河（あまのじゃく）'),
    ('つばめ', '天邪河（あまのじゃく）'),
    ('ぴよな', '天邪河（あまのじゃく）'),
    ('ほがらか', '天邪河（あまのじゃく）'),
    ('りんな', '天邪河（あまのじゃく）'),
    ('れいにー', '天邪河（あまのじゃく）'),
    ('ソラ', '天邪河（あまのじゃく）'),
    ('八継じの', '天邪河（あまのじゃく）'),
    ('Remia（れみあ）', '奪うもの、奪われるもの'),
    ('えりん', '奪うもの、奪われるもの'),
    ('ほがらか', '奪うもの、奪われるもの'),
    ('みずき', '奪うもの、奪われるもの'),
    ('崎', '奪うもの、奪われるもの'),
    ('松井（まつい）', '奪うもの、奪われるもの'),
    ('江波（えなみん）', '奪うもの、奪われるもの'),
    ('Remia（れみあ）', '女皇の書架'),
    ('labo', '女皇の書架'),
    ('しらやま', '女皇の書架'),
    ('ぴよな', '女皇の書架'),
    ('ほがらか', '女皇の書架'),
    ('ぽん', '女皇の書架'),
    ('みずき', '女皇の書架'),
    ('りんな', '女皇の書架'),
    ('れいにー', '女皇の書架'),
    ('松井（まつい）', '女皇の書架'),
    ('江波（えなみん）', '女皇の書架'),
    ('藤崎ソルト', '女皇の書架'),
    ('あんころ', '妖怪たちと月夜の刀'),
    ('つばめ', '妖怪たちと月夜の刀'),
    ('ソラ', '妖怪たちと月夜の刀'),
    ('えりん', '季節のマーダーミステリー／ニィホン'),
    ('しらやま', '季節のマーダーミステリー／ニィホン'),
    ('つばめ', '季節のマーダーミステリー／ニィホン'),
    ('ぽん', '季節のマーダーミステリー／ニィホン'),
    ('みずき', '季節のマーダーミステリー／ニィホン'),
    ('りんな', '季節のマーダーミステリー／ニィホン'),
    ('れいにー', '季節のマーダーミステリー／ニィホン'),
    ('崎', '季節のマーダーミステリー／ニィホン'),
    ('松井（まつい）', '季節のマーダーミステリー／ニィホン'),
    ('labo', '季節マーダー／アニクシィ'),
    ('あんころ', '季節マーダー／アニクシィ'),
    ('しらやま', '季節マーダー／アニクシィ'),
    ('だいこん', '季節マーダー／アニクシィ'),
    ('ほがらか', '季節マーダー／アニクシィ'),
    ('みくみん', '季節マーダー／アニクシィ'),
    ('イワセモリシ', '季節マーダー／アニクシィ'),
    ('古賀', '季節マーダー／アニクシィ'),
    ('松井（まつい）', '季節マーダー／アニクシィ'),
    ('渚咲', '季節マーダー／アニクシィ'),
    ('藤崎ソルト', '季節マーダー／アニクシィ'),
    ('labo', '季節マーダー／カノケリ'),
    ('あんころ', '季節マーダー／カノケリ'),
    ('しらやま', '季節マーダー／カノケリ'),
    ('だいこん', '季節マーダー／カノケリ'),
    ('ほがらか', '季節マーダー／カノケリ'),
    ('みくみん', '季節マーダー／カノケリ'),
    ('松井（まつい）', '季節マーダー／カノケリ'),
    ('渚咲', '季節マーダー／カノケリ'),
    ('藤崎ソルト', '季節マーダー／カノケリ'),
    ('labo', '季節マーダー／キモナス'),
    ('しらやま', '季節マーダー／キモナス'),
    ('だいこん', '季節マーダー／キモナス'),
    ('つばめ', '季節マーダー／キモナス'),
    ('ほがらか', '季節マーダー／キモナス'),
    ('みくみん', '季節マーダー／キモナス'),
    ('松井（まつい）', '季節マーダー／キモナス'),
    ('だいこん', '季節マーダー／シノポロ'),
    ('つばめ', '季節マーダー／シノポロ'),
    ('イワセモリシ', '季節マーダー／シノポロ'),
    ('ソウタン', '季節マーダー／シノポロ'),
    ('松井（まつい）', '季節マーダー／シノポロ'),
    ('藤崎ソルト', '季節マーダー／シノポロ'),
    ('Remia（れみあ）', '学校の解談'),
    ('labo', '学校の解談'),
    ('あんころ', '学校の解談'),
    ('きゅう', '学校の解談'),
    ('つばめ', '学校の解談'),
    ('ぴよな', '学校の解談'),
    ('ほがらか', '学校の解談'),
    ('ぽったー', '学校の解談'),
    ('ぽん', '学校の解談'),
    ('みくみん', '学校の解談'),
    ('りんな', '学校の解談'),
    ('れいにー', '学校の解談'),
    ('ソラ', '学校の解談'),
    ('松井（まつい）', '学校の解談'),
    ('えりん', '小暮事件に関する考察'),
    ('ほがらか', '小暮事件に関する考察'),
    ('ぽったー', '小暮事件に関する考察'),
    ('ぽん', '小暮事件に関する考察'),
    ('みずき', '小暮事件に関する考察'),
    ('れいにー', '小暮事件に関する考察'),
    ('古賀', '小暮事件に関する考察'),
    ('温風リン', '小暮事件に関する考察'),
    ('Remia（れみあ）', '少年少女Aの独白'),
    ('kanade', '少年少女Aの独白'),
    ('えりん', '少年少女Aの独白'),
    ('きゅう', '少年少女Aの独白'),
    ('しらやま', '少年少女Aの独白'),
    ('つばめ', '少年少女Aの独白'),
    ('ほがらか', '少年少女Aの独白'),
    ('ぽったー', '少年少女Aの独白'),
    ('ぽん', '少年少女Aの独白'),
    ('ミカノハ', '少年少女Aの独白'),
    ('奏兎', '少年少女Aの独白'),
    ('松井（まつい）', '少年少女Aの独白'),
    ('labo', '岐路に降り立つ')
) AS ep(staff_name, scenario_title)
JOIN staff s ON s.name = ep.staff_name
JOIN scenarios sc ON sc.title = ep.scenario_title
ON CONFLICT (staff_id, scenario_id)
DO UPDATE SET
  can_main_gm = false,
  can_sub_gm = false,
  is_experienced = true;

-- ===========================================
-- STEP 2-7: 体験済み復元 (901~1050/1577)
-- ===========================================
INSERT INTO staff_scenario_assignments (staff_id, scenario_id, can_main_gm, can_sub_gm, is_experienced, can_gm_at)
SELECT s.id, sc.id, false, false, true, NOW()
FROM (VALUES
    ('えりん', '岐路に降り立つ'),
    ('つばめ', '岐路に降り立つ'),
    ('ほがらか', '岐路に降り立つ'),
    ('ぽったー', '岐路に降り立つ'),
    ('ぽん', '岐路に降り立つ'),
    ('みずき', '岐路に降り立つ'),
    ('りえぞー', '岐路に降り立つ'),
    ('れいにー', '岐路に降り立つ'),
    ('イワセモリシ', '岐路に降り立つ'),
    ('ソラ', '岐路に降り立つ'),
    ('Remia（れみあ）', '幻想のマリス'),
    ('kanade', '幻想のマリス'),
    ('labo', '幻想のマリス'),
    ('えりん', '幻想のマリス'),
    ('ほがらか', '幻想のマリス'),
    ('みくみん', '幻想のマリス'),
    ('りえぞー', '幻想のマリス'),
    ('松井（まつい）', '幻想のマリス'),
    ('Remia（れみあ）', '廻る弾丸輪舞（ダンガンロンド）'),
    ('あんころ', '廻る弾丸輪舞（ダンガンロンド）'),
    ('えりん', '廻る弾丸輪舞（ダンガンロンド）'),
    ('八継じの', '廻る弾丸輪舞（ダンガンロンド）'),
    ('崎', '廻る弾丸輪舞（ダンガンロンド）'),
    ('えりん', '彗星蘭の万朶'),
    ('きゅう', '彗星蘭の万朶'),
    ('だいこん', '彗星蘭の万朶'),
    ('ほがらか', '彗星蘭の万朶'),
    ('みずき', '彗星蘭の万朶'),
    ('れいにー', '彗星蘭の万朶'),
    ('ソウタン', '彗星蘭の万朶'),
    ('崎', '彗星蘭の万朶'),
    ('松井（まつい）', '彗星蘭の万朶'),
    ('江波（えなみん）', '彗星蘭の万朶'),
    ('温風リン', '彗星蘭の万朶'),
    ('labo', '彼とかじつとマシュマロウ'),
    ('えりん', '彼とかじつとマシュマロウ'),
    ('ぴよな', '彼とかじつとマシュマロウ'),
    ('ほがらか', '彼とかじつとマシュマロウ'),
    ('みくみん', '彼とかじつとマシュマロウ'),
    ('れいにー', '彼とかじつとマシュマロウ'),
    ('ソウタン', '彼とかじつとマシュマロウ'),
    ('松井（まつい）', '彼とかじつとマシュマロウ'),
    ('江波（えなみん）', '彼とかじつとマシュマロウ'),
    ('labo', '彼女といるかとチョコレート'),
    ('きゅう', '彼女といるかとチョコレート'),
    ('つばめ', '彼女といるかとチョコレート'),
    ('ほがらか', '彼女といるかとチョコレート'),
    ('みくみん', '彼女といるかとチョコレート'),
    ('みずき', '彼女といるかとチョコレート'),
    ('れいにー', '彼女といるかとチョコレート'),
    ('松井（まつい）', '彼女といるかとチョコレート'),
    ('江波（えなみん）', '彼女といるかとチョコレート'),
    ('Remia（れみあ）', '悪意の岐路に立つ'),
    ('labo', '悪意の岐路に立つ'),
    ('えりん', '悪意の岐路に立つ'),
    ('きゅう', '悪意の岐路に立つ'),
    ('ほがらか', '悪意の岐路に立つ'),
    ('ぽったー', '悪意の岐路に立つ'),
    ('ぽん', '悪意の岐路に立つ'),
    ('みずき', '悪意の岐路に立つ'),
    ('れいにー', '悪意の岐路に立つ'),
    ('Remia（れみあ）', '想いは満天の星に'),
    ('labo', '想いは満天の星に'),
    ('えりん', '想いは満天の星に'),
    ('きゅう', '想いは満天の星に'),
    ('だいこん', '想いは満天の星に'),
    ('みずき', '想いは満天の星に'),
    ('りえぞー', '想いは満天の星に'),
    ('れいにー', '想いは満天の星に'),
    ('古賀', '想いは満天の星に'),
    ('松井（まつい）', '想いは満天の星に'),
    ('江波（えなみん）', '想いは満天の星に'),
    ('labo', '愛する故に'),
    ('あんころ', '愛する故に'),
    ('えりん', '愛する故に'),
    ('きゅう', '愛する故に'),
    ('ほがらか', '愛する故に'),
    ('ぽったー', '愛する故に'),
    ('ぽん', '愛する故に'),
    ('ソウタン', '愛する故に'),
    ('ミカノハ', '愛する故に'),
    ('崎', '愛する故に'),
    ('江波（えなみん）', '愛する故に'),
    ('labo', '或ル胡蝶ノ夢'),
    ('だいこん', '或ル胡蝶ノ夢'),
    ('つばめ', '或ル胡蝶ノ夢'),
    ('ぴよな', '或ル胡蝶ノ夢'),
    ('ほがらか', '或ル胡蝶ノ夢'),
    ('ぽったー', '或ル胡蝶ノ夢'),
    ('れいにー', '或ル胡蝶ノ夢'),
    ('ミカノハ', '或ル胡蝶ノ夢'),
    ('八継じの', '或ル胡蝶ノ夢'),
    ('古賀', '或ル胡蝶ノ夢'),
    ('江波（えなみん）', '或ル胡蝶ノ夢'),
    ('BB', '探ぱんマーダーミステリー・ノーショーツトルダム学園殺人事件'),
    ('Remia（れみあ）', '探ぱんマーダーミステリー・ノーショーツトルダム学園殺人事件'),
    ('あんころ', '探ぱんマーダーミステリー・ノーショーツトルダム学園殺人事件'),
    ('きゅう', '探ぱんマーダーミステリー・ノーショーツトルダム学園殺人事件'),
    ('ぽったー', '探ぱんマーダーミステリー・ノーショーツトルダム学園殺人事件'),
    ('らの', '探ぱんマーダーミステリー・ノーショーツトルダム学園殺人事件'),
    ('りんな', '探ぱんマーダーミステリー・ノーショーツトルダム学園殺人事件'),
    ('ミカノハ', '探ぱんマーダーミステリー・ノーショーツトルダム学園殺人事件'),
    ('藤崎ソルト', '探ぱんマーダーミステリー・ノーショーツトルダム学園殺人事件'),
    ('Remia（れみあ）', '探偵撲滅'),
    ('labo', '探偵撲滅'),
    ('えりん', '探偵撲滅'),
    ('きゅう', '探偵撲滅'),
    ('つばめ', '探偵撲滅'),
    ('ほがらか', '探偵撲滅'),
    ('ぽん', '探偵撲滅'),
    ('りえぞー', '探偵撲滅'),
    ('れいにー', '探偵撲滅'),
    ('イワセモリシ', '探偵撲滅'),
    ('松井（まつい）', '探偵撲滅'),
    ('江波（えなみん）', '探偵撲滅'),
    ('Remia（れみあ）', '新世界のユキサキ'),
    ('だいこん', '新世界のユキサキ'),
    ('つばめ', '新世界のユキサキ'),
    ('ぽったー', '新世界のユキサキ'),
    ('あんころ', '星'),
    ('きゅう', '星'),
    ('つばめ', '星'),
    ('ぽん', '星'),
    ('江波（えなみん）', '星'),
    ('Remia（れみあ）', '星空のマリス'),
    ('kanade', '星空のマリス'),
    ('labo', '星空のマリス'),
    ('あんころ', '星空のマリス'),
    ('ほがらか', '星空のマリス'),
    ('ぽったー', '星空のマリス'),
    ('みくみん', '星空のマリス'),
    ('れいにー', '星空のマリス'),
    ('ソウタン', '星空のマリス'),
    ('ソラ', '星空のマリス'),
    ('ミカノハ', '星空のマリス'),
    ('古賀', '星空のマリス'),
    ('崎', '星空のマリス'),
    ('あんころ', '曙光のエテルナ'),
    ('りんな', '曙光のエテルナ'),
    ('温風リン', '曙光のエテルナ'),
    ('Remia（れみあ）', '月光の偽桜'),
    ('kanade', '月光の偽桜'),
    ('あんころ', '月光の偽桜'),
    ('えりん', '月光の偽桜'),
    ('きゅう', '月光の偽桜'),
    ('だいこん', '月光の偽桜'),
    ('ぽったー', '月光の偽桜'),
    ('りんな', '月光の偽桜'),
    ('イワセモリシ', '月光の偽桜'),
    ('八継じの', '月光の偽桜')
) AS ep(staff_name, scenario_title)
JOIN staff s ON s.name = ep.staff_name
JOIN scenarios sc ON sc.title = ep.scenario_title
ON CONFLICT (staff_id, scenario_id)
DO UPDATE SET
  can_main_gm = false,
  can_sub_gm = false,
  is_experienced = true;

-- ===========================================
-- STEP 2-8: 体験済み復元 (1051~1200/1577)
-- ===========================================
INSERT INTO staff_scenario_assignments (staff_id, scenario_id, can_main_gm, can_sub_gm, is_experienced, can_gm_at)
SELECT s.id, sc.id, false, false, true, NOW()
FROM (VALUES
    ('松井（まつい）', '月光の偽桜'),
    ('Remia（れみあ）', '朱き亡国に捧げる祈り'),
    ('labo', '朱き亡国に捧げる祈り'),
    ('えりん', '朱き亡国に捧げる祈り'),
    ('つばめ', '朱き亡国に捧げる祈り'),
    ('ほがらか', '朱き亡国に捧げる祈り'),
    ('ぽん', '朱き亡国に捧げる祈り'),
    ('みずき', '朱き亡国に捧げる祈り'),
    ('Remia（れみあ）', '椅子戦争'),
    ('えりん', '椅子戦争'),
    ('きゅう', '椅子戦争'),
    ('ぴよな', '椅子戦争'),
    ('ぽん', '椅子戦争'),
    ('れいにー', '椅子戦争'),
    ('江波（えなみん）', '椅子戦争'),
    ('labo', '機巧人形の心臓'),
    ('あんころ', '機巧人形の心臓'),
    ('えりん', '機巧人形の心臓'),
    ('だいこん', '機巧人形の心臓'),
    ('ぽったー', '機巧人形の心臓'),
    ('りんな', '機巧人形の心臓'),
    ('イワセモリシ', '機巧人形の心臓'),
    ('ソラ', '機巧人形の心臓'),
    ('ミカノハ', '機巧人形の心臓'),
    ('奏兎', '機巧人形の心臓'),
    ('温風リン', '機巧人形の心臓'),
    ('あんころ', '檻見る5人-（空色時箱セット公演）'),
    ('しらやま', '檻見る5人-（空色時箱セット公演）'),
    ('ぴよな', '檻見る5人-（空色時箱セット公演）'),
    ('りえぞー', '檻見る5人-（空色時箱セット公演）'),
    ('イワセモリシ', '檻見る5人-（空色時箱セット公演）'),
    ('八継じの', '檻見る5人-（空色時箱セット公演）'),
    ('きゅう', '正義はまた蘇る'),
    ('つばめ', '正義はまた蘇る'),
    ('ぽん', '正義はまた蘇る'),
    ('みずき', '正義はまた蘇る'),
    ('れいにー', '正義はまた蘇る'),
    ('labo', '歯に噛むあなたに'),
    ('えりん', '歯に噛むあなたに'),
    ('ぽったー', '歯に噛むあなたに'),
    ('みずき', '歯に噛むあなたに'),
    ('れいにー', '歯に噛むあなたに'),
    ('崎', '歯に噛むあなたに'),
    ('えりん', '殺人鬼Xの独白'),
    ('ほがらか', '殺人鬼Xの独白'),
    ('ぽったー', '殺人鬼Xの独白'),
    ('ぽん', '殺人鬼Xの独白'),
    ('みずき', '殺人鬼Xの独白'),
    ('イワセモリシ', '殺人鬼Xの独白'),
    ('ソラ', '殺人鬼Xの独白'),
    ('古賀', '殺人鬼Xの独白'),
    ('江波（えなみん）', '殺人鬼Xの独白'),
    ('Remia（れみあ）', '殺人鬼イバラノミチの回想録'),
    ('labo', '殺人鬼イバラノミチの回想録'),
    ('あんころ', '殺人鬼イバラノミチの回想録'),
    ('えりん', '殺人鬼イバラノミチの回想録'),
    ('しらやま', '殺人鬼イバラノミチの回想録'),
    ('ほがらか', '殺人鬼イバラノミチの回想録'),
    ('ソラ', '殺人鬼イバラノミチの回想録'),
    ('崎', '殺人鬼イバラノミチの回想録'),
    ('江波（えなみん）', '殺人鬼イバラノミチの回想録'),
    ('藤崎ソルト', '殺人鬼イバラノミチの回想録'),
    ('Remia（れみあ）', '殺神罪'),
    ('labo', '殺神罪'),
    ('あんころ', '殺神罪'),
    ('えりん', '殺神罪'),
    ('きゅう', '殺神罪'),
    ('だいこん', '殺神罪'),
    ('ぴよな', '殺神罪'),
    ('ほがらか', '殺神罪'),
    ('ぽん', '殺神罪'),
    ('れいにー', '殺神罪'),
    ('イワセモリシ', '殺神罪'),
    ('ソラ', '殺神罪'),
    ('八継じの', '殺神罪'),
    ('古賀', '殺神罪'),
    ('奏兎', '殺神罪'),
    ('崎', '殺神罪'),
    ('江波（えなみん）', '殺神罪'),
    ('Remia（れみあ）', '流年'),
    ('きゅう', '流年'),
    ('しらやま', '流年'),
    ('つばめ', '流年'),
    ('ぴよな', '流年'),
    ('ほがらか', '流年'),
    ('ぽん', '流年'),
    ('みずき', '流年'),
    ('ソウタン', '流年'),
    ('ミカノハ', '流年'),
    ('八継じの', '流年'),
    ('あんころ', '深海に沈む子供たち（水底に生きる）'),
    ('きゅう', '深海に沈む子供たち（水底に生きる）'),
    ('つばめ', '深海に沈む子供たち（水底に生きる）'),
    ('ぴよな', '深海に沈む子供たち（水底に生きる）'),
    ('ソラ', '深海に沈む子供たち（水底に生きる）'),
    ('藤崎ソルト', '深海に沈む子供たち（水底に生きる）'),
    ('Remia（れみあ）', '清流館の秘宝'),
    ('えりん', '清流館の秘宝'),
    ('きゅう', '清流館の秘宝'),
    ('つばめ', '清流館の秘宝'),
    ('ほがらか', '清流館の秘宝'),
    ('れいにー', '清流館の秘宝'),
    ('江波（えなみん）', '清流館の秘宝'),
    ('あんころ', '漣の向こう側'),
    ('ぽったー', '漣の向こう側'),
    ('りんな', '漣の向こう側'),
    ('Remia（れみあ）', '火ノ神様のいうとおり'),
    ('labo', '火ノ神様のいうとおり'),
    ('ほがらか', '火ノ神様のいうとおり'),
    ('みずき', '火ノ神様のいうとおり'),
    ('れいにー', '火ノ神様のいうとおり'),
    ('松井（まつい）', '火ノ神様のいうとおり'),
    ('あんころ', '燔祭のジェミニ'),
    ('きゅう', '燔祭のジェミニ'),
    ('だいこん', '燔祭のジェミニ'),
    ('みずき', '燔祭のジェミニ'),
    ('れいにー', '燔祭のジェミニ'),
    ('ソラ', '燔祭のジェミニ'),
    ('ミカノハ', '燔祭のジェミニ'),
    ('松井（まつい）', '燔祭のジェミニ'),
    ('しらやま', '狂気山脈　2.5　頂上戦争'),
    ('だいこん', '狂気山脈　2.5　頂上戦争'),
    ('みずき', '狂気山脈　2.5　頂上戦争'),
    ('ソウタン', '狂気山脈　2.5　頂上戦争'),
    ('崎', '狂気山脈　2.5　頂上戦争'),
    ('江波（えなみん）', '狂気山脈　2.5　頂上戦争'),
    ('kanade', '狂気山脈　星降る天辺（２）'),
    ('labo', '狂気山脈　星降る天辺（２）'),
    ('あんころ', '狂気山脈　星降る天辺（２）'),
    ('えりん', '狂気山脈　星降る天辺（２）'),
    ('しらやま', '狂気山脈　星降る天辺（２）'),
    ('だいこん', '狂気山脈　星降る天辺（２）'),
    ('ぽったー', '狂気山脈　星降る天辺（２）'),
    ('みずき', '狂気山脈　星降る天辺（２）'),
    ('りえぞー', '狂気山脈　星降る天辺（２）'),
    ('ソウタン', '狂気山脈　星降る天辺（２）'),
    ('ソラ', '狂気山脈　星降る天辺（２）'),
    ('ミカノハ', '狂気山脈　星降る天辺（２）'),
    ('奏兎', '狂気山脈　星降る天辺（２）'),
    ('崎', '狂気山脈　星降る天辺（２）'),
    ('松井（まつい）', '狂気山脈　星降る天辺（２）'),
    ('江波（えなみん）', '狂気山脈　星降る天辺（２）'),
    ('labo', '狂気山脈　薄明三角点（３）'),
    ('あんころ', '狂気山脈　薄明三角点（３）'),
    ('えりん', '狂気山脈　薄明三角点（３）'),
    ('しらやま', '狂気山脈　薄明三角点（３）'),
    ('だいこん', '狂気山脈　薄明三角点（３）'),
    ('ぽったー', '狂気山脈　薄明三角点（３）'),
    ('みずき', '狂気山脈　薄明三角点（３）'),
    ('りえぞー', '狂気山脈　薄明三角点（３）')
) AS ep(staff_name, scenario_title)
JOIN staff s ON s.name = ep.staff_name
JOIN scenarios sc ON sc.title = ep.scenario_title
ON CONFLICT (staff_id, scenario_id)
DO UPDATE SET
  can_main_gm = false,
  can_sub_gm = false,
  is_experienced = true;

-- ===========================================
-- STEP 2-9: 体験済み復元 (1201~1350/1577)
-- ===========================================
INSERT INTO staff_scenario_assignments (staff_id, scenario_id, can_main_gm, can_sub_gm, is_experienced, can_gm_at)
SELECT s.id, sc.id, false, false, true, NOW()
FROM (VALUES
    ('ソウタン', '狂気山脈　薄明三角点（３）'),
    ('ミカノハ', '狂気山脈　薄明三角点（３）'),
    ('奏兎', '狂気山脈　薄明三角点（３）'),
    ('崎', '狂気山脈　薄明三角点（３）'),
    ('江波（えなみん）', '狂気山脈　薄明三角点（３）'),
    ('kanade', '狂気山脈　陰謀の分水嶺（１）'),
    ('labo', '狂気山脈　陰謀の分水嶺（１）'),
    ('あんころ', '狂気山脈　陰謀の分水嶺（１）'),
    ('えりん', '狂気山脈　陰謀の分水嶺（１）'),
    ('しらやま', '狂気山脈　陰謀の分水嶺（１）'),
    ('だいこん', '狂気山脈　陰謀の分水嶺（１）'),
    ('つばめ', '狂気山脈　陰謀の分水嶺（１）'),
    ('ぴよな', '狂気山脈　陰謀の分水嶺（１）'),
    ('ほがらか', '狂気山脈　陰謀の分水嶺（１）'),
    ('ぽったー', '狂気山脈　陰謀の分水嶺（１）'),
    ('ぽん', '狂気山脈　陰謀の分水嶺（１）'),
    ('みずき', '狂気山脈　陰謀の分水嶺（１）'),
    ('りえぞー', '狂気山脈　陰謀の分水嶺（１）'),
    ('ソウタン', '狂気山脈　陰謀の分水嶺（１）'),
    ('ソラ', '狂気山脈　陰謀の分水嶺（１）'),
    ('ミカノハ', '狂気山脈　陰謀の分水嶺（１）'),
    ('古賀', '狂気山脈　陰謀の分水嶺（１）'),
    ('奏兎', '狂気山脈　陰謀の分水嶺（１）'),
    ('崎', '狂気山脈　陰謀の分水嶺（１）'),
    ('松井（まつい）', '狂気山脈　陰謀の分水嶺（１）'),
    ('江波（えなみん）', '狂気山脈　陰謀の分水嶺（１）'),
    ('渚咲', '狂気山脈　陰謀の分水嶺（１）'),
    ('えりん', '異能特区シンギュラリティ'),
    ('きゅう', '異能特区シンギュラリティ'),
    ('つばめ', '異能特区シンギュラリティ'),
    ('ぴよな', '異能特区シンギュラリティ'),
    ('ぽったー', '異能特区シンギュラリティ'),
    ('イワセモリシ', '異能特区シンギュラリティ'),
    ('八継じの', '異能特区シンギュラリティ'),
    ('崎', '異能特区シンギュラリティ'),
    ('松井（まつい）', '異能特区シンギュラリティ'),
    ('温風リン', '異能特区シンギュラリティ'),
    ('Remia（れみあ）', '白殺しType-K'),
    ('あんころ', '白殺しType-K'),
    ('つばめ', '白殺しType-K'),
    ('ぴよな', '白殺しType-K'),
    ('ほがらか', '白殺しType-K'),
    ('ぽったー', '白殺しType-K'),
    ('みずき', '白殺しType-K'),
    ('りえぞー', '白殺しType-K'),
    ('りんな', '白殺しType-K'),
    ('れいにー', '白殺しType-K'),
    ('八継じの', '白殺しType-K'),
    ('崎', '白殺しType-K'),
    ('松井（まつい）', '白殺しType-K'),
    ('江波（えなみん）', '白殺しType-K'),
    ('Remia（れみあ）', '百鬼の夜、月光の影'),
    ('あんころ', '百鬼の夜、月光の影'),
    ('えりん', '百鬼の夜、月光の影'),
    ('つばめ', '百鬼の夜、月光の影'),
    ('ぴよな', '百鬼の夜、月光の影'),
    ('ぽったー', '百鬼の夜、月光の影'),
    ('ぽん', '百鬼の夜、月光の影'),
    ('れいにー', '百鬼の夜、月光の影'),
    ('イワセモリシ', '百鬼の夜、月光の影'),
    ('ソラ', '百鬼の夜、月光の影'),
    ('ミカノハ', '百鬼の夜、月光の影'),
    ('八継じの', '百鬼の夜、月光の影'),
    ('古賀', '百鬼の夜、月光の影'),
    ('松井（まつい）', '百鬼の夜、月光の影'),
    ('江波（えなみん）', '百鬼の夜、月光の影'),
    ('kanade', '真・渋谷陰陽奇譚'),
    ('あんころ', '真・渋谷陰陽奇譚'),
    ('しらやま', '真・渋谷陰陽奇譚'),
    ('あんころ', '空色時箱（ソライロタイムカプセル）-檻見る５人セット公演'),
    ('しらやま', '空色時箱（ソライロタイムカプセル）-檻見る５人セット公演'),
    ('りえぞー', '空色時箱（ソライロタイムカプセル）-檻見る５人セット公演'),
    ('イワセモリシ', '空色時箱（ソライロタイムカプセル）-檻見る５人セット公演'),
    ('八継じの', '空色時箱（ソライロタイムカプセル）-檻見る５人セット公演'),
    ('江波（えなみん）', '空色時箱（ソライロタイムカプセル）-檻見る５人セット公演'),
    ('えりん', '立方館'),
    ('きゅう', '立方館'),
    ('しらやま', '立方館'),
    ('だいこん', '立方館'),
    ('つばめ', '立方館'),
    ('崎', '立方館'),
    ('温風リン', '立方館'),
    ('藤崎ソルト', '立方館'),
    ('Remia（れみあ）', '紅く舞う'),
    ('labo', '紅く舞う'),
    ('えりん', '紅く舞う'),
    ('つばめ', '紅く舞う'),
    ('ほがらか', '紅く舞う'),
    ('みずき', '紅く舞う'),
    ('れいにー', '紅く舞う'),
    ('江波（えなみん）', '紅く舞う'),
    ('Remia（れみあ）', '紫に染まる前に'),
    ('きゅう', '紫に染まる前に'),
    ('しらやま', '紫に染まる前に'),
    ('つばめ', '紫に染まる前に'),
    ('ぽん', '紫に染まる前に'),
    ('みくみん', '紫に染まる前に'),
    ('みずき', '紫に染まる前に'),
    ('れいにー', '紫に染まる前に'),
    ('江波（えなみん）', '紫に染まる前に'),
    ('Remia（れみあ）', '絆の永逝'),
    ('kanade', '絆の永逝'),
    ('あんころ', '絆の永逝'),
    ('えりん', '絆の永逝'),
    ('しらやま', '絆の永逝'),
    ('つばめ', '絆の永逝'),
    ('ほがらか', '絆の永逝'),
    ('みずき', '絆の永逝'),
    ('りえぞー', '絆の永逝'),
    ('れいにー', '絆の永逝'),
    ('ミカノハ', '絆の永逝'),
    ('奏兎', '絆の永逝'),
    ('松井（まつい）', '絆の永逝'),
    ('江波（えなみん）', '絆の永逝'),
    ('Remia（れみあ）', '花咲の箱庭'),
    ('ぽん', '花咲の箱庭'),
    ('松井（まつい）', '花咲の箱庭'),
    ('江波（えなみん）', '花咲の箱庭'),
    ('つばめ', '花街リグレット'),
    ('ぽったー', '花街リグレット'),
    ('ぽん', '花街リグレット'),
    ('りんな', '花街リグレット'),
    ('れいにー', '花街リグレット'),
    ('ソウタン', '花街リグレット'),
    ('ソラ', '花街リグレット'),
    ('江波（えなみん）', '花街リグレット'),
    ('藤崎ソルト', '花街リグレット'),
    ('kanade', '荒廃のマリス'),
    ('labo', '荒廃のマリス'),
    ('あんころ', '荒廃のマリス'),
    ('ほがらか', '荒廃のマリス'),
    ('れいにー', '荒廃のマリス'),
    ('ソウタン', '荒廃のマリス'),
    ('崎', '荒廃のマリス'),
    ('Remia（れみあ）', '藍雨廻逢'),
    ('kanade', '藍雨廻逢'),
    ('あんころ', '藍雨廻逢'),
    ('えりん', '藍雨廻逢'),
    ('渚咲', '藍雨廻逢'),
    ('温風リン', '藍雨廻逢'),
    ('labo', '蝉散'),
    ('えりん', '蝉散'),
    ('みずき', '蝉散'),
    ('りんな', '蝉散'),
    ('labo', '蟻集'),
    ('えりん', '蟻集'),
    ('しらやま', '蟻集'),
    ('だいこん', '蟻集'),
    ('つばめ', '蟻集'),
    ('みずき', '蟻集')
) AS ep(staff_name, scenario_title)
JOIN staff s ON s.name = ep.staff_name
JOIN scenarios sc ON sc.title = ep.scenario_title
ON CONFLICT (staff_id, scenario_id)
DO UPDATE SET
  can_main_gm = false,
  can_sub_gm = false,
  is_experienced = true;

-- ===========================================
-- STEP 2-10: 体験済み復元 (1351~1500/1577)
-- ===========================================
INSERT INTO staff_scenario_assignments (staff_id, scenario_id, can_main_gm, can_sub_gm, is_experienced, can_gm_at)
SELECT s.id, sc.id, false, false, true, NOW()
FROM (VALUES
    ('りんな', '蟻集'),
    ('Remia（れみあ）', '裁くもの、裁かれるもの'),
    ('labo', '裁くもの、裁かれるもの'),
    ('あんころ', '裁くもの、裁かれるもの'),
    ('えりん', '裁くもの、裁かれるもの'),
    ('しらやま', '裁くもの、裁かれるもの'),
    ('だいこん', '裁くもの、裁かれるもの'),
    ('つばめ', '裁くもの、裁かれるもの'),
    ('ぴよな', '裁くもの、裁かれるもの'),
    ('ほがらか', '裁くもの、裁かれるもの'),
    ('ぽったー', '裁くもの、裁かれるもの'),
    ('ぽん', '裁くもの、裁かれるもの'),
    ('みずき', '裁くもの、裁かれるもの'),
    ('イワセモリシ', '裁くもの、裁かれるもの'),
    ('ソラ', '裁くもの、裁かれるもの'),
    ('八継じの', '裁くもの、裁かれるもの'),
    ('崎', '裁くもの、裁かれるもの'),
    ('松井（まつい）', '裁くもの、裁かれるもの'),
    ('Remia（れみあ）', '裁判員の仮面'),
    ('きゅう', '裁判員の仮面'),
    ('ほがらか', '裁判員の仮面'),
    ('ぽったー', '裁判員の仮面'),
    ('ぽん', '裁判員の仮面'),
    ('れいにー', '裁判員の仮面'),
    ('八継じの', '裁判員の仮面'),
    ('Remia（れみあ）', '裂き子さん'),
    ('あんころ', '裂き子さん'),
    ('えりん', '裂き子さん'),
    ('しらやま', '裂き子さん'),
    ('ほがらか', '裂き子さん'),
    ('ぽったー', '裂き子さん'),
    ('みくみん', '裂き子さん'),
    ('れいにー', '裂き子さん'),
    ('八継じの', '裂き子さん'),
    ('松井（まつい）', '裂き子さん'),
    ('江波（えなみん）', '裂き子さん'),
    ('あんころ', '親方の館'),
    ('きゅう', '親方の館'),
    ('ぴよな', '親方の館'),
    ('ソラ', '親方の館'),
    ('ミカノハ', '親方の館'),
    ('Remia（れみあ）', '誠実な十字架'),
    ('あんころ', '誠実な十字架'),
    ('えりん', '誠実な十字架'),
    ('だいこん', '誠実な十字架'),
    ('ほがらか', '誠実な十字架'),
    ('ぽったー', '誠実な十字架'),
    ('ぽん', '誠実な十字架'),
    ('りんな', '誠実な十字架'),
    ('れいにー', '誠実な十字架'),
    ('イワセモリシ', '誠実な十字架'),
    ('ソラ', '誠実な十字架'),
    ('松井（まつい）', '誠実な十字架'),
    ('藤崎ソルト', '誠実な十字架'),
    ('Remia（れみあ）', '贖罪のロザリオ'),
    ('えりん', '贖罪のロザリオ'),
    ('きゅう', '贖罪のロザリオ'),
    ('つばめ', '贖罪のロザリオ'),
    ('れいにー', '贖罪のロザリオ'),
    ('ソラ', '贖罪のロザリオ'),
    ('江波（えなみん）', '贖罪のロザリオ'),
    ('Remia（れみあ）', '赤の導線'),
    ('あんころ', '赤の導線'),
    ('きゅう', '赤の導線'),
    ('だいこん', '赤の導線'),
    ('つばめ', '赤の導線'),
    ('ぽったー', '赤の導線'),
    ('ぽん', '赤の導線'),
    ('みずき', '赤の導線'),
    ('りんな', '赤の導線'),
    ('ソラ', '赤の導線'),
    ('八継じの', '赤の導線'),
    ('古賀', '赤の導線'),
    ('崎', '赤の導線'),
    ('温風リン', '赤の導線'),
    ('藤崎ソルト', '赤の導線'),
    ('あんころ', '赤鬼が泣いた夜'),
    ('ぴよな', '赤鬼が泣いた夜'),
    ('ソラ', '赤鬼が泣いた夜'),
    ('八継じの', '赤鬼が泣いた夜'),
    ('松井（まつい）', '赤鬼が泣いた夜'),
    ('kanade', '超特急の呪いの館で撮れ高足りてますか？'),
    ('つばめ', '超特急の呪いの館で撮れ高足りてますか？'),
    ('ぽったー', '超特急の呪いの館で撮れ高足りてますか？'),
    ('りんな', '超特急の呪いの館で撮れ高足りてますか？'),
    ('八継じの', '超特急の呪いの館で撮れ高足りてますか？'),
    ('松井（まつい）', '超特急の呪いの館で撮れ高足りてますか？'),
    ('Remia（れみあ）', '違人'),
    ('あんころ', '違人'),
    ('えりん', '違人'),
    ('ぽったー', '違人'),
    ('ぽん', '違人'),
    ('みずき', '違人'),
    ('りんな', '違人'),
    ('れいにー', '違人'),
    ('八継じの', '違人'),
    ('古賀', '違人'),
    ('松井（まつい）', '違人'),
    ('江波（えなみん）', '違人'),
    ('Remia（れみあ）', '野槌'),
    ('ほがらか', '野槌'),
    ('りえぞー', '野槌'),
    ('れいにー', '野槌'),
    ('松井（まつい）', '野槌'),
    ('江波（えなみん）', '野槌'),
    ('Remia（れみあ）', '鉄紺の証言'),
    ('labo', '鉄紺の証言'),
    ('ほがらか', '鉄紺の証言'),
    ('ぽったー', '鉄紺の証言'),
    ('ぽん', '鉄紺の証言'),
    ('りんな', '鉄紺の証言'),
    ('れいにー', '鉄紺の証言'),
    ('イワセモリシ', '鉄紺の証言'),
    ('ソラ', '鉄紺の証言'),
    ('松井（まつい）', '鉄紺の証言'),
    ('Remia（れみあ）', '銀世界のアシアト(５月まで）'),
    ('labo', '銀世界のアシアト(５月まで）'),
    ('あんころ', '銀世界のアシアト(５月まで）'),
    ('えりん', '銀世界のアシアト(５月まで）'),
    ('だいこん', '銀世界のアシアト(５月まで）'),
    ('つばめ', '銀世界のアシアト(５月まで）'),
    ('ほがらか', '銀世界のアシアト(５月まで）'),
    ('ぽったー', '銀世界のアシアト(５月まで）'),
    ('みずき', '銀世界のアシアト(５月まで）'),
    ('れいにー', '銀世界のアシアト(５月まで）'),
    ('イワセモリシ', '銀世界のアシアト(５月まで）'),
    ('ソウタン', '銀世界のアシアト(５月まで）'),
    ('ミカノハ', '銀世界のアシアト(５月まで）'),
    ('八継じの', '銀世界のアシアト(５月まで）'),
    ('Remia（れみあ）', '電脳の檻のアリス'),
    ('あんころ', '電脳の檻のアリス'),
    ('きゅう', '電脳の檻のアリス'),
    ('しらやま', '電脳の檻のアリス'),
    ('つばめ', '電脳の檻のアリス'),
    ('みずき', '電脳の檻のアリス'),
    ('りんな', '電脳の檻のアリス'),
    ('れいにー', '電脳の檻のアリス'),
    ('イワセモリシ', '電脳の檻のアリス'),
    ('ソラ', '電脳の檻のアリス'),
    ('ミカノハ', '電脳の檻のアリス'),
    ('江波（えなみん）', '電脳の檻のアリス'),
    ('labo', '霧に眠るは幾つの罪'),
    ('あんころ', '霧に眠るは幾つの罪'),
    ('えりん', '霧に眠るは幾つの罪'),
    ('だいこん', '霧に眠るは幾つの罪'),
    ('つばめ', '霧に眠るは幾つの罪'),
    ('ほがらか', '霧に眠るは幾つの罪'),
    ('ぽん', '霧に眠るは幾つの罪'),
    ('みずき', '霧に眠るは幾つの罪'),
    ('りえぞー', '霧に眠るは幾つの罪')
) AS ep(staff_name, scenario_title)
JOIN staff s ON s.name = ep.staff_name
JOIN scenarios sc ON sc.title = ep.scenario_title
ON CONFLICT (staff_id, scenario_id)
DO UPDATE SET
  can_main_gm = false,
  can_sub_gm = false,
  is_experienced = true;

-- ===========================================
-- STEP 2-11: 体験済み復元 (1501~1577/1577)
-- ===========================================
INSERT INTO staff_scenario_assignments (staff_id, scenario_id, can_main_gm, can_sub_gm, is_experienced, can_gm_at)
SELECT s.id, sc.id, false, false, true, NOW()
FROM (VALUES
    ('ソラ', '霧に眠るは幾つの罪'),
    ('藤崎ソルト', '霧に眠るは幾つの罪'),
    ('Remia（れみあ）', '鬼哭館の殺人事件'),
    ('labo', '鬼哭館の殺人事件'),
    ('あんころ', '鬼哭館の殺人事件'),
    ('えりん', '鬼哭館の殺人事件'),
    ('きゅう', '鬼哭館の殺人事件'),
    ('だいこん', '鬼哭館の殺人事件'),
    ('つばめ', '鬼哭館の殺人事件'),
    ('ぴよな', '鬼哭館の殺人事件'),
    ('ほがらか', '鬼哭館の殺人事件'),
    ('ぽったー', '鬼哭館の殺人事件'),
    ('ぽん', '鬼哭館の殺人事件'),
    ('りえぞー', '鬼哭館の殺人事件'),
    ('りんな', '鬼哭館の殺人事件'),
    ('イワセモリシ', '鬼哭館の殺人事件'),
    ('ミカノハ', '鬼哭館の殺人事件'),
    ('八継じの', '鬼哭館の殺人事件'),
    ('奏兎', '鬼哭館の殺人事件'),
    ('崎', '鬼哭館の殺人事件'),
    ('江波（えなみん）', '鬼哭館の殺人事件'),
    ('藤崎ソルト', '鬼哭館の殺人事件'),
    ('奏兎', '魂を運ぶ飛行船'),
    ('Remia（れみあ）', '魔女の聖餐式'),
    ('えりん', '魔女の聖餐式'),
    ('きゅう', '魔女の聖餐式'),
    ('だいこん', '魔女の聖餐式'),
    ('ぽん', '魔女の聖餐式'),
    ('れいにー', '魔女の聖餐式'),
    ('古賀', '魔女の聖餐式'),
    ('松井（まつい）', '魔女の聖餐式'),
    ('Remia（れみあ）', '鳴神様のいうとおり'),
    ('labo', '鳴神様のいうとおり'),
    ('つばめ', '鳴神様のいうとおり'),
    ('ほがらか', '鳴神様のいうとおり'),
    ('みずき', '鳴神様のいうとおり'),
    ('れいにー', '鳴神様のいうとおり'),
    ('ソウタン', '鳴神様のいうとおり'),
    ('松井（まつい）', '鳴神様のいうとおり'),
    ('渚咲', '鳴神様のいうとおり'),
    ('Remia（れみあ）', '鹿神館の罪人'),
    ('きゅう', '鹿神館の罪人'),
    ('ほがらか', '鹿神館の罪人'),
    ('ぽん', '鹿神館の罪人'),
    ('れいにー', '鹿神館の罪人'),
    ('きゅう', '黒い森の獣part1'),
    ('だいこん', '黒い森の獣part1'),
    ('ほがらか', '黒い森の獣part1'),
    ('ぽん', '黒い森の獣part1'),
    ('りえぞー', '黒い森の獣part1'),
    ('ソラ', '黒い森の獣part1'),
    ('古賀', '黒い森の獣part1'),
    ('江波（えなみん）', '黒い森の獣part1'),
    ('Remia（れみあ）', '黒い森の獣part2人と狼'),
    ('きゅう', '黒い森の獣part2人と狼'),
    ('だいこん', '黒い森の獣part2人と狼'),
    ('ほがらか', '黒い森の獣part2人と狼'),
    ('みずき', '黒い森の獣part2人と狼'),
    ('ソラ', '黒い森の獣part2人と狼'),
    ('古賀', '黒い森の獣part2人と狼'),
    ('江波（えなみん）', '黒い森の獣part2人と狼'),
    ('きゅう', '黒と白の狭間に'),
    ('ほがらか', '黒と白の狭間に'),
    ('ぽん', '黒と白の狭間に'),
    ('みくみん', '黒と白の狭間に'),
    ('みずき', '黒と白の狭間に'),
    ('りえぞー', '黒と白の狭間に'),
    ('れいにー', '黒と白の狭間に'),
    ('ソウタン', '黒と白の狭間に'),
    ('八継じの', '黒と白の狭間に'),
    ('古賀', '黒と白の狭間に'),
    ('松井（まつい）', '黒と白の狭間に'),
    ('Remia（れみあ）', '黒の眺望'),
    ('きゅう', '黒の眺望'),
    ('つばめ', '黒の眺望'),
    ('れいにー', '黒の眺望'),
    ('江波（えなみん）', '黒の眺望')
) AS ep(staff_name, scenario_title)
JOIN staff s ON s.name = ep.staff_name
JOIN scenarios sc ON sc.title = ep.scenario_title
ON CONFLICT (staff_id, scenario_id)
DO UPDATE SET
  can_main_gm = false,
  can_sub_gm = false,
  is_experienced = true;

-- ===========================================
-- STEP 3: organization_scenarios.available_gms 再構築
-- ===========================================
WITH gm_via_scenarios AS (
  SELECT s.scenario_master_id, s.organization_id, st.name
  FROM staff_scenario_assignments ssa
  JOIN scenarios s ON s.id = ssa.scenario_id
  JOIN staff st ON st.id = ssa.staff_id
  WHERE (ssa.can_main_gm = true OR ssa.can_sub_gm = true)
    AND s.scenario_master_id IS NOT NULL
    AND st.name IS NOT NULL AND st.name != ''
),
gm_via_masters AS (
  SELECT ssa.scenario_id AS scenario_master_id, os.organization_id, st.name
  FROM staff_scenario_assignments ssa
  JOIN staff st ON st.id = ssa.staff_id
  JOIN organization_scenarios os ON os.scenario_master_id = ssa.scenario_id
  WHERE (ssa.can_main_gm = true OR ssa.can_sub_gm = true)
    AND ssa.scenario_id IN (SELECT id FROM scenario_masters)
    AND st.name IS NOT NULL AND st.name != ''
),
gm_via_title AS (
  SELECT sm.id AS scenario_master_id, os.organization_id, st.name
  FROM staff_scenario_assignments ssa
  JOIN staff st ON st.id = ssa.staff_id
  JOIN scenarios s ON s.id = ssa.scenario_id
  JOIN scenario_masters sm ON sm.title = s.title
  JOIN organization_scenarios os ON os.scenario_master_id = sm.id
  WHERE (ssa.can_main_gm = true OR ssa.can_sub_gm = true)
    AND st.name IS NOT NULL AND st.name != ''
),
gm_from_old_scenarios AS (
  SELECT s.scenario_master_id, s.organization_id, unnest(s.available_gms) as name
  FROM scenarios s
  WHERE s.scenario_master_id IS NOT NULL
    AND s.available_gms IS NOT NULL AND array_length(s.available_gms, 1) > 0
),
all_gms AS (
  SELECT scenario_master_id, organization_id, name FROM gm_via_scenarios
  UNION
  SELECT scenario_master_id, organization_id, name FROM gm_via_masters
  UNION
  SELECT scenario_master_id, organization_id, name FROM gm_via_title
  UNION
  SELECT scenario_master_id, organization_id, name FROM gm_from_old_scenarios
),
merged_gms AS (
  SELECT scenario_master_id, organization_id,
    ARRAY_AGG(DISTINCT name ORDER BY name) AS gm_list
  FROM all_gms
  WHERE name IS NOT NULL AND name != ''
  GROUP BY scenario_master_id, organization_id
)
UPDATE organization_scenarios os
SET available_gms = mg.gm_list, updated_at = NOW()
FROM merged_gms mg
WHERE os.scenario_master_id = mg.scenario_master_id
  AND os.organization_id = mg.organization_id;

-- ===========================================
-- STEP 4: organization_scenarios.experienced_staff 再構築
-- ===========================================
-- ※ is_experienced=true のスタッフのみ（GM可能は担当GMとして表示）
WITH exp_via_scenarios AS (
  SELECT s.scenario_master_id, s.organization_id, st.name
  FROM staff_scenario_assignments ssa
  JOIN scenarios s ON s.id = ssa.scenario_id
  JOIN staff st ON st.id = ssa.staff_id
  WHERE ssa.is_experienced = true
    AND s.scenario_master_id IS NOT NULL
    AND st.name IS NOT NULL AND st.name != ''
),
exp_via_masters AS (
  SELECT ssa.scenario_id AS scenario_master_id, os.organization_id, st.name
  FROM staff_scenario_assignments ssa
  JOIN staff st ON st.id = ssa.staff_id
  JOIN organization_scenarios os ON os.scenario_master_id = ssa.scenario_id
  WHERE ssa.is_experienced = true
    AND ssa.scenario_id IN (SELECT id FROM scenario_masters)
    AND st.name IS NOT NULL AND st.name != ''
),
exp_via_title AS (
  SELECT sm.id AS scenario_master_id, os.organization_id, st.name
  FROM staff_scenario_assignments ssa
  JOIN staff st ON st.id = ssa.staff_id
  JOIN scenarios s ON s.id = ssa.scenario_id
  JOIN scenario_masters sm ON sm.title = s.title
  JOIN organization_scenarios os ON os.scenario_master_id = sm.id
  WHERE ssa.is_experienced = true
    AND st.name IS NOT NULL AND st.name != ''
),
all_exp AS (
  SELECT scenario_master_id, organization_id, name FROM exp_via_scenarios
  UNION
  SELECT scenario_master_id, organization_id, name FROM exp_via_masters
  UNION
  SELECT scenario_master_id, organization_id, name FROM exp_via_title
),
merged_exp AS (
  SELECT scenario_master_id, organization_id,
    ARRAY_AGG(DISTINCT name ORDER BY name) AS exp_list
  FROM all_exp
  WHERE name IS NOT NULL AND name != ''
  GROUP BY scenario_master_id, organization_id
)
UPDATE organization_scenarios os
SET experienced_staff = me.exp_list, updated_at = NOW()
FROM merged_exp me
WHERE os.scenario_master_id = me.scenario_master_id
  AND os.organization_id = me.organization_id;

-- ===========================================
-- STEP 5: organization_scenarios.gm_assignments 再構築
-- ===========================================
WITH gm_data AS (
  SELECT s.scenario_master_id, s.organization_id,
    jsonb_agg(jsonb_build_object(
      'staff_id', ssa.staff_id,
      'staff_name', st.name,
      'can_main_gm', ssa.can_main_gm,
      'can_sub_gm', ssa.can_sub_gm
    ) ORDER BY st.name) AS gm_json
  FROM staff_scenario_assignments ssa
  JOIN scenarios s ON s.id = ssa.scenario_id
  JOIN staff st ON st.id = ssa.staff_id
  WHERE (ssa.can_main_gm = true OR ssa.can_sub_gm = true)
    AND s.scenario_master_id IS NOT NULL
    AND st.name IS NOT NULL
  GROUP BY s.scenario_master_id, s.organization_id
)
UPDATE organization_scenarios os
SET gm_assignments = gd.gm_json, updated_at = NOW()
FROM gm_data gd
WHERE os.scenario_master_id = gd.scenario_master_id
  AND os.organization_id = gd.organization_id;

-- ===========================================
-- STEP 5.5: organization_id がNULLのレコードを修正
-- ===========================================
-- インポートファイルは organization_id なしでINSERTされたため、
-- scenarios テーブルの organization_id を使って埋める
UPDATE staff_scenario_assignments ssa
SET organization_id = s.organization_id
FROM scenarios s
WHERE ssa.scenario_id = s.id
  AND ssa.organization_id IS NULL
  AND s.organization_id IS NOT NULL;

SELECT 'organization_id fixed: ' || COUNT(*) || ' records still NULL' as org_id_status
FROM staff_scenario_assignments WHERE organization_id IS NULL;

-- ===========================================
-- STEP 6: 復元結果の確認
-- ===========================================
SELECT 'After: Total assignments: ' || COUNT(*) as total FROM staff_scenario_assignments;
SELECT 'After: GM-capable: ' || COUNT(*) as gm_count FROM staff_scenario_assignments WHERE can_main_gm = true OR can_sub_gm = true;
SELECT 'After: Experienced-only: ' || COUNT(*) as exp_count FROM staff_scenario_assignments WHERE is_experienced = true;
SELECT 'After: org available_gms set: ' || COUNT(*) as org_gm FROM organization_scenarios WHERE available_gms IS NOT NULL AND available_gms != '{}' AND array_length(available_gms, 1) > 0;
SELECT 'After: org experienced_staff set: ' || COUNT(*) as org_exp FROM organization_scenarios WHERE experienced_staff IS NOT NULL AND experienced_staff != '{}' AND array_length(experienced_staff, 1) > 0;

-- 担当GM数 上位20シナリオ
SELECT sm.title, array_length(os.available_gms, 1) as gm_count, os.available_gms
FROM organization_scenarios os
JOIN scenario_masters sm ON sm.id = os.scenario_master_id
WHERE os.available_gms IS NOT NULL AND os.available_gms != '{}' AND array_length(os.available_gms, 1) > 0
ORDER BY array_length(os.available_gms, 1) DESC
LIMIT 20;

-- 体験済み数 上位20シナリオ
SELECT sm.title, array_length(os.experienced_staff, 1) as exp_count, os.experienced_staff
FROM organization_scenarios os
JOIN scenario_masters sm ON sm.id = os.scenario_master_id
WHERE os.experienced_staff IS NOT NULL AND os.experienced_staff != '{}' AND array_length(os.experienced_staff, 1) > 0
ORDER BY array_length(os.experienced_staff, 1) DESC
LIMIT 20;