/**
 * 日本語（ひらがな・カタカナ）をローマ字に変換するユーティリティ
 */

// ひらがな→ローマ字変換表
const hiraganaToRomaji: Record<string, string> = {
  // 基本
  'あ': 'a', 'い': 'i', 'う': 'u', 'え': 'e', 'お': 'o',
  'か': 'ka', 'き': 'ki', 'く': 'ku', 'け': 'ke', 'こ': 'ko',
  'さ': 'sa', 'し': 'shi', 'す': 'su', 'せ': 'se', 'そ': 'so',
  'た': 'ta', 'ち': 'chi', 'つ': 'tsu', 'て': 'te', 'と': 'to',
  'な': 'na', 'に': 'ni', 'ぬ': 'nu', 'ね': 'ne', 'の': 'no',
  'は': 'ha', 'ひ': 'hi', 'ふ': 'fu', 'へ': 'he', 'ほ': 'ho',
  'ま': 'ma', 'み': 'mi', 'む': 'mu', 'め': 'me', 'も': 'mo',
  'や': 'ya', 'ゆ': 'yu', 'よ': 'yo',
  'ら': 'ra', 'り': 'ri', 'る': 'ru', 'れ': 're', 'ろ': 'ro',
  'わ': 'wa', 'を': 'wo', 'ん': 'n',
  // 濁音
  'が': 'ga', 'ぎ': 'gi', 'ぐ': 'gu', 'げ': 'ge', 'ご': 'go',
  'ざ': 'za', 'じ': 'ji', 'ず': 'zu', 'ぜ': 'ze', 'ぞ': 'zo',
  'だ': 'da', 'ぢ': 'di', 'づ': 'du', 'で': 'de', 'ど': 'do',
  'ば': 'ba', 'び': 'bi', 'ぶ': 'bu', 'べ': 'be', 'ぼ': 'bo',
  // 半濁音
  'ぱ': 'pa', 'ぴ': 'pi', 'ぷ': 'pu', 'ぺ': 'pe', 'ぽ': 'po',
  // 拗音
  'きゃ': 'kya', 'きゅ': 'kyu', 'きょ': 'kyo',
  'しゃ': 'sha', 'しゅ': 'shu', 'しょ': 'sho',
  'ちゃ': 'cha', 'ちゅ': 'chu', 'ちょ': 'cho',
  'にゃ': 'nya', 'にゅ': 'nyu', 'にょ': 'nyo',
  'ひゃ': 'hya', 'ひゅ': 'hyu', 'ひょ': 'hyo',
  'みゃ': 'mya', 'みゅ': 'myu', 'みょ': 'myo',
  'りゃ': 'rya', 'りゅ': 'ryu', 'りょ': 'ryo',
  'ぎゃ': 'gya', 'ぎゅ': 'gyu', 'ぎょ': 'gyo',
  'じゃ': 'ja', 'じゅ': 'ju', 'じょ': 'jo',
  'びゃ': 'bya', 'びゅ': 'byu', 'びょ': 'byo',
  'ぴゃ': 'pya', 'ぴゅ': 'pyu', 'ぴょ': 'pyo',
  // 小文字
  'ぁ': 'a', 'ぃ': 'i', 'ぅ': 'u', 'ぇ': 'e', 'ぉ': 'o',
  'ゃ': 'ya', 'ゅ': 'yu', 'ょ': 'yo',
  'っ': '', // 促音（次の子音を重ねる処理は別途）
  // 長音
  'ー': '',
}

// カタカナ→ひらがな変換
function katakanaToHiragana(str: string): string {
  return str.replace(/[\u30A1-\u30F6]/g, (char) => {
    return String.fromCharCode(char.charCodeAt(0) - 0x60)
  })
}

// 漢字の読み仮名マッピング（よく使われるシナリオ名用、重複なし）
const kanjiReadings: Record<string, string> = {
  '愛': 'ai',
  '哀': 'ai',
  '悪': 'aku',
  '明': 'aka',
  '赤': 'aka',
  '秋': 'aki',
  '青': 'ao',
  '蒼': 'sou',
  '暗': 'an',
  '闇': 'yami',
  '雨': 'ame',
  '嵐': 'arashi',
  '海': 'umi',
  '歌': 'uta',
  '永': 'ei',
  '影': 'kage',
  '園': 'en',
  '炎': 'en',
  '宴': 'en',
  '縁': 'en',
  '王': 'ou',
  '黄': 'ou',
  '桜': 'sakura',
  '奥': 'oku',
  '音': 'oto',
  '花': 'hana',
  '華': 'ka',
  '火': 'hi',
  '夏': 'natsu',
  '家': 'ie',
  '回': 'kai',
  '開': 'kai',
  '怪': 'kai',
  '界': 'kai',
  '学': 'gaku',
  '楽': 'gaku',
  '神': 'kami',
  '雷': 'kaminari',
  '紙': 'kami',
  '川': 'kawa',
  '河': 'kawa',
  '館': 'kan',
  '感': 'kan',
  '間': 'kan',
  '危': 'ki',
  '気': 'ki',
  '記': 'ki',
  '奇': 'ki',
  '鬼': 'oni',
  '貴': 'ki',
  '輝': 'ki',
  '金': 'kin',
  '銀': 'gin',
  '禁': 'kin',
  '空': 'sora',
  '宮': 'miya',
  '九': 'ku',
  '苦': 'ku',
  '黒': 'kuro',
  '蔵': 'kura',
  '倉': 'kura',
  '血': 'chi',
  '結': 'ketsu',
  '月': 'tsuki',
  '決': 'ketsu',
  '剣': 'ken',
  '見': 'ken',
  '言': 'gen',
  '現': 'gen',
  '幻': 'gen',
  '元': 'gen',
  '原': 'gen',
  '古': 'ko',
  '湖': 'ko',
  '己': 'ko',
  '孤': 'ko',
  '光': 'hikari',
  '紅': 'kou',
  '高': 'kou',
  '香': 'kou',
  '恋': 'koi',
  '国': 'koku',
  '刻': 'koku',
  '告': 'koku',
  '獄': 'goku',
  '今': 'kon',
  '魂': 'kon',
  '最': 'sai',
  '祭': 'matsuri',
  '災': 'sai',
  '彩': 'sai',
  '殺': 'satsu',
  '山': 'yama',
  '三': 'san',
  '惨': 'san',
  '散': 'san',
  '死': 'shi',
  '四': 'shi',
  '詩': 'shi',
  '私': 'shi',
  '視': 'shi',
  '時': 'toki',
  '次': 'ji',
  '事': 'ji',
  '自': 'ji',
  '寺': 'ji',
  '地': 'chi',
  '七': 'nana',
  '失': 'shitsu',
  '室': 'shitsu',
  '島': 'shima',
  '写': 'sha',
  '者': 'sha',
  '社': 'sha',
  '車': 'sha',
  '主': 'shu',
  '守': 'shu',
  '手': 'te',
  '酒': 'sake',
  '終': 'shuu',
  '集': 'shuu',
  '十': 'juu',
  '重': 'juu',
  '春': 'haru',
  '純': 'jun',
  '初': 'hatsu',
  '所': 'sho',
  '書': 'sho',
  '女': 'jo',
  '小': 'shou',
  '少': 'shou',
  '消': 'shou',
  '笑': 'shou',
  '証': 'shou',
  '勝': 'shou',
  '城': 'shiro',
  '場': 'ba',
  '上': 'jou',
  '情': 'jou',
  '常': 'jou',
  '状': 'jou',
  '森': 'mori',
  '心': 'kokoro',
  '真': 'shin',
  '新': 'shin',
  '深': 'shin',
  '信': 'shin',
  '進': 'shin',
  '親': 'shin',
  '人': 'hito',
  '仁': 'jin',
  '刃': 'jin',
  '陣': 'jin',
  '図': 'zu',
  '頭': 'atama',
  '水': 'mizu',
  '世': 'yo',
  '星': 'hoshi',
  '声': 'koe',
  '生': 'sei',
  '聖': 'sei',
  '正': 'sei',
  '精': 'sei',
  '西': 'sei',
  '清': 'sei',
  '性': 'sei',
  '雪': 'yuki',
  '説': 'setsu',
  '絶': 'zetsu',
  '節': 'setsu',
  '切': 'setsu',
  '船': 'fune',
  '戦': 'sen',
  '先': 'sen',
  '千': 'sen',
  '泉': 'sen',
  '選': 'sen',
  '線': 'sen',
  '前': 'mae',
  '全': 'zen',
  '然': 'zen',
  '相': 'sou',
  '想': 'sou',
  '創': 'sou',
  '葬': 'sou',
  '早': 'sou',
  '草': 'sou',
  '双': 'sou',
  '族': 'zoku',
  '続': 'zoku',
  '村': 'mura',
  '存': 'son',
  '尊': 'son',
  '大': 'dai',
  '代': 'dai',
  '台': 'dai',
  '題': 'dai',
  '隊': 'tai',
  '第': 'dai',
  '体': 'tai',
  '探': 'tan',
  '単': 'tan',
  '短': 'tan',
  '誕': 'tan',
  '団': 'dan',
  '断': 'dan',
  '弾': 'dan',
  '段': 'dan',
  '男': 'dan',
  '知': 'chi',
  '智': 'chi',
  '池': 'ike',
  '中': 'naka',
  '虫': 'mushi',
  '注': 'chuu',
  '宙': 'chuu',
  '朝': 'asa',
  '蝶': 'chou',
  '超': 'chou',
  '長': 'chou',
  '町': 'machi',
  '調': 'chou',
  '追': 'tsui',
  '痛': 'tsuu',
  '通': 'tsuu',
  '天': 'ten',
  '転': 'ten',
  '点': 'ten',
  '伝': 'den',
  '田': 'ta',
  '殿': 'den',
  '電': 'den',
  '都': 'to',
  '土': 'do',
  '塔': 'tou',
  '党': 'tou',
  '倒': 'tou',
  '投': 'tou',
  '逃': 'tou',
  '灯': 'tou',
  '当': 'tou',
  '東': 'tou',
  '統': 'tou',
  '闘': 'tou',
  '答': 'tou',
  '盗': 'tou',
  '道': 'michi',
  '読': 'doku',
  '毒': 'doku',
  '独': 'doku',
  '特': 'toku',
  '得': 'toku',
  '徳': 'toku',
  '二': 'ni',
  '日': 'hi',
  '入': 'nyu',
  '忍': 'nin',
  '認': 'nin',
  '年': 'nen',
  '念': 'nen',
  '燃': 'nen',
  '能': 'nou',
  '脳': 'nou',
  '農': 'nou',
  '破': 'ha',
  '馬': 'uma',
  '波': 'nami',
  '派': 'ha',
  '覇': 'ha',
  '背': 'hai',
  '敗': 'hai',
  '灰': 'hai',
  '配': 'hai',
  '白': 'shiro',
  '伯': 'haku',
  '迫': 'haku',
  '泊': 'haku',
  '博': 'haku',
  '薄': 'haku',
  '箱': 'hako',
  '八': 'hachi',
  '発': 'hatsu',
  '罰': 'batsu',
  '抜': 'batsu',
  '半': 'han',
  '反': 'han',
  '犯': 'han',
  '判': 'han',
  '晩': 'ban',
  '番': 'ban',
  '般': 'han',
  '盤': 'ban',
  '飯': 'han',
  '板': 'ban',
  '版': 'han',
  '悲': 'hi',
  '飛': 'hi',
  '秘': 'hi',
  '費': 'hi',
  '非': 'hi',
  '被': 'hi',
  '皮': 'hi',
  '避': 'hi',
  '彼': 'kare',
  '百': 'hyaku',
  '表': 'hyou',
  '氷': 'hyou',
  '病': 'byou',
  '猫': 'neko',
  '品': 'hin',
  '浜': 'hama',
  '貧': 'hin',
  '不': 'fu',
  '負': 'fu',
  '婦': 'fu',
  '夫': 'otto',
  '富': 'fu',
  '付': 'fu',
  '府': 'fu',
  '浮': 'fu',
  '腐': 'fu',
  '布': 'fu',
  '普': 'fu',
  '父': 'chichi',
  '怖': 'fu',
  '武': 'bu',
  '部': 'bu',
  '風': 'kaze',
  '封': 'fuu',
  '服': 'fuku',
  '福': 'fuku',
  '副': 'fuku',
  '幅': 'fuku',
  '復': 'fuku',
  '腹': 'fuku',
  '複': 'fuku',
  '物': 'mono',
  '仏': 'butsu',
  '粉': 'fun',
  '奮': 'fun',
  '噴': 'fun',
  '兵': 'hei',
  '平': 'hei',
  '並': 'hei',
  '閉': 'hei',
  '餅': 'mochi',
  '米': 'bei',
  '壁': 'kabe',
  '碧': 'heki',
  '変': 'hen',
  '偏': 'hen',
  '編': 'hen',
  '片': 'hen',
  '辺': 'hen',
  '返': 'hen',
  '歩': 'ho',
  '保': 'ho',
  '補': 'ho',
  '墓': 'haka',
  '法': 'hou',
  '放': 'hou',
  '報': 'hou',
  '方': 'hou',
  '訪': 'hou',
  '包': 'hou',
  '宝': 'hou',
  '抱': 'hou',
  '砲': 'hou',
  '峰': 'mine',
  '鳳': 'hou',
  '芳': 'hou',
  '蜂': 'hachi',
  '亡': 'bou',
  '忘': 'bou',
  '忙': 'bou',
  '望': 'bou',
  '坊': 'bou',
  '妨': 'bou',
  '房': 'bou',
  '冒': 'bou',
  '帽': 'bou',
  '棒': 'bou',
  '暴': 'bou',
  '謀': 'bou',
  '防': 'bou',
  '北': 'kita',
  '僕': 'boku',
  '牧': 'boku',
  '墨': 'boku',
  '本': 'hon',
  '奔': 'hon',
  '凡': 'bon',
  '盆': 'bon',
  '魔': 'ma',
  '麻': 'asa',
  '磨': 'ma',
  '魅': 'mi',
  '味': 'aji',
  '未': 'mi',
  '実': 'mi',
  '密': 'mitsu',
  '蜜': 'mitsu',
  '民': 'min',
  '眠': 'min',
  '無': 'mu',
  '夢': 'yume',
  '舞': 'mai',
  '霧': 'kiri',
  '務': 'mu',
  '名': 'na',
  '命': 'mei',
  '迷': 'mei',
  '鳴': 'mei',
  '盟': 'mei',
  '銘': 'mei',
  '滅': 'metsu',
  '免': 'men',
  '面': 'men',
  '綿': 'men',
  '麺': 'men',
  '木': 'ki',
  '黙': 'moku',
  '目': 'me',
  '模': 'mo',
  '母': 'haha',
  '茂': 'mo',
  '毛': 'ke',
  '猛': 'mou',
  '盲': 'mou',
  '網': 'mou',
  '門': 'mon',
  '紋': 'mon',
  '問': 'mon',
  '文': 'bun',
  '夜': 'yoru',
  '野': 'no',
  '矢': 'ya',
  '役': 'yaku',
  '約': 'yaku',
  '薬': 'yaku',
  '訳': 'yaku',
  '躍': 'yaku',
  '唯': 'yui',
  '優': 'yuu',
  '友': 'tomo',
  '有': 'yuu',
  '勇': 'yuu',
  '幽': 'yuu',
  '悠': 'yuu',
  '憂': 'yuu',
  '裕': 'yuu',
  '遊': 'yuu',
  '雄': 'yuu',
  '融': 'yuu',
  '由': 'yuu',
  '油': 'yu',
  '愉': 'yu',
  '輸': 'yu',
  '癒': 'yu',
  '羊': 'hitsuji',
  '洋': 'you',
  '要': 'you',
  '陽': 'you',
  '葉': 'ha',
  '様': 'you',
  '踊': 'you',
  '容': 'you',
  '溶': 'you',
  '曜': 'you',
  '養': 'you',
  '妖': 'you',
  '幼': 'you',
  '用': 'you',
  '揚': 'you',
  '遥': 'you',
  '抑': 'yoku',
  '欲': 'yoku',
  '浴': 'yoku',
  '翌': 'yoku',
  '翼': 'yoku',
  '落': 'raku',
  '絡': 'raku',
  '乱': 'ran',
  '卵': 'ran',
  '覧': 'ran',
  '藍': 'ran',
  '蘭': 'ran',
  '利': 'ri',
  '理': 'ri',
  '裏': 'ura',
  '里': 'ri',
  '離': 'ri',
  '璃': 'ri',
  '李': 'ri',
  '梨': 'nashi',
  '莉': 'ri',
  '律': 'ritsu',
  '率': 'ritsu',
  '立': 'ritsu',
  '隆': 'ryuu',
  '竜': 'ryuu',
  '龍': 'ryuu',
  '流': 'ryuu',
  '留': 'ryuu',
  '粒': 'ryuu',
  '柳': 'ryuu',
  '琉': 'ryuu',
  '瑠': 'ru',
  '了': 'ryou',
  '両': 'ryou',
  '涼': 'ryou',
  '良': 'ryou',
  '量': 'ryou',
  '陵': 'ryou',
  '領': 'ryou',
  '療': 'ryou',
  '糧': 'ryou',
  '遼': 'ryou',
  '僚': 'ryou',
  '寮': 'ryou',
  '綾': 'aya',
  '菱': 'hishi',
  '凌': 'ryou',
  '亮': 'ryou',
  '力': 'chikara',
  '緑': 'midori',
  '林': 'hayashi',
  '輪': 'wa',
  '隣': 'rin',
  '臨': 'rin',
  '琳': 'rin',
  '鱗': 'rin',
  '涙': 'rui',
  '累': 'rui',
  '塁': 'rui',
  '類': 'rui',
  '令': 'rei',
  '例': 'rei',
  '冷': 'rei',
  '励': 'rei',
  '怜': 'rei',
  '玲': 'rei',
  '礼': 'rei',
  '鈴': 'suzu',
  '零': 'rei',
  '霊': 'rei',
  '麗': 'rei',
  '齢': 'rei',
  '暦': 'reki',
  '歴': 'reki',
  '列': 'retsu',
  '劣': 'retsu',
  '烈': 'retsu',
  '裂': 'retsu',
  '連': 'ren',
  '練': 'ren',
  '錬': 'ren',
  '廉': 'ren',
  '蓮': 'ren',
  '路': 'ro',
  '露': 'ro',
  '労': 'rou',
  '郎': 'rou',
  '朗': 'rou',
  '廊': 'rou',
  '楼': 'rou',
  '浪': 'rou',
  '漏': 'rou',
  '老': 'rou',
  '狼': 'rou',
  '籠': 'rou',
  '六': 'roku',
  '録': 'roku',
  '論': 'ron',
  '和': 'wa',
  '話': 'hanashi',
  '惑': 'waku',
  '枠': 'waku',
  '湾': 'wan',
  '腕': 'wan',
}

/**
 * 日本語テキストをローマ字（slug用）に変換
 */
export function toRomaji(text: string): string {
  // カタカナをひらがなに変換
  let result = katakanaToHiragana(text)
  
  // 漢字を読み仮名に置換
  for (const [kanji, reading] of Object.entries(kanjiReadings)) {
    result = result.replace(new RegExp(kanji, 'g'), reading)
  }
  
  // 拗音を先に変換（2文字のパターン）
  const youon = ['きゃ', 'きゅ', 'きょ', 'しゃ', 'しゅ', 'しょ', 'ちゃ', 'ちゅ', 'ちょ', 
                 'にゃ', 'にゅ', 'にょ', 'ひゃ', 'ひゅ', 'ひょ', 'みゃ', 'みゅ', 'みょ',
                 'りゃ', 'りゅ', 'りょ', 'ぎゃ', 'ぎゅ', 'ぎょ', 'じゃ', 'じゅ', 'じょ',
                 'びゃ', 'びゅ', 'びょ', 'ぴゃ', 'ぴゅ', 'ぴょ']
  for (const y of youon) {
    if (hiraganaToRomaji[y]) {
      result = result.replace(new RegExp(y, 'g'), hiraganaToRomaji[y])
    }
  }
  
  // 促音（っ）の処理
  result = result.replace(/っ([かきくけこさしすせそたちつてとはひふへほぱぴぷぺぽ])/g, (_, next) => {
    const nextRomaji = hiraganaToRomaji[next] || next
    return nextRomaji.charAt(0) + nextRomaji
  })
  result = result.replace(/っ/g, '')
  
  // 残りのひらがなを変換
  for (const [hira, roma] of Object.entries(hiraganaToRomaji)) {
    if (hira.length === 1) { // 単一文字のみ
      result = result.replace(new RegExp(hira, 'g'), roma)
    }
  }
  
  // 英数字はそのまま小文字に
  result = result.toLowerCase()
  
  // スペースや記号をハイフンに変換
  result = result.replace(/[\s　・:：\-_]+/g, '-')
  
  // 英数字とハイフン以外を削除
  result = result.replace(/[^a-z0-9-]/g, '')
  
  // 連続するハイフンを1つに
  result = result.replace(/-+/g, '-')
  
  // 先頭と末尾のハイフンを削除
  result = result.replace(/^-|-$/g, '')
  
  return result
}

/**
 * タイトルからslugを生成（ユーザー確認用）
 */
export function generateSlugFromTitle(title: string): string {
  return toRomaji(title)
}
